table _Medidas
	lineageTag: 0e83e21d-5d18-4dbe-a026-1692a30648a5

	measure Ultima_atualizacao = ```
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			RETURN
			SWITCH(
			    _selecaoIdioma,
			    1,Max(ult_atualizacao[PT]),
			    
			    2,Max(ult_atualizacao[DE]),
			    
			    3,Max(ult_atualizacao[EN])
			)
			```
		isHidden
		displayFolder: Atualização
		lineageTag: 388a76e3-793d-4618-a36a-5153edf6e22a

	measure PesoFaturado = ```
			
			    DIVIDE(
			        SUM(fFaturamento[peso_liq_kg])
			        ,1000
			    )
			```
		displayFolder: Geral
		lineageTag: f23532ea-5583-46b6-aba0-d671534d4af3

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Faturamento com taxa' = SUM(fFaturamento[vl_total_item])
		displayFolder: Geral
		lineageTag: f399a584-9daf-47d4-8edf-17ff78f41940

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Faturamento sem taxa' = ```
			
			SUMX(
			    fFaturamento,
			    fFaturamento[vl_total_item] 
			    -fFaturamento[vl_cofins]
			    -fFaturamento[vl_icms]
			    -fFaturamento[vl_ipi]
			    -fFaturamento[vl_pis]
			)
			```
		displayFolder: Geral
		lineageTag: 5e2031b8-eeb8-4853-996d-7a41a4957e02

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preco Medio com imposto' = DIVIDE([Faturamento com taxa],[PesoFaturado])
		displayFolder: Geral
		lineageTag: 4659d5ab-ced6-4904-88f8-4e0caa035567

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Preco Medio sem imposto' =
			
			DIVIDE(
			        [Faturamento sem taxa]
			        ,[PesoFaturado]
			    )
		displayFolder: Geral
		lineageTag: b25ee09d-af46-4ac5-be49-383d51cf8f90

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Abatimento = 0 --SUM(fFaturamento[vl_abatimento])
		isHidden
		displayFolder: Geral
		lineageTag: cea7797f-e9e3-4a0c-b46c-88e23b528675

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Devoluções =
			
			CALCULATE(
			    SUM(fDevolucao[vl_total_item]),
			    dMotivoDevolucao[descr_motivdev] in VALUES(ptiposegmentacao[Parâmetro Campos])
			)
		displayFolder: Geral
		lineageTag: 8b9cf3ec-f8be-4259-bfca-4e34d8e171f6

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Imposto =
			
			SUMX(
			    fFaturamento,
			    fFaturamento[vl_cofins]
			    +fFaturamento[vl_icms]
			    +fFaturamento[vl_ipi]
			    +fFaturamento[vl_pis]
			)
		displayFolder: Geral
		lineageTag: b3f9b1d8-cc70-4997-952d-b2eaa6bf9226

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Gross Margin (R$)' = [Faturamento com taxa] - [Abatimento] - [Devoluções] - [Imposto]
		displayFolder: Geral
		lineageTag: 59a22950-0068-44d3-aa90-e12a9b436c96

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Faturamento =
			
			VAR _calculo =
			IF(
			    SELECTEDVALUE(pFaturamento[sFaturamento Pedido]) = 1
			    , [Faturamento com taxa]
			    , [Faturamento sem taxa]
			)
			
			RETURN
			IF(NOT ISBLANK (_calculo),_calculo)
		displayFolder: Geral
		lineageTag: 532c63c6-f7bb-42e5-9424-b446c0b51d5d

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Preco Medio' = ```
			
			var _calculo = 
			IF(
			    SELECTEDVALUE(pFaturamento[sFaturamento Pedido]) = 1
			    , [Preco Medio com imposto]
			    , [Preco Medio sem imposto]
			)
			RETURN 
			IF(NOT ISBLANK (_calculo),DIVIDE(_calculo,1000))
			```
		displayFolder: Geral
		lineageTag: 1b3eba82-6015-4f59-a6c6-0d668a34fc0c

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.000"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.000",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Devoluções t' = ```
			
			CALCULATE(
			    DIVIDE( 
			        SUM(fDevolucao[peso_liq_kg])
			        ,1000
			    ),
			    dMotivoDevolucao[descr_motivdev] in VALUES(ptiposegmentacao[Parâmetro Campos])
			)
			```
		displayFolder: Geral
		lineageTag: 220ac1f1-0827-462d-baac-bd180f487650

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd. Pedidos' = DISTINCTCOUNT(fFaturamento[id_pedido])
		displayFolder: Geral
		lineageTag: 5b40c825-441d-4640-830d-cddc5152f9f6

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.#B",
				    ABS( _valor) >= 1E6, "#,,.#M",
				    ABS( _valor) >= 1E3, "#,.#K",
				    "#,,,0.#"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.#",
				    1,_formatoDinamico,
				    2, "#,.#K",
				    3, "#,,.#M",
				    4, "#,,,.#B"
				)
				
				```

	measure Desc_Ajuda = SELECTEDVALUE(fhelp[Descrição])
		isHidden
		displayFolder: Geral
		lineageTag: 1ed2fe25-9c47-4310-9fcf-6ada493f9561

	measure 'Local Market Sales (t)' =
			
			CALCULATE(
			    [PesoFaturado],
			    KEEPFILTERS(dClientes[mercado] = "Interno"),
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] = "REL")
			)
		displayFolder: KPIs
		lineageTag: 5b8a229b-0269-4ccf-b03b-9d2629590202

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Export Market Sales (t)' =
			
			CALCULATE(
			    [PesoFaturado],
			    KEEPFILTERS(dClientes[mercado] = "Externo"),
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] = "REL")
			)
		displayFolder: KPIs
		lineageTag: f5cc4265-864e-4153-8679-6adce083eb46

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit Total (R$/t)' =
			
			VAR _custoFull=  CALCULATE(SUM(febtida_artigo_coml[custo_mp_full]),REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL"))
			VAR _PesoFaturado = CALCULATE(SUM(febtida_artigo_coml[Peso_faturado]),REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL"))
			VAR _PesoSucata = CALCULATE(SUM(febtida_artigo_coml[Peso_Sucata]),REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL"))
			VAR _tonelada = DIVIDE(_PesoFaturado + _PesoSucata, 1000)
			VAR _receita_por_ton = [Faturamento por tonelada]
			
			RETURN
			
			_receita_por_ton -
			DIVIDE(
			    _custoFull,
			    _tonelada
			)
		displayFolder: KPIs
		lineageTag: 91173108-1f64-420c-ba83-23fc2107e65c

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Total Market Sales (t)' = [Local Market Sales (t)] + [Export Market Sales (t)]
		displayFolder: KPIs
		lineageTag: 59a8c6f6-3dbd-491a-8659-abf804576439

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Cold Rolled (market Sales: Local + Export) (t)' =
			
			CALCULATE(
			    [PesoFaturado],
			    dArtigo[rota] = "Com Laminação",
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] = "REL")
			)
		displayFolder: KPIs
		lineageTag: c5bf6d7e-32f5-4c62-a660-b2bb83c3671d

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantidade de deméritos' = SUM(fIQF[nota])
		formatString: 0
		displayFolder: KPIs
		lineageTag: f115e543-f2bb-4cab-a279-f66dadec870a

	measure 'Coated Sales Volumes (t)' =
			
			CALCULATE(
			    [PesoFaturado],
			    dArtigo[revestimento] <> "*",
			    dArtigo[revestimento] <> "",
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] = "REL")
			)
		displayFolder: KPIs
		lineageTag: 4db9f351-72b6-406c-9bb8-4b1332035b10

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'H&T Sales Volumes (t)' =
			
			CALCULATE(
			    [PesoFaturado],
			    dArtigo[temperado] <> "*",
			    dArtigo[temperado] <> "",
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] = "REL")
			)
		displayFolder: KPIs
		lineageTag: 4867dd16-500f-4048-a634-2d25318ba970

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Sales (KBRL)' = ```
			
			var _selecao = SELECTEDVALUE(pFaturamento[sFaturamento Pedido])
			VAR _calculo =
			IF(
			    SELECTEDVALUE(pFaturamento[sFaturamento Pedido]) = 1
			    ,CALCULATE(
			            SUM(fFaturamento[vl_total_item]),
			            REMOVEFILTERS(dArtigo[identificacao]),
			            dArtigo[identificacao] IN {"M.Obra","MO Decap"}
			            )
			    ,SUMX(
			        CALCULATETABLE(
			            fFaturamento,
			            REMOVEFILTERS(dArtigo[identificacao]),
			            KEEPFILTERS(dArtigo[identificacao] IN {"M.Obra","MO Decap"})
			            ),
			            fFaturamento[vl_total_item]
			            -fFaturamento[vl_cofins]
			            -fFaturamento[vl_icms]
			            -fFaturamento[vl_ipi]
			            -fFaturamento[vl_pis]
			        )   
			)
			
			RETURN
			DIVIDE(_calculo,1000)
			```
		displayFolder: KPIs
		lineageTag: 58981e75-cda0-42f6-9921-9de3a864f202

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Customer Projects' = BLANK()
		displayFolder: KPIs
		lineageTag: fab4b57e-b42a-40aa-a3ab-5cca8b785f32

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Gross Profit - Cold Rolled (R$/t)' = ```
			
			CALCULATE(
			    [Gross Profit Total (R$/t)],
			    dArtigo[rota] = "Com Laminação",
			    dArtigo[identificacao] = "REL"
			)
			
			```
		displayFolder: KPIs
		lineageTag: acf69113-fca3-4c9e-aaed-a67089b11192

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Indice Insatisfação' = ```
			
			SUMX(
			    ADDCOLUMNS(
			        VALUES(dCalendario[ano_mes_numerico]),
			        "@Indice",
			        VAR _ano = [ano_mes_numerico]
			        VAR _tab = 
			        CALCULATETABLE(
			            VALUES(fIQF[id_cliente]),
			            KEEPFILTERS(fIQF[nota] = 1),
			            KEEPFILTERS(dCalendario[ano_mes_numerico] = _ano),
			            KEEPFILTERS(fIQF[grupo] = 1)
			        )
			        RETURN
			        COUNTROWS(_tab)
			    ),[@Indice]
			)
			```
		displayFolder: KPIs
		lineageTag: 505046f7-173d-403f-bcce-bb3997cc9fff

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,B",
				    ABS( _valor) >= 1E6, "#,,M",
				    ABS( _valor) >= 1E3, "#,K",
				    "#0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#0",
				    1,_formatoDinamico,
				    2, "#,K",
				    3, "#,,M",
				    4, "#,,,B"
				)
				```

	measure 'HTML - Cards Scorecard' = ```
			
			VAR _Data = MAX(dCalendario[data])<=TODAY()
			
			VAR __LocalMarket_Invoiced = [Local Market Sales (t)]
			VAR __LocalMarket_Target = [LocalMarketSales_Target] 
			VAR __LocalMarket_Budget =  [LocalMarketSales_Budget]  
			VAR __LocalMarket_Forecast =  [LocalMarketSales_forecast] 
			
			VAR __ColdRolled_Invoiced = [Cold Rolled (market Sales: Local + Export) (t)] 
			VAR __ColdRolled_Target = [Cold Rolled_target] 
			VAR __ColdRolled_Budget = [Cold Rolled_Budget]
			VAR __ColdRolled_Forecast = [Cold Rolled_Forecast]
			
			VAR __ExportMarket_Invoiced = [Export Market Sales (t)] 
			VAR __ExportMarket_Target = [ExportMarketSales_Target]
			VAR __ExportMarket_Budget = [ExportMarketSales_Budget] 
			VAR __ExportMarket_Forecast = [ExportMarketSales_forecast] 
			
			VAR __ServiceSales_Invoiced = [Service Sales (KBRL)] 
			VAR __ServiceSales_Target = [Service Sales (KBRL) target] 
			VAR __ServiceSales_Budget = [Service Sales (KBRL) budget]  
			VAR __ServiceSales_Forecast = [Service Sales (KBRL) forecast]  
			
			VAR _validacao = IF(_Data,0)
			VAR __Customer_Satisfaction_Invoiced = [Indice Insatisfação]   
			VAR __Customer_Satisfaction_Target = _validacao
			VAR __Customer_Satisfaction_Budget = _validacao
			VAR __Customer_Satisfaction_Forecast = _validacao 
			
			VAR __GrossProfitTotal_Invoiced = [Gross Profit Total (R$/t)]
			VAR __GrossProfitTotal_Target = [Gross Profit Total (R$/t)_Target] 
			VAR __GrossProfitTotal_Budget = [Gross Profit Total (R$/t)_budget] 
			VAR __GrossProfitTotal_Forecast = [Gross Profit Total (R$/t)_forecast] 
			
			VAR __GrossProfitPercent_Invoiced = [Gross Profit (%)] 
			VAR __GrossProfitPercent_Target = [GrossProfit_target (%)]
			VAR __GrossProfitPercent_Budget = [GrossProfit_budget (%)]
			VAR __GrossProfitPercent_Forecast = [GrossProfit_forecast (%)]
			
			VAR __Gross_Margin_Cold_Rolled_Invoiced = [Gross Profit - Cold Rolled (R$/t)] 
			VAR __Gross_Margin_Cold_Rolled_Target = [Gross Profit cold rolled (R$/t)_target]  
			VAR __Gross_Margin_Cold_Rolled_Budget = [Gross Profit cold rolled (R$/t)_budget] 
			VAR __Gross_Margin_Cold_Rolled_Forecast = [Gross Profit cold rolled (R$/t)_forecast] 
			
			VAR __Customer_projects_Invoiced = 0--[Customer Projects]  
			VAR __Customer_projects_Target = 0--1 
			VAR __Customer_projects_Budget = 0--1 
			VAR __Customer_projects_Forecast = 0-- 1 
			
			VAR __Coated_Sales_Volume_Invoiced = [Coated Sales Volumes (t)]   
			VAR __Coated_Sales_Volume_Target = [Coated Sales Volume_target] 
			VAR __Coated_Sales_Volume_Budget = [Coated Sales Volume_Budget]  
			VAR __Coated_Sales_Volume_Forecast = [Coated Sales Volume_forecast]   
			
			VAR __HeTSalesVolume_Invoiced = [H&T Sales Volumes (t)]
			VAR __HeTSalesVolume_Target = [H&T Sales Volume_target]
			VAR __HeTSalesVolume_Budget = [H&T Sales Volume_Budget]
			VAR __HeTSalesVolume_Forecast = [H&T Sales Volume_forecast] 
			
			VAR __TotalMarketSales_Invoiced = [Total Market Sales (t)]
			VAR __TotalMarketSales_Target = [TotalMarketSales_Target]
			VAR __TotalMarketSales_Budget = [TotalMarketSales_Budget] 
			VAR __TotalMarketSales_Forecast = [TotalMarketSales_forecast]
			
			VAR __Revenue_Invoiced = [Faturamento] 
			VAR __Revenue_Target = [Faturamento_target]  
			VAR __Revenue_Budget = [Faturamento_budget]  
			VAR __Revenue_Forecast = [Faturamento_forecast]  
			
			VAR __AveragePrice_Invoiced = [Preco Medio]
			VAR __AveragePrice_Target = [Preco Medio_target] 
			VAR __AveragePrice_Budget = [Preco Medio_budget] 
			VAR __AveragePrice_Forecast = [Preco Medio_forecast]
			
			-- Variáveis Percentuais
			VAR __LocalMarket_PercentTarget = DIVIDE(__LocalMarket_Invoiced - __LocalMarket_Target, __LocalMarket_Target, 0)
			VAR __LocalMarket_PercentBudget = DIVIDE(__LocalMarket_Invoiced - __LocalMarket_Budget, __LocalMarket_Budget, 0)
			VAR __LocalMarket_PercentForecast = DIVIDE(__LocalMarket_Invoiced - __LocalMarket_Forecast, __LocalMarket_Forecast, 0)
			
			VAR __ColdRolled_PercentTarget = DIVIDE(__ColdRolled_Invoiced - __ColdRolled_Target, __ColdRolled_Target, 0)
			VAR __ColdRolled_PercentBudget = DIVIDE(__ColdRolled_Invoiced - __ColdRolled_Budget, __ColdRolled_Budget, 0)
			VAR __ColdRolled_PercentForecast = DIVIDE(__ColdRolled_Invoiced - __ColdRolled_Forecast, __ColdRolled_Forecast, 0)
			
			VAR __ExportMarket_PercentTarget = DIVIDE(__ExportMarket_Invoiced - __ExportMarket_Target, __ExportMarket_Target, 0)
			VAR __ExportMarket_PercentBudget = DIVIDE(__ExportMarket_Invoiced - __ExportMarket_Budget, __ExportMarket_Budget, 0)
			VAR __ExportMarket_PercentForecast = DIVIDE(__ExportMarket_Invoiced - __ExportMarket_Forecast, __ExportMarket_Forecast, 0)
			
			VAR __ServiceSales_PercentTarget = DIVIDE(__ServiceSales_Invoiced - __ServiceSales_Target, __ServiceSales_Target, 0)
			VAR __ServiceSales_PercentBudget = DIVIDE(__ServiceSales_Invoiced - __ServiceSales_Budget, __ServiceSales_Budget, 0)
			VAR __ServiceSales_PercentForecast = DIVIDE(__ServiceSales_Invoiced - __ServiceSales_Forecast, __ServiceSales_Forecast, 0)
			
			VAR __Customer_Satisfaction_PercentTarget = DIVIDE(__Customer_Satisfaction_Invoiced - __Customer_Satisfaction_Target, __Customer_Satisfaction_Target, 0)
			VAR __Customer_Satisfaction_PercentBudget = DIVIDE(__Customer_Satisfaction_Invoiced - __Customer_Satisfaction_Budget, __Customer_Satisfaction_Budget, 0)
			VAR __Customer_Satisfaction_PercentForecast = DIVIDE(__Customer_Satisfaction_Invoiced - __Customer_Satisfaction_Forecast, __Customer_Satisfaction_Forecast, 0)
			
			VAR __GrossProfitTotal_PercentTarget = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Target, __GrossProfitTotal_Target, 0)
			VAR __GrossProfitTotal_PercentBudget = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Budget, __GrossProfitTotal_Budget, 0)
			VAR __GrossProfitTotal_PercentForecast = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Forecast, __GrossProfitTotal_Forecast, 0)
			
			VAR __GrossProfitPercent_PercentTarget = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Target, __GrossProfitPercent_Target, 0)
			VAR __GrossProfitPercent_PercentBudget = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Budget, __GrossProfitPercent_Budget, 0)
			VAR __GrossProfitPercent_PercentForecast = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Forecast, __GrossProfitPercent_Forecast, 0)
			
			VAR __Gross_Margin_Cold_Rolled_PercentTarget = DIVIDE(__Gross_Margin_Cold_Rolled_Invoiced - __Gross_Margin_Cold_Rolled_Target, __Gross_Margin_Cold_Rolled_Target, 0)
			VAR __Gross_Margin_Cold_Rolled_PercentBudget = DIVIDE(__Gross_Margin_Cold_Rolled_Invoiced - __Gross_Margin_Cold_Rolled_Budget, __Gross_Margin_Cold_Rolled_Budget, 0)
			VAR __Gross_Margin_Cold_Rolled_PercentForecast = DIVIDE(__Gross_Margin_Cold_Rolled_Invoiced - __Gross_Margin_Cold_Rolled_Forecast, __Gross_Margin_Cold_Rolled_Forecast, 0)
			
			VAR __Customer_projects_PercentTarget = DIVIDE(__Customer_projects_Invoiced - __Customer_projects_Target, __Customer_projects_Target, 0)
			VAR __Customer_projects_PercentBudget = DIVIDE(__Customer_projects_Invoiced - __Customer_projects_Budget, __Customer_projects_Budget, 0)
			VAR __Customer_projects_PercentForecast = DIVIDE(__Customer_projects_Invoiced - __Customer_projects_Forecast, __Customer_projects_Forecast, 0)
			
			VAR __Coated_Sales_Volume_PercentTarget = DIVIDE(__Coated_Sales_Volume_Invoiced - __Coated_Sales_Volume_Target, __Coated_Sales_Volume_Target, 0)
			VAR __Coated_Sales_Volume_PercentBudget = DIVIDE(__Coated_Sales_Volume_Invoiced - __Coated_Sales_Volume_Budget, __Coated_Sales_Volume_Budget, 0)
			VAR __Coated_Sales_Volume_PercentForecast = DIVIDE(__Coated_Sales_Volume_Invoiced - __Coated_Sales_Volume_Forecast, __Coated_Sales_Volume_Forecast, 0)
			
			VAR __HeTSalesVolume_PercentTarget = DIVIDE(__HeTSalesVolume_Invoiced - __HeTSalesVolume_Target, __HeTSalesVolume_Target, 0)
			VAR __HeTSalesVolume_PercentBudget = DIVIDE(__HeTSalesVolume_Invoiced - __HeTSalesVolume_Budget, __HeTSalesVolume_Budget, 0)
			VAR __HeTSalesVolume_PercentForecast = DIVIDE(__HeTSalesVolume_Invoiced - __HeTSalesVolume_Forecast, __HeTSalesVolume_Forecast, 0)
			
			VAR __TotalMarketSales_PercentTarget = DIVIDE(__TotalMarketSales_Invoiced - __TotalMarketSales_Target, __TotalMarketSales_Target, 0)
			VAR __TotalMarketSales_PercentBudget = DIVIDE(__TotalMarketSales_Invoiced - __TotalMarketSales_Budget, __TotalMarketSales_Budget, 0)
			VAR __TotalMarketSales_PercentForecast = DIVIDE(__TotalMarketSales_Invoiced - __TotalMarketSales_Forecast, __TotalMarketSales_Forecast, 0)
			
			VAR __Revenue_PercentTarget = DIVIDE(__Revenue_Invoiced - __Revenue_Target, __Revenue_Target, 0)
			VAR __Revenue_PercentBudget = DIVIDE(__Revenue_Invoiced - __Revenue_Budget, __Revenue_Budget, 0)
			VAR __Revenue_PercentForecast = DIVIDE(__Revenue_Invoiced - __Revenue_Forecast, __Revenue_Forecast, 0)
			
			VAR __AveragePrice_PercentTarget = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Target, __AveragePrice_Target, 0)
			VAR __AveragePrice_PercentBudget = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Budget, __AveragePrice_Budget, 0)
			VAR __AveragePrice_PercentForecast = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Forecast, __AveragePrice_Forecast, 0)
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _atual = 
			SWITCH(_selecaoIdioma,
			        1,"Atual",
			        2,"Aktuell",
			        3,"Actual"
			)
			VAR _Target = 
			SWITCH(_selecaoIdioma,
			        1,"Meta",
			        2,"Ziel",
			        3,"Target"
			)
			VAR _Budget = 
			SWITCH(_selecaoIdioma,
			        1,"Orçamento",
			        "Budget"
			)
			VAR _Forecast = 
			SWITCH(_selecaoIdioma,
			        1,"Previsão",
			        "Forecast"
			)
			RETURN
			
			"
			<div style='display: flex; flex-wrap: wrap;'>
			    <!-- Linha 1 -->
			    <!-- Card 1 -->
			    <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Vendas no Mercado Local (t)",
			                        2,"Lokale Marktverkäufe (t)",
			                        3,"Local Market Sales (t)"
			                )
			            &"
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__LocalMarket_Invoiced) >= 1E9, FORMAT(__LocalMarket_Invoiced, "#,,,.0B"), 
			                    ABS(__LocalMarket_Invoiced) >= 1E6, FORMAT(__LocalMarket_Invoiced, "#,,.0M"), 
			                    ABS(__LocalMarket_Invoiced) >= 1E3, FORMAT(__LocalMarket_Invoiced, "#,.0K"), 
			                    FORMAT(__LocalMarket_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__LocalMarket_Target) >= 1E9, FORMAT(__LocalMarket_Target, "#,,,.0B"), 
			                    ABS(__LocalMarket_Target) >= 1E6, FORMAT(__LocalMarket_Target, "#,,.0M"), 
			                    ABS(__LocalMarket_Target) >= 1E3, FORMAT(__LocalMarket_Target, "#,.0K"), 
			                    FORMAT(__LocalMarket_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__LocalMarket_PercentTarget > 0, "#4C7596", IF(__LocalMarket_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__LocalMarket_PercentTarget > 0, "&#9650; ", IF(__LocalMarket_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__LocalMarket_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__LocalMarket_Budget) >= 1E9, FORMAT(__LocalMarket_Budget, "#,,,.0B"), 
			                    ABS(__LocalMarket_Budget) >= 1E6, FORMAT(__LocalMarket_Budget, "#,,.0M"), 
			                    ABS(__LocalMarket_Budget) >= 1E3, FORMAT(__LocalMarket_Budget, "#,.0K"), 
			                    FORMAT(__LocalMarket_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__LocalMarket_PercentBudget > 0, "#4C7596", IF(__LocalMarket_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__LocalMarket_PercentBudget > 0, "&#9650; ", IF(__LocalMarket_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__LocalMarket_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__LocalMarket_Forecast) >= 1E9, FORMAT(__LocalMarket_Forecast, "#,,,.0B"), 
			                    ABS(__LocalMarket_Forecast) >= 1E6, FORMAT(__LocalMarket_Forecast, "#,,.0M"), 
			                    ABS(__LocalMarket_Forecast) >= 1E3, FORMAT(__LocalMarket_Forecast, "#,.0K"), 
			                    FORMAT(__LocalMarket_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__LocalMarket_PercentForecast > 0, "#4C7596", IF(__LocalMarket_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__LocalMarket_PercentForecast > 0, "&#9650; ", IF(__LocalMarket_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__LocalMarket_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			
			
			    <!-- Card 2 -->
			    <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Laminado a Frio (vendas: local + exportação)",
			                        2,"Kaltgewalzt (Markt: lokal + Export)",
			                        3,"Cold Rolled (market Sales: Local + Export) (t) "
			                )
			                &"
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ColdRolled_Invoiced) >= 1E9, FORMAT(__ColdRolled_Invoiced, "#,,,.0B"), 
			                    ABS(__ColdRolled_Invoiced) >= 1E6, FORMAT(__ColdRolled_Invoiced, "#,,.0M"), 
			                    ABS(__ColdRolled_Invoiced) >= 1E3, FORMAT(__ColdRolled_Invoiced, "#,.0K"), 
			                    FORMAT(__ColdRolled_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ColdRolled_Target) >= 1E9, FORMAT(__ColdRolled_Target, "#,,,.0B"), 
			                    ABS(__ColdRolled_Target) >= 1E6, FORMAT(__ColdRolled_Target, "#,,.0M"), 
			                    ABS(__ColdRolled_Target) >= 1E3, FORMAT(__ColdRolled_Target, "#,.0K"), 
			                    FORMAT(__ColdRolled_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ColdRolled_PercentTarget > 0, "#4C7596", IF(__ColdRolled_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ColdRolled_PercentTarget > 0, "&#9650; ", IF(__ColdRolled_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ColdRolled_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ColdRolled_Budget) >= 1E9, FORMAT(__ColdRolled_Budget, "#,,,.0B"), 
			                    ABS(__ColdRolled_Budget) >= 1E6, FORMAT(__ColdRolled_Budget, "#,,.0M"), 
			                    ABS(__ColdRolled_Budget) >= 1E3, FORMAT(__ColdRolled_Budget, "#,.0K"), 
			                    FORMAT(__ColdRolled_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ColdRolled_PercentBudget > 0, "#4C7596", IF(__ColdRolled_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ColdRolled_PercentBudget > 0, "&#9650; ", IF(__ColdRolled_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ColdRolled_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ColdRolled_Forecast) >= 1E9, FORMAT(__ColdRolled_Forecast, "#,,,.0B"), 
			                    ABS(__ColdRolled_Forecast) >= 1E6, FORMAT(__ColdRolled_Forecast, "#,,.0M"), 
			                    ABS(__ColdRolled_Forecast) >= 1E3, FORMAT(__ColdRolled_Forecast, "#,.0K"), 
			                    FORMAT(__ColdRolled_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ColdRolled_PercentForecast > 0, "#4C7596", IF(__ColdRolled_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ColdRolled_PercentForecast > 0, "&#9650; ", IF(__ColdRolled_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ColdRolled_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			
			    <!-- Card 3 -->
			    <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Vendas para Exportação (t)",
			                        2,"Exportmarkt (t)",
			                        3,"Export Market Sales (t)"
			                )
			            &"
			            
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ExportMarket_Invoiced) >= 1E9, FORMAT(__ExportMarket_Invoiced, "#,,,.0B"), 
			                    ABS(__ExportMarket_Invoiced) >= 1E6, FORMAT(__ExportMarket_Invoiced, "#,,.0M"), 
			                    ABS(__ExportMarket_Invoiced) >= 1E3, FORMAT(__ExportMarket_Invoiced, "#,.0K"), 
			                    FORMAT(__ExportMarket_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ExportMarket_Target) >= 1E9, FORMAT(__ExportMarket_Target, "#,,,.0B"), 
			                    ABS(__ExportMarket_Target) >= 1E6, FORMAT(__ExportMarket_Target, "#,,.0M"), 
			                    ABS(__ExportMarket_Target) >= 1E3, FORMAT(__ExportMarket_Target, "#,.0K"), 
			                    FORMAT(__ExportMarket_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ExportMarket_PercentTarget > 0, "#4C7596", IF(__ExportMarket_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ExportMarket_PercentTarget > 0, "&#9650; ", IF(__ExportMarket_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ExportMarket_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ExportMarket_Budget) >= 1E9, FORMAT(__ExportMarket_Budget, "#,,,.0B"), 
			                    ABS(__ExportMarket_Budget) >= 1E6, FORMAT(__ExportMarket_Budget, "#,,.0M"), 
			                    ABS(__ExportMarket_Budget) >= 1E3, FORMAT(__ExportMarket_Budget, "#,.0K"), 
			                    FORMAT(__ExportMarket_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ExportMarket_PercentBudget > 0, "#4C7596", IF(__ExportMarket_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ExportMarket_PercentBudget > 0, "&#9650; ", IF(__ExportMarket_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ExportMarket_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__ExportMarket_Forecast) >= 1E9, FORMAT(__ExportMarket_Forecast, "#,,,.0B"), 
			                    ABS(__ExportMarket_Forecast) >= 1E6, FORMAT(__ExportMarket_Forecast, "#,,.0M"), 
			                    ABS(__ExportMarket_Forecast) >= 1E3, FORMAT(__ExportMarket_Forecast, "#,.0K"), 
			                    FORMAT(__ExportMarket_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ExportMarket_PercentForecast > 0, "#4C7596", IF(__ExportMarket_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ExportMarket_PercentForecast > 0, "&#9650; ", IF(__ExportMarket_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ExportMarket_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			
			    <!-- Card 4 -->
			    <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Vendas de Serviço (KBRL)",
			                        2,"Service (KBRL)",
			                        3,"Service Sales (KBRL)"
			                )
			            &"
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__ServiceSales_Invoiced) >= 1E9, FORMAT(__ServiceSales_Invoiced, "#,,,.0B"), 
			                    ABS(__ServiceSales_Invoiced) >= 1E6, FORMAT(__ServiceSales_Invoiced, "#,,.0M"), 
			                    ABS(__ServiceSales_Invoiced) >= 1E3, FORMAT(__ServiceSales_Invoiced, "#,.0K"), 
			                    FORMAT(__ServiceSales_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__ServiceSales_Target) >= 1E9, FORMAT(__ServiceSales_Target, "#,,,.0B"), 
			                    ABS(__ServiceSales_Target) >= 1E6, FORMAT(__ServiceSales_Target, "#,,.0M"), 
			                    ABS(__ServiceSales_Target) >= 1E3, FORMAT(__ServiceSales_Target, "#,.0K"), 
			                    FORMAT(__ServiceSales_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ServiceSales_PercentTarget > 0, "#4C7596", IF(__ServiceSales_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ServiceSales_PercentTarget > 0, "&#9650; ", IF(__ServiceSales_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ServiceSales_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__ServiceSales_Budget) >= 1E9, FORMAT(__ServiceSales_Budget, "#,,,.0B"), 
			                    ABS(__ServiceSales_Budget) >= 1E6, FORMAT(__ServiceSales_Budget, "#,,.0M"), 
			                    ABS(__ServiceSales_Budget) >= 1E3, FORMAT(__ServiceSales_Budget, "#,.0K"), 
			                    FORMAT(__ServiceSales_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ServiceSales_PercentBudget > 0, "#4C7596", IF(__ServiceSales_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ServiceSales_PercentBudget > 0, "&#9650; ", IF(__ServiceSales_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ServiceSales_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__ServiceSales_Forecast) >= 1E9, FORMAT(__ServiceSales_Forecast, "#,,,.0B"), 
			                    ABS(__ServiceSales_Forecast) >= 1E6, FORMAT(__ServiceSales_Forecast, "#,,.0M"), 
			                    ABS(__ServiceSales_Forecast) >= 1E3, FORMAT(__ServiceSales_Forecast, "#,.0K"), 
			                    FORMAT(__ServiceSales_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__ServiceSales_PercentForecast > 0, "#4C7596", IF(__ServiceSales_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__ServiceSales_PercentForecast > 0, "&#9650; ", IF(__ServiceSales_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__ServiceSales_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			    <!-- Card 5 -->
			    <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Insatisfação do Cliente (quantidade)",
			                        2,"Kundenunzufriedenheit (Menge)",
			                        3,"Customer Insatisfaction (quantity)"
			                )
			            &"
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & __Customer_Satisfaction_Invoiced & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & __Customer_Satisfaction_Target & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Customer_Satisfaction_PercentTarget > 0, "#4C7596", IF(__Customer_Satisfaction_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Customer_Satisfaction_PercentTarget > 0, "&#9650; ", IF(__Customer_Satisfaction_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Customer_Satisfaction_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" &__Customer_Satisfaction_Budget & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Customer_Satisfaction_PercentBudget > 0, "#4C7596", IF(__Customer_Satisfaction_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Customer_Satisfaction_PercentBudget > 0, "&#9650; ", IF(__Customer_Satisfaction_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Customer_Satisfaction_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & __Customer_Satisfaction_Forecast & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Customer_Satisfaction_PercentForecast > 0, "#4C7596", IF(__Customer_Satisfaction_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Customer_Satisfaction_PercentForecast > 0, "&#9650; ", IF(__Customer_Satisfaction_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Customer_Satisfaction_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			
			    <!-- Card 6 -->
			    <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Lucro Bruto Total (R$/t)",
			                        2,"Gesamte Bruttogewinn (R$/t)",
			                        3,"Gross Profit Total (R$/t)"
			                )
			            &"
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__GrossProfitTotal_Invoiced) >= 1E9, FORMAT(__GrossProfitTotal_Invoiced, "#,,,.0B"), 
			                    ABS(__GrossProfitTotal_Invoiced) >= 1E6, FORMAT(__GrossProfitTotal_Invoiced, "#,,.0M"), 
			                    ABS(__GrossProfitTotal_Invoiced) >= 1E3, FORMAT(__GrossProfitTotal_Invoiced, "#,.0K"), 
			                    FORMAT(__GrossProfitTotal_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__GrossProfitTotal_Target) >= 1E9, FORMAT(__GrossProfitTotal_Target, "#,,,.0B"), 
			                    ABS(__GrossProfitTotal_Target) >= 1E6, FORMAT(__GrossProfitTotal_Target, "#,,.0M"), 
			                    ABS(__GrossProfitTotal_Target) >= 1E3, FORMAT(__GrossProfitTotal_Target, "#,.0K"), 
			                    FORMAT(__GrossProfitTotal_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__GrossProfitTotal_PercentTarget > 0, "#4C7596", IF(__GrossProfitTotal_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__GrossProfitTotal_PercentTarget > 0, "&#9650; ", IF(__GrossProfitTotal_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__GrossProfitTotal_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__GrossProfitTotal_Budget) >= 1E9, FORMAT(__GrossProfitTotal_Budget, "#,,,.0B"), 
			                    ABS(__GrossProfitTotal_Budget) >= 1E6, FORMAT(__GrossProfitTotal_Budget, "#,,.0M"), 
			                    ABS(__GrossProfitTotal_Budget) >= 1E3, FORMAT(__GrossProfitTotal_Budget, "#,.0K"), 
			                    FORMAT(__GrossProfitTotal_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__GrossProfitTotal_PercentBudget > 0, "#4C7596", IF(__GrossProfitTotal_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__GrossProfitTotal_PercentBudget > 0, "&#9650; ", IF(__GrossProfitTotal_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__GrossProfitTotal_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__GrossProfitTotal_Forecast) >= 1E9, FORMAT(__GrossProfitTotal_Forecast, "#,,,.0B"), 
			                    ABS(__GrossProfitTotal_Forecast) >= 1E6, FORMAT(__GrossProfitTotal_Forecast, "#,,.0M"), 
			                    ABS(__GrossProfitTotal_Forecast) >= 1E3, FORMAT(__GrossProfitTotal_Forecast, "#,.0K"), 
			                    FORMAT(__GrossProfitTotal_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__GrossProfitTotal_PercentForecast > 0, "#4C7596", IF(__GrossProfitTotal_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__GrossProfitTotal_PercentForecast > 0, "&#9650; ", IF(__GrossProfitTotal_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__GrossProfitTotal_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			
			    <!-- Card 7 -->
			    <div style='height: 115px; width: 171px; border-radius: 10px; background-color: white;'>
			        <!-- Título do Card -->
			        <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Lucro Bruto Total (%)",
			                        2,"Gesamte Bruttogewinn (%)",
			                        3,"Gross Profit Total (%)"
			                )
			            &"
			        </div>
			        <!-- Conteúdo do Card -->
			        <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			            <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & 
			                    FORMAT(__GrossProfitPercent_Invoiced, "#0.00%") & " 
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & 
			                    FORMAT(__GrossProfitPercent_Target, "#0.00%") & " 
			                <span style='font-size: 8px; color: 
			                    " & IF(__GrossProfitPercent_PercentTarget > 0, "#4C7596", IF(__GrossProfitPercent_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__GrossProfitPercent_PercentTarget > 0, "&#9650; ", IF(__GrossProfitPercent_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__GrossProfitPercent_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & 
			                    FORMAT(__GrossProfitPercent_Budget, "#0.00%") & " 
			                <span style='font-size: 8px; color: 
			                    " & IF(__GrossProfitPercent_PercentBudget > 0, "#4C7596", IF(__GrossProfitPercent_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__GrossProfitPercent_PercentBudget > 0, "&#9650; ", IF(__GrossProfitPercent_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__GrossProfitPercent_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & 
			                    FORMAT(__GrossProfitPercent_Forecast, "#0.00%") & " 
			                <span style='font-size: 8px; color: 
			                    " & IF(__GrossProfitPercent_PercentForecast > 0, "#4C7596", IF(__GrossProfitPercent_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__GrossProfitPercent_PercentForecast > 0, "&#9650; ", IF(__GrossProfitPercent_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__GrossProfitPercent_PercentForecast), "0.00%") & ")
			                </span>
			            </span>
			        </div>
			    </div>
			
			
			    <!-- Linha 2 -->
			    <div style='display: flex; margin-top: 10px;'>
			        <!-- Card 1 -->
			            <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Lucro Bruto - Laminado a Frio (R$/t)",
			                        2,"Bruttogewinn - Kaltgewalzt (R$/t)",
			                        3,"Gross Profit - Cold Rolled (R$/t)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Gross_Margin_Cold_Rolled_Invoiced) >= 1E9, FORMAT(__Gross_Margin_Cold_Rolled_Invoiced, "#,,,.0B"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Invoiced) >= 1E6, FORMAT(__Gross_Margin_Cold_Rolled_Invoiced, "#,,.0M"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Invoiced) >= 1E3, FORMAT(__Gross_Margin_Cold_Rolled_Invoiced, "#,.0K"), 
			                    FORMAT(__Gross_Margin_Cold_Rolled_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Gross_Margin_Cold_Rolled_Target) >= 1E9, FORMAT(__Gross_Margin_Cold_Rolled_Target, "#,,,.0B"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Target) >= 1E6, FORMAT(__Gross_Margin_Cold_Rolled_Target, "#,,.0M"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Target) >= 1E3, FORMAT(__Gross_Margin_Cold_Rolled_Target, "#,.0K"), 
			                    FORMAT(__Gross_Margin_Cold_Rolled_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Gross_Margin_Cold_Rolled_PercentTarget > 0, "#4C7596", IF(__Gross_Margin_Cold_Rolled_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Gross_Margin_Cold_Rolled_PercentTarget > 0, "&#9650; ", IF(__Gross_Margin_Cold_Rolled_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Gross_Margin_Cold_Rolled_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Gross_Margin_Cold_Rolled_Budget) >= 1E9, FORMAT(__Gross_Margin_Cold_Rolled_Budget, "#,,,.0B"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Budget) >= 1E6, FORMAT(__Gross_Margin_Cold_Rolled_Budget, "#,,.0M"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Budget) >= 1E3, FORMAT(__Gross_Margin_Cold_Rolled_Budget, "#,.0K"), 
			                    FORMAT(__Gross_Margin_Cold_Rolled_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Gross_Margin_Cold_Rolled_PercentBudget > 0, "#4C7596", IF(__Gross_Margin_Cold_Rolled_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Gross_Margin_Cold_Rolled_PercentBudget > 0, "&#9650; ", IF(__Gross_Margin_Cold_Rolled_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Gross_Margin_Cold_Rolled_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Gross_Margin_Cold_Rolled_Forecast) >= 1E9, FORMAT(__Gross_Margin_Cold_Rolled_Forecast, "#,,,.0B"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Forecast) >= 1E6, FORMAT(__Gross_Margin_Cold_Rolled_Forecast, "#,,.0M"), 
			                    ABS(__Gross_Margin_Cold_Rolled_Forecast) >= 1E3, FORMAT(__Gross_Margin_Cold_Rolled_Forecast, "#,.0K"), 
			                    FORMAT(__Gross_Margin_Cold_Rolled_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Gross_Margin_Cold_Rolled_PercentForecast > 0, "#4C7596", IF(__Gross_Margin_Cold_Rolled_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Gross_Margin_Cold_Rolled_PercentForecast > 0, "&#9650; ", IF(__Gross_Margin_Cold_Rolled_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Gross_Margin_Cold_Rolled_PercentForecast), "0.00%") & ")
			                </span>                    </span>
			                </div>
			            </div>
			
			
			            <!-- Card 2 -->
			            <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Customer Projects (t)",
			                        2,"Kundenprojekte (t)",
			                        3,"Customer Projects (t)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Customer_projects_Invoiced) >= 1E9, FORMAT(__Customer_projects_Invoiced, "#,,,.0B"), 
			                    ABS(__Customer_projects_Invoiced) >= 1E6, FORMAT(__Customer_projects_Invoiced, "#,,.0M"), 
			                    ABS(__Customer_projects_Invoiced) >= 1E3, FORMAT(__Customer_projects_Invoiced, "#,.0K"), 
			                    FORMAT(__Customer_projects_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Customer_projects_Target) >= 1E9, FORMAT(__Customer_projects_Target, "#,,,.0B"), 
			                    ABS(__Customer_projects_Target) >= 1E6, FORMAT(__Customer_projects_Target, "#,,.0M"), 
			                    ABS(__Customer_projects_Target) >= 1E3, FORMAT(__Customer_projects_Target, "#,.0K"), 
			                    FORMAT(__Customer_projects_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Customer_projects_PercentTarget > 0, "#4C7596", IF(__Customer_projects_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Customer_projects_PercentTarget > 0, "&#9650; ", IF(__Customer_projects_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Customer_projects_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Customer_projects_Budget) >= 1E9, FORMAT(__Customer_projects_Budget, "#,,,.0B"), 
			                    ABS(__Customer_projects_Budget) >= 1E6, FORMAT(__Customer_projects_Budget, "#,,.0M"), 
			                    ABS(__Customer_projects_Budget) >= 1E3, FORMAT(__Customer_projects_Budget, "#,.0K"), 
			                    FORMAT(__Customer_projects_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Customer_projects_PercentBudget > 0, "#4C7596", IF(__Customer_projects_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Customer_projects_PercentBudget > 0, "&#9650; ", IF(__Customer_projects_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Customer_projects_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Customer_projects_Forecast) >= 1E9, FORMAT(__Customer_projects_Forecast, "#,,,.0B"), 
			                    ABS(__Customer_projects_Forecast) >= 1E6, FORMAT(__Customer_projects_Forecast, "#,,.0M"), 
			                    ABS(__Customer_projects_Forecast) >= 1E3, FORMAT(__Customer_projects_Forecast, "#,.0K"), 
			                    FORMAT(__Customer_projects_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Customer_projects_PercentForecast > 0, "#4C7596", IF(__Customer_projects_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Customer_projects_PercentForecast > 0, "&#9650; ", IF(__Customer_projects_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Customer_projects_PercentForecast), "0.00%") & ")
			                </span>                    </span>
			                </div>
			            </div>
			
			            <!-- Card 3 -->
			            <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    
			                     "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Volumes de Vendas Revestidos (t)",
			                        2,"Coated Verkaufsvolumen (t)",
			                        3,"Coated Sales Volumes (t)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Coated_Sales_Volume_Invoiced) >= 1E9, FORMAT(__Coated_Sales_Volume_Invoiced, "#,,,.0B"), 
			                    ABS(__Coated_Sales_Volume_Invoiced) >= 1E6, FORMAT(__Coated_Sales_Volume_Invoiced, "#,,.0M"), 
			                    ABS(__Coated_Sales_Volume_Invoiced) >= 1E3, FORMAT(__Coated_Sales_Volume_Invoiced, "#,.0K"), 
			                    FORMAT(__Coated_Sales_Volume_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Coated_Sales_Volume_Target) >= 1E9, FORMAT(__Coated_Sales_Volume_Target, "#,,,.0B"), 
			                    ABS(__Coated_Sales_Volume_Target) >= 1E6, FORMAT(__Coated_Sales_Volume_Target, "#,,.0M"), 
			                    ABS(__Coated_Sales_Volume_Target) >= 1E3, FORMAT(__Coated_Sales_Volume_Target, "#,.0K"), 
			                    FORMAT(__Coated_Sales_Volume_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Coated_Sales_Volume_PercentTarget > 0, "#4C7596", IF(__Coated_Sales_Volume_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Coated_Sales_Volume_PercentTarget > 0, "&#9650; ", IF(__Coated_Sales_Volume_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Coated_Sales_Volume_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Coated_Sales_Volume_Budget) >= 1E9, FORMAT(__Coated_Sales_Volume_Budget, "#,,,.0B"), 
			                    ABS(__Coated_Sales_Volume_Budget) >= 1E6, FORMAT(__Coated_Sales_Volume_Budget, "#,,.0M"), 
			                    ABS(__Coated_Sales_Volume_Budget) >= 1E3, FORMAT(__Coated_Sales_Volume_Budget, "#,.0K"), 
			                    FORMAT(__Coated_Sales_Volume_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Coated_Sales_Volume_PercentBudget > 0, "#4C7596", IF(__Coated_Sales_Volume_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Coated_Sales_Volume_PercentBudget > 0, "&#9650; ", IF(__Coated_Sales_Volume_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Coated_Sales_Volume_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__Coated_Sales_Volume_Forecast) >= 1E9, FORMAT(__Coated_Sales_Volume_Forecast, "#,,,.0B"), 
			                    ABS(__Coated_Sales_Volume_Forecast) >= 1E6, FORMAT(__Coated_Sales_Volume_Forecast, "#,,.0M"), 
			                    ABS(__Coated_Sales_Volume_Forecast) >= 1E3, FORMAT(__Coated_Sales_Volume_Forecast, "#,.0K"), 
			                    FORMAT(__Coated_Sales_Volume_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Coated_Sales_Volume_PercentForecast > 0, "#4C7596", IF(__Coated_Sales_Volume_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Coated_Sales_Volume_PercentForecast > 0, "&#9650; ", IF(__Coated_Sales_Volume_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Coated_Sales_Volume_PercentForecast), "0.00%") & ")
			                </span>                    </span>
			                </div>
			            </div>
			
			            <!-- Card 4 -->
			            <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Volumes de Vendas H&T (t)",
			                        2,"H&T Verkaufsvolumen (t)",
			                        3,"H&T Sales Volumes (t)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__HeTSalesVolume_Invoiced) >= 1E9, FORMAT(__HeTSalesVolume_Invoiced, "#,,,.0B"), 
			                    ABS(__HeTSalesVolume_Invoiced) >= 1E6, FORMAT(__HeTSalesVolume_Invoiced, "#,,.0M"), 
			                    ABS(__HeTSalesVolume_Invoiced) >= 1E3, FORMAT(__HeTSalesVolume_Invoiced, "#,.0K"), 
			                    FORMAT(__HeTSalesVolume_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__HeTSalesVolume_Target) >= 1E9, FORMAT(__HeTSalesVolume_Target, "#,,,.0B"), 
			                    ABS(__HeTSalesVolume_Target) >= 1E6, FORMAT(__HeTSalesVolume_Target, "#,,.0M"), 
			                    ABS(__HeTSalesVolume_Target) >= 1E3, FORMAT(__HeTSalesVolume_Target, "#,.0K"), 
			                    FORMAT(__HeTSalesVolume_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__HeTSalesVolume_PercentTarget > 0, "#4C7596", IF(__HeTSalesVolume_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__HeTSalesVolume_PercentTarget > 0, "&#9650; ", IF(__HeTSalesVolume_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__HeTSalesVolume_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__HeTSalesVolume_Budget) >= 1E9, FORMAT(__HeTSalesVolume_Budget, "#,,,.0B"), 
			                    ABS(__HeTSalesVolume_Budget) >= 1E6, FORMAT(__HeTSalesVolume_Budget, "#,,.0M"), 
			                    ABS(__HeTSalesVolume_Budget) >= 1E3, FORMAT(__HeTSalesVolume_Budget, "#,.0K"), 
			                    FORMAT(__HeTSalesVolume_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__HeTSalesVolume_PercentBudget > 0, "#4C7596", IF(__HeTSalesVolume_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__HeTSalesVolume_PercentBudget > 0, "&#9650; ", IF(__HeTSalesVolume_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__HeTSalesVolume_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__HeTSalesVolume_Forecast) >= 1E9, FORMAT(__HeTSalesVolume_Forecast, "#,,,.0B"), 
			                    ABS(__HeTSalesVolume_Forecast) >= 1E6, FORMAT(__HeTSalesVolume_Forecast, "#,,.0M"), 
			                    ABS(__HeTSalesVolume_Forecast) >= 1E3, FORMAT(__HeTSalesVolume_Forecast, "#,.0K"), 
			                    FORMAT(__HeTSalesVolume_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__HeTSalesVolume_PercentForecast > 0, "#4C7596", IF(__HeTSalesVolume_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__HeTSalesVolume_PercentForecast > 0, "&#9650; ", IF(__HeTSalesVolume_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__HeTSalesVolume_PercentForecast), "0.00%") & ")
			                </span>                    </span>
			                </div>
			            </div>
			            <!-- Card 5 -->
			            <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Total de Vendas no Mercado (t)",
			                        2,"Gesamte Marktverkäufe (t)",
			                        3,"Total Market Sales (t)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__TotalMarketSales_Invoiced) >= 1E9, FORMAT(__TotalMarketSales_Invoiced, "#,,,.0B"), 
			                    ABS(__TotalMarketSales_Invoiced) >= 1E6, FORMAT(__TotalMarketSales_Invoiced, "#,,.0M"), 
			                    ABS(__TotalMarketSales_Invoiced) >= 1E3, FORMAT(__TotalMarketSales_Invoiced, "#,.0K"), 
			                    FORMAT(__TotalMarketSales_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__TotalMarketSales_Target) >= 1E9, FORMAT(__TotalMarketSales_Target, "#,,,.0B"), 
			                    ABS(__TotalMarketSales_Target) >= 1E6, FORMAT(__TotalMarketSales_Target, "#,,.0M"), 
			                    ABS(__TotalMarketSales_Target) >= 1E3, FORMAT(__TotalMarketSales_Target, "#,.0K"), 
			                    FORMAT(__TotalMarketSales_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__TotalMarketSales_PercentTarget > 0, "#4C7596", IF(__TotalMarketSales_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__TotalMarketSales_PercentTarget > 0, "&#9650; ", IF(__TotalMarketSales_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__TotalMarketSales_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__TotalMarketSales_Budget) >= 1E9, FORMAT(__TotalMarketSales_Budget, "#,,,.0B"), 
			                    ABS(__TotalMarketSales_Budget) >= 1E6, FORMAT(__TotalMarketSales_Budget, "#,,.0M"), 
			                    ABS(__TotalMarketSales_Budget) >= 1E3, FORMAT(__TotalMarketSales_Budget, "#,.0K"), 
			                    FORMAT(__TotalMarketSales_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__TotalMarketSales_PercentBudget > 0, "#4C7596", IF(__TotalMarketSales_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__TotalMarketSales_PercentBudget > 0, "&#9650; ", IF(__TotalMarketSales_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__TotalMarketSales_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong>" & SWITCH(TRUE(), 
			                    ABS(__TotalMarketSales_Forecast) >= 1E9, FORMAT(__TotalMarketSales_Forecast, "#,,,.0B"), 
			                    ABS(__TotalMarketSales_Forecast) >= 1E6, FORMAT(__TotalMarketSales_Forecast, "#,,.0M"), 
			                    ABS(__TotalMarketSales_Forecast) >= 1E3, FORMAT(__TotalMarketSales_Forecast, "#,.0K"), 
			                    FORMAT(__TotalMarketSales_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__TotalMarketSales_PercentForecast > 0, "#4C7596", IF(__TotalMarketSales_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__TotalMarketSales_PercentForecast > 0, "&#9650; ", IF(__TotalMarketSales_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__TotalMarketSales_PercentForecast), "0.00%") & ")
			                </span>
			                    </span>
			                </div>
			            </div>
			
			            <!-- Card 6 -->
			            <div style='height: 115px; width: 171px;margin-right: 10px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Faturamento (R$)",
			                        3,"Revenue (R$)",
			                        2,"Umsatz (R$)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Revenue_Invoiced) >= 1E9, FORMAT(__Revenue_Invoiced, "#,,,.0B"), 
			                    ABS(__Revenue_Invoiced) >= 1E6, FORMAT(__Revenue_Invoiced, "#,,.0M"), 
			                    ABS(__Revenue_Invoiced) >= 1E3, FORMAT(__Revenue_Invoiced, "#,.0K"), 
			                    FORMAT(__Revenue_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Revenue_Target) >= 1E9, FORMAT(__Revenue_Target, "#,,,.0B"), 
			                    ABS(__Revenue_Target) >= 1E6, FORMAT(__Revenue_Target, "#,,.0M"), 
			                    ABS(__Revenue_Target) >= 1E3, FORMAT(__Revenue_Target, "#,.0K"), 
			                    FORMAT(__Revenue_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Revenue_PercentTarget > 0, "#4C7596", IF(__Revenue_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Revenue_PercentTarget > 0, "&#9650; ", IF(__Revenue_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Revenue_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Revenue_Budget) >= 1E9, FORMAT(__Revenue_Budget, "#,,,.0B"), 
			                    ABS(__Revenue_Budget) >= 1E6, FORMAT(__Revenue_Budget, "#,,.0M"), 
			                    ABS(__Revenue_Budget) >= 1E3, FORMAT(__Revenue_Budget, "#,.0K"), 
			                    FORMAT(__Revenue_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Revenue_PercentBudget > 0, "#4C7596", IF(__Revenue_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Revenue_PercentBudget > 0, "&#9650; ", IF(__Revenue_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Revenue_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__Revenue_Forecast) >= 1E9, FORMAT(__Revenue_Forecast, "#,,,.0B"), 
			                    ABS(__Revenue_Forecast) >= 1E6, FORMAT(__Revenue_Forecast, "#,,.0M"), 
			                    ABS(__Revenue_Forecast) >= 1E3, FORMAT(__Revenue_Forecast, "#,.0K"), 
			                    FORMAT(__Revenue_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__Revenue_PercentForecast > 0, "#4C7596", IF(__Revenue_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__Revenue_PercentForecast > 0, "&#9650; ", IF(__Revenue_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__Revenue_PercentForecast), "0.00%") & ")
			                    </span>
			                </div>
			            </div>
			
			            <!-- Card 7 -->
			            <div style='height: 115px; width: 171px; border-radius: 10px; background-color: white;'>
			                <!-- Título do Card -->
			                <div style='background: linear-gradient(to bottom, #4C7596, #4C7596); height: 40px; color: white; font-weight: bold; text-align: left; padding: 6px; display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Preço Médio (R$/kg)",
			                        3,"Avarage Price (R$/kg)",
			                        2,"Durchschnittspreis (R$/kg)"
			                )
			            &"
			                </div>
			                <!-- Conteúdo do Card -->
			                <div style='padding-left: 4px; height: 75px; width: 156px; display: flex; flex-direction: column; justify-content: center;'>
			                    <!-- Invoiced -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_atual&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__AveragePrice_Invoiced) >= 1E9, FORMAT(__AveragePrice_Invoiced, "#,,,.0B"), 
			                    ABS(__AveragePrice_Invoiced) >= 1E6, FORMAT(__AveragePrice_Invoiced, "#,,.0M"), 
			                    ABS(__AveragePrice_Invoiced) >= 1E3, FORMAT(__AveragePrice_Invoiced, "#,.0K"), 
			                    FORMAT(__AveragePrice_Invoiced, "#0.00")) & "
			            </span>
			            <!-- Target -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Target&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__AveragePrice_Target) >= 1E9, FORMAT(__AveragePrice_Target, "#,,,.0B"), 
			                    ABS(__AveragePrice_Target) >= 1E6, FORMAT(__AveragePrice_Target, "#,,.0M"), 
			                    ABS(__AveragePrice_Target) >= 1E3, FORMAT(__AveragePrice_Target, "#,.0K"), 
			                    FORMAT(__AveragePrice_Target, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__AveragePrice_PercentTarget > 0, "#4C7596", IF(__AveragePrice_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__AveragePrice_PercentTarget > 0, "&#9650; ", IF(__AveragePrice_PercentTarget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__AveragePrice_PercentTarget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Budget -->
			            <span style='font-size: 10px; color: black; margin-bottom: 2px;'>
			                <strong>"&_Budget&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__AveragePrice_Budget) >= 1E9, FORMAT(__AveragePrice_Budget, "#,,,.0B"), 
			                    ABS(__AveragePrice_Budget) >= 1E6, FORMAT(__AveragePrice_Budget, "#,,.0M"), 
			                    ABS(__AveragePrice_Budget) >= 1E3, FORMAT(__AveragePrice_Budget, "#,.0K"), 
			                    FORMAT(__AveragePrice_Budget, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__AveragePrice_PercentBudget > 0, "#4C7596", IF(__AveragePrice_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__AveragePrice_PercentBudget > 0, "&#9650; ", IF(__AveragePrice_PercentBudget < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__AveragePrice_PercentBudget), "0.00%") & ")
			                </span>
			            </span>
			            <!-- Forecast -->
			            <span style='font-size: 10px; color: black;'>
			                <strong>"&_Forecast&": </strong> R$ " & SWITCH(TRUE(), 
			                    ABS(__AveragePrice_Forecast) >= 1E9, FORMAT(__AveragePrice_Forecast, "#,,,.0B"), 
			                    ABS(__AveragePrice_Forecast) >= 1E6, FORMAT(__AveragePrice_Forecast, "#,,.0M"), 
			                    ABS(__AveragePrice_Forecast) >= 1E3, FORMAT(__AveragePrice_Forecast, "#,.0K"), 
			                    FORMAT(__AveragePrice_Forecast, "#0.00")) & "
			                <span style='font-size: 8px; color: 
			                    " & IF(__AveragePrice_PercentForecast > 0, "#4C7596", IF(__AveragePrice_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                    (" & IF(__AveragePrice_PercentForecast > 0, "&#9650; ", IF(__AveragePrice_PercentForecast < 0, "&#9660; ", "")) & 
			                    FORMAT(ABS(__AveragePrice_PercentForecast), "0.00%") & ")
			                </span>
			                    </span>
			                </div>
			            </div>
			    </div>
			</div>
			
			
			"
			
			
			```
		isHidden
		displayFolder: HTML
		lineageTag: 07876d75-686f-4344-8e01-8eea9e68b9a7

	measure 'HTML - Cards Overview' = ```
			
			VAR _selecaoFormato = SELECTEDVALUE(pFormato[sFormato Pedido])
			
			-- Cálculos
			VAR __GrossProfitTotal_Invoiced = [Gross Profit Total (R$/t)]
			VAR __GrossProfitTotal_Target = [Gross Profit Total (R$/t)_Target] 
			VAR __GrossProfitTotal_Budget = [Gross Profit Total (R$/t)_budget] 
			VAR __GrossProfitTotal_Forecast = [Gross Profit Total (R$/t)_forecast] 
			VAR __GrossProfitTotal_Invoiced_abs = ABS([Gross Profit Total (R$/t)])
			
			VAR __GrossProfitPercent_Invoiced = [Gross Profit (%)] 
			VAR __GrossProfitPercent_Target = [GrossProfit_target (%)]  
			VAR __GrossProfitPercent_Budget = [GrossProfit_budget (%)] 
			VAR __GrossProfitPercent_Forecast = [GrossProfit_forecast (%)] 
			VAR __GrossProfitPercent_Invoiced_abs = ABS([Gross Profit (%)] )
			
			VAR __Revenue_Invoiced = [Faturamento] 
			VAR __Revenue_Target = [Faturamento_target]  
			VAR __Revenue_Budget = [Faturamento_budget]  
			VAR __Revenue_Forecast = [Faturamento_forecast]  
			VAR __Revenue_Invoiced_abs = ABS([Faturamento] )
			
			VAR __AveragePrice_Invoiced = [Preco Medio]
			VAR __AveragePrice_Target = [Preco Medio_target] 
			VAR __AveragePrice_Budget = [Preco Medio_budget] 
			VAR __AveragePrice_Forecast = [Preco Medio_forecast]
			VAR __AveragePrice_Invoiced_abs = ABS([Preco Medio])
			
			VAR __Peso_Invoiced = [PesoFaturado]
			VAR __Peso_Target = [Target Peso] 
			VAR __Peso_Budget = [Budget Peso] 
			VAR __Peso_Forecast = [Forecast Peso]
			VAR __Peso_Invoiced_abs = ABS([PesoFaturado])
			
			-- Variáveis Percentuais
			VAR __GrossProfitTotal_PercentTarget = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Target, __GrossProfitTotal_Target, 0)
			VAR __GrossProfitTotal_PercentBudget = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Budget, __GrossProfitTotal_Budget, 0)
			VAR __GrossProfitTotal_PercentForecast = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Forecast, __GrossProfitTotal_Forecast, 0)
			
			VAR __GrossProfitPercent_PercentTarget = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Target, __GrossProfitPercent_Target, 0)
			VAR __GrossProfitPercent_PercentBudget = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Budget, __GrossProfitPercent_Budget, 0)
			VAR __GrossProfitPercent_PercentForecast = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Forecast, __GrossProfitPercent_Forecast, 0)
			
			VAR __Revenue_PercentTarget = DIVIDE(__Revenue_Invoiced - __Revenue_Target, __Revenue_Target, 0)
			VAR __Revenue_PercentBudget = DIVIDE(__Revenue_Invoiced - __Revenue_Budget, __Revenue_Budget, 0)
			VAR __Revenue_PercentForecast = DIVIDE(__Revenue_Invoiced - __Revenue_Forecast, __Revenue_Forecast, 0)
			
			VAR __AveragePrice_PercentTarget = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Target, __AveragePrice_Target, 0)
			VAR __AveragePrice_PercentBudget = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Budget, __AveragePrice_Budget, 0)
			VAR __AveragePrice_PercentForecast = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Forecast, __AveragePrice_Forecast, 0)
			
			VAR __Peso_PercentTarget = DIVIDE(__Peso_Invoiced - __Peso_Target, __Peso_Target, 0)
			VAR __Peso_PercentBudget = DIVIDE(__Peso_Invoiced - __Peso_Budget, __Peso_Budget, 0)
			VAR __Peso_PercentForecast = DIVIDE(__Peso_Invoiced - __Peso_Forecast, __Peso_Forecast, 0)
			
			-- Realizados (formatados)
			
			VAR __AveragePrice_Invoiced_formated = 
			FORMAT(__AveragePrice_Invoiced,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0.000",
			        1,SWITCH(
			                TRUE(),
			                __AveragePrice_Invoiced_abs >= 1E9, "#,,,.00B",
			                __AveragePrice_Invoiced_abs >= 1E6, "#,,.00M",
			                __AveragePrice_Invoiced_abs >= 1E3, "#,.00K",
			                "#,,,0.000"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			
			VAR __Peso_Invoiced_formated = 
			FORMAT(__Peso_Invoiced,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0",
			        1,SWITCH(
			                TRUE(),
			                __Peso_Invoiced_abs >= 1E9, "#,,,.00B",
			                __Peso_Invoiced_abs >= 1E6, "#,,.00M",
			                __Peso_Invoiced_abs >= 1E3, "#,.00K",
			                "#,,,0"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			
			VAR __Revenue_Invoiced_formated = 
			FORMAT(__Revenue_Invoiced,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0",
			        1,SWITCH(
			                TRUE(),
			                __Revenue_Invoiced_abs >= 1E9, "#,,,.00B",
			                __Revenue_Invoiced_abs >= 1E6, "#,,.00M",
			                __Revenue_Invoiced_abs >= 1E3, "#,.00K",
			                "#,,,0"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			
			VAR __GrossProfitTotal_Invoiced_formated = 
			FORMAT(__GrossProfitTotal_Invoiced,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0",
			        1,SWITCH(
			                TRUE(),
			                __GrossProfitTotal_Invoiced_abs >= 1E9, "#,,,.00B",
			                __GrossProfitTotal_Invoiced_abs >= 1E6, "#,,.00M",
			                __GrossProfitTotal_Invoiced_abs >= 1E3, "#,.00K",
			                "#,,,0"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			-- Parte de idioma
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _atual = 
			SWITCH(_selecaoIdioma,
			        1,"Atual",
			        2,"Aktuell",
			        3,"Actual"
			)
			VAR _Target = 
			SWITCH(_selecaoIdioma,
			        1,"Meta",
			        2,"Ziel",
			        3,"Target"
			)
			VAR _Budget = 
			SWITCH(_selecaoIdioma,
			        1,"Orçamento",
			        "Budget"
			)
			VAR _Forecast = 
			SWITCH(_selecaoIdioma,
			        1,"Previsão",
			        "Forecast"
			)
			RETURN
			
			"
			<div style='display: flex; flex-wrap: wrap;'>
			    <!-- Linha 1 -->
			    <div style='display: flex; margin-bottom: 12px'>
			        
			        <!-- Card 1 -->
			        <div style='height: 92px; width: 232px; border-radius: 10px; background-color: white;'>
			            <!-- Título do Card -->
			            <div style=' height: 10px; margin-top: 5px; margin-left: 4px; color: black; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Preço Médio (R$/kg)",
			                        3,"Avarage Price (R$/kg)",
			                        2,"Durchschnittspreis (R$/kg)"
			                )
			            &"
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 4px; padding-top: 4px; height: 75px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Invoiced -->
			                <span style='font-size: 12px; color: black; margin-bottom: 2px;'>
			                    <strong>R$ " & __AveragePrice_Invoiced_formated & "
			                    </strong> 
			                </span>
			                <!-- Target -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__AveragePrice_PercentTarget > 0, "#4C7596", IF(__AveragePrice_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__AveragePrice_PercentTarget > 0, "&#9650; ", IF(__AveragePrice_PercentTarget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__AveragePrice_PercentTarget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                         vs "&_Target&"
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__AveragePrice_PercentBudget > 0, "#4C7596", IF(__AveragePrice_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__AveragePrice_PercentBudget > 0, "&#9650; ", IF(__AveragePrice_PercentBudget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__AveragePrice_PercentBudget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Budget&"
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__AveragePrice_PercentForecast > 0, "#4C7596", IF(__AveragePrice_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__AveragePrice_PercentForecast > 0, "&#9650; ", IF(__AveragePrice_PercentForecast < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__AveragePrice_PercentForecast), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Forecast&"
			                    </span>
			                </span>
			            </div>
			        </div>
			    </div>
			
			    <!-- Linha 2 -->
			    <div style='display: flex; margin-bottom: 12px'>
			        
			        <!-- Card 1 -->
			        <div style='height: 92px; width: 110px; margin-right:12px; border-radius: 10px; background-color: white;'>
			            <!-- Título do Card -->
			            <div style=' height: 10px; margin-top: 5px; margin-left: 4px; color: black; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Peso (t)",
			                        3,"Weight (t)",
			                        2,"Gewicht (t)"
			                )
			            &"
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 4px; padding-top: 4px; height: 75px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Invoiced -->
			                <span style='font-size: 12px; color: black; margin-bottom: 2px;'>
			                    <strong> " & __Peso_Invoiced_formated & "
			                    </strong> 
			                </span>
			                <!-- Target -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__Peso_PercentTarget > 0, "#4C7596", IF(__Peso_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__Peso_PercentTarget > 0, "&#9650; ", IF(__Peso_PercentTarget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__Peso_PercentTarget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                         vs "&_Target&"
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__Peso_PercentBudget > 0, "#4C7596", IF(__Peso_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__Peso_PercentBudget > 0, "&#9650; ", IF(__Peso_PercentBudget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__Peso_PercentBudget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Budget&"
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__Peso_PercentForecast > 0, "#4C7596", IF(__Peso_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__Peso_PercentForecast > 0, "&#9650; ", IF(__Peso_PercentForecast < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__Peso_PercentForecast), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Forecast&"
			                    </span>
			                </span>
			            </div>
			        </div>
			
			        <!-- Card 2 -->
			        <div style='height: 92px; width: 110px; border-radius: 10px; background-color: white;'>
			            <!-- Título do Card -->
			            <div style=' height: 10px; margin-top: 5px; margin-left: 4px; color: black; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Faturamento (R$)",
			                        3,"Revenue (R$)",
			                        2,"Umsatz (R$)"
			                )
			            &"
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 4px; padding-top: 4px; height: 75px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Invoiced -->
			                <span style='font-size: 12px; color: black; margin-bottom: 2px;'>
			                    <strong>R$ " & __Revenue_Invoiced_formated & "
			                    </strong> 
			                </span>
			                <!-- Target -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__Revenue_PercentTarget > 0, "#4C7596", IF(__Revenue_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__Revenue_PercentTarget > 0, "&#9650; ", IF(__Revenue_PercentTarget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__Revenue_PercentTarget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                         vs "&_Target&"
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__Revenue_PercentBudget > 0, "#4C7596", IF(__Revenue_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__Revenue_PercentBudget > 0, "&#9650; ", IF(__Revenue_PercentBudget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__Revenue_PercentBudget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Budget&"
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__Revenue_PercentForecast > 0, "#4C7596", IF(__Revenue_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__Revenue_PercentForecast > 0, "&#9650; ", IF(__Revenue_PercentForecast < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__Revenue_PercentForecast), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Forecast&"
			                    </span>
			                </span>
			            </div>
			        </div>
			    </div>
			
			    <!-- Linha 3 -->
			    <div style='display: flex;'>
			        
			        <!-- Card 1 -->
			        <div style='height: 92px; width: 110px; margin-right:12px; border-radius: 10px; background-color: white;'>
			            <!-- Título do Card -->
			            <div style=' height: 10px; margin-top: 5px; margin-left: 4px; color: black; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			            "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Lucro Bruto (R$/t)",
			                        3,"Gross Profit (R$/t)",
			                        2,"Bruttogewinn (R$/t)"
			                )
			            &"
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 4px; padding-top: 4px; height: 75px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Invoiced -->
			                <span style='font-size: 12px; color: black; margin-bottom: 2px;'>
			                    <strong>R$ " & __GrossProfitTotal_Invoiced_formated & "
			                    </strong> 
			                </span>
			                <!-- Target -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__GrossProfitTotal_PercentTarget > 0, "#4C7596", IF(__GrossProfitTotal_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__GrossProfitTotal_PercentTarget > 0, "&#9650; ", IF(__GrossProfitTotal_PercentTarget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__GrossProfitTotal_PercentTarget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                         vs "&_Target&"
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__GrossProfitTotal_PercentBudget > 0, "#4C7596", IF(__GrossProfitTotal_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__GrossProfitTotal_PercentBudget > 0, "&#9650; ", IF(__GrossProfitTotal_PercentBudget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__GrossProfitTotal_PercentBudget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Budget&"
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__GrossProfitTotal_PercentForecast > 0, "#4C7596", IF(__GrossProfitTotal_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__GrossProfitTotal_PercentForecast > 0, "&#9650; ", IF(__GrossProfitTotal_PercentForecast < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__GrossProfitTotal_PercentForecast), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Forecast&"
			                    </span>
			                </span>
			            </div>
			        </div>
			
			        <!-- Card 2 -->
			        <div style='height: 92px; width: 110px; border-radius: 10px; background-color: white;'>
			            <!-- Título do Card -->
			            <div style=' height: 10px; margin-top: 5px; margin-left: 4px; color: black; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Lucro Bruto (%)",
			                        3,"Gross Profit (%)",
			                        2,"Bruttogewinn (%)"
			                )
			            &"
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 4px; padding-top: 4px; height: 75px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Invoiced -->
			                <span style='font-size: 12px; color: black; margin-bottom: 2px;'>
			                    <strong> " &  FORMAT(__GrossProfitPercent_Invoiced, "#0.00%") & "
			                    </strong> 
			                </span>
			                <!-- Target -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__GrossProfitPercent_PercentTarget > 0, "#4C7596", IF(__GrossProfitPercent_PercentTarget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__GrossProfitPercent_PercentTarget > 0, "&#9650; ", IF(__GrossProfitPercent_PercentTarget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__GrossProfitPercent_PercentTarget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                         vs "&_Target&"
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__GrossProfitPercent_PercentBudget > 0, "#4C7596", IF(__GrossProfitPercent_PercentBudget < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__GrossProfitPercent_PercentBudget > 0, "&#9650; ", IF(__GrossProfitPercent_PercentBudget < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__GrossProfitPercent_PercentBudget), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Budget&"
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 9px; margin-bottom: 2px; color: 
			                        " & IF(__GrossProfitPercent_PercentForecast > 0, "#4C7596", IF(__GrossProfitPercent_PercentForecast < 0, "#dc3545", "black")) & ";'>
			                        " & IF(__GrossProfitPercent_PercentForecast > 0, "&#9650; ", IF(__GrossProfitPercent_PercentForecast < 0, "&#9660; ", "")) & 
			                        FORMAT(ABS(__GrossProfitPercent_PercentForecast), "0.00%") & "
			                    <span style='font-size: 8px; margin-bottom: 2px; color: grey'>
			                     vs "&_Forecast&"
			                    </span>
			                </span>
			            </div>
			        </div>
			    </div>
			</div>
			
			
			"
			
			
			```
		isHidden
		displayFolder: HTML
		lineageTag: d496b67e-dc16-49c1-95ed-249cbc3a3549

	measure 'HTML - Cards Sales' = ```
			
			VAR _lista = CALCULATETABLE(VALUES(dCalendario[data]),SAMEPERIODLASTYEAR(dCalendario[data]))
			VAR __GrossProfitTotal_Invoiced = [Gross Profit Total (R$/t)] 
			VAR __GrossProfitTotal_Target = [Gross Profit Total (R$/t)_Target] 
			VAR __GrossProfitTotal_Budget = [Gross Profit Total (R$/t)_budget] 
			VAR __GrossProfitTotal_Forecast = [Gross Profit Total (R$/t)_forecast] 
			
			VAR __GrossProfitPercent_Invoiced = [Gross Profit (%)] 
			VAR __GrossProfitPercent_Target = [GrossProfit_target (%)] 
			VAR __GrossProfitPercent_Budget = [GrossProfit_budget (%)]
			VAR __GrossProfitPercent_Forecast = [GrossProfit_forecast (%)] 
			
			VAR __Revenue_Invoiced = [Faturamento] 
			VAR __Revenue_Target = [Faturamento_target]  
			VAR __Revenue_Budget = [Faturamento_budget]  
			VAR __Revenue_Forecast = [Faturamento_forecast]  
			VAR __Revenue_LY = CALCULATE([Faturamento] ,_lista)--SAMEPERIODLASTYEAR(dCalendario[data])) 
			
			VAR __AveragePrice_Invoiced = [Preco Medio]
			VAR __AveragePrice_Target = [Preco Medio_target]  
			VAR __AveragePrice_Budget = [Preco Medio_budget]  
			VAR __AveragePrice_Forecast = [Preco Medio_forecast]  
			VAR __AveragePrice_LY = CALCULATE([Preco Medio] ,_lista)--SAMEPERIODLASTYEAR(dCalendario[data])) 
			
			VAR __Peso_Invoiced = [PesoFaturado]
			VAR __Peso_Target = [Target Peso] 
			VAR __Peso_Budget = [Budget Peso] 
			VAR __Peso_Forecast = [Forecast Peso]
			VAR __Peso_LY = CALCULATE([PesoFaturado] ,_lista)--SAMEPERIODLASTYEAR(dCalendario[data])) 
			
			-- Variáveis Percentuais
			VAR __GrossProfitTotal_PercentTarget = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Target, __GrossProfitTotal_Target, 0)
			VAR __GrossProfitTotal_PercentBudget = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Budget, __GrossProfitTotal_Budget, 0)
			VAR __GrossProfitTotal_PercentForecast = DIVIDE(__GrossProfitTotal_Invoiced - __GrossProfitTotal_Forecast, __GrossProfitTotal_Forecast, 0)
			
			VAR __GrossProfitPercent_PercentTarget = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Target, __GrossProfitPercent_Target, 0)
			VAR __GrossProfitPercent_PercentBudget = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Budget, __GrossProfitPercent_Budget, 0)
			VAR __GrossProfitPercent_PercentForecast = DIVIDE(__GrossProfitPercent_Invoiced - __GrossProfitPercent_Forecast, __GrossProfitPercent_Forecast, 0)
			
			VAR __Revenue_PercentTarget = DIVIDE(__Revenue_Invoiced - __Revenue_Target, __Revenue_Target, 0)
			VAR __Revenue_PercentBudget = DIVIDE(__Revenue_Invoiced - __Revenue_Budget, __Revenue_Budget, 0)
			VAR __Revenue_PercentForecast = DIVIDE(__Revenue_Invoiced - __Revenue_Forecast, __Revenue_Forecast, 0)
			VAR __Revenue_PercentLY = DIVIDE(__Revenue_Invoiced - __Revenue_LY, __Revenue_LY, 0)
			
			VAR __AveragePrice_PercentTarget = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Target, __AveragePrice_Target, 0)
			VAR __AveragePrice_PercentBudget = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Budget, __AveragePrice_Budget, 0)
			VAR __AveragePrice_PercentForecast = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_Forecast, __AveragePrice_Forecast, 0)
			VAR __AveragePrice_PercentLY = DIVIDE(__AveragePrice_Invoiced - __AveragePrice_LY, __AveragePrice_LY, 0)
			
			VAR __Peso_PercentTarget = DIVIDE(__Peso_Invoiced - __Peso_Target, __Peso_Target, 0)
			VAR __Peso_PercentBudget = DIVIDE(__Peso_Invoiced - __Peso_Budget, __Peso_Budget, 0)
			VAR __Peso_PercentForecast = DIVIDE(__Peso_Invoiced - __Peso_Forecast, __Peso_Forecast, 0)
			VAR __Peso_PercentLY = DIVIDE(__Peso_Invoiced - __Peso_LY, __Peso_LY, 0)
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _atual = 
			SWITCH(_selecaoIdioma,
			        1,"Atual",
			        2,"Aktuell",
			        3,"Actual"
			)
			VAR _Target = 
			SWITCH(_selecaoIdioma,
			        1,"Meta",
			        2,"Ziel",
			        3,"Target"
			)
			VAR _Budget = 
			SWITCH(_selecaoIdioma,
			        1,"Orçamento",
			        "Budget"
			)
			VAR _Forecast = 
			SWITCH(_selecaoIdioma,
			        1,"Previsão",
			        "Forecast"
			)
			
			VAR _release = 
			SWITCH(_selecaoIdioma,
			        1,"Liberado",
			        2,"Freigegeben",
			        3,"Released"
			)
			
			VAR _ToRelease = 
			SWITCH(_selecaoIdioma,
			        1,"A liberar",
			        2,"Zu freigeben",
			        3,"To release"
			)
			
			VAR _AnoAnterior = 
			SWITCH(_selecaoIdioma,
			        1,"Ano anterior",
			        2,"Vorjahr",
			        3,"Last year"
			)
			RETURN
			
			"
			<div style='display: flex; flex-wrap: wrap;'>
			    <!-- Linha 1 -->
			    <div style='display: flex; margin-top: 0px; margin-bottom: 7px'>
			        
			        <!-- Card 1 -->
			        <div style='height: 95px; width: 185px; border-radius: 10px;'>
			            <!-- Título do Card -->
			            <div style=' height: 20px; margin-left: 1px; color: white; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Faturamento(R$)",
			                        3,"Revenue(R$)",
			                        2,"Umsatz(R$)"
			                )
			            &"<span style = 'font-size: 12px; margin-left: 3px;'> <strong>R$"&SWITCH(TRUE(), 
			                        ABS(__Revenue_Invoiced) >= 1E9, FORMAT(__Revenue_Invoiced, "#,,,.00B"), 
			                        ABS(__Revenue_Invoiced) >= 1E6, FORMAT(__Revenue_Invoiced, "#,,.00M"), 
			                        ABS(__Revenue_Invoiced) >= 1E3, FORMAT(__Revenue_Invoiced, "#,.00K"), 
			                        FORMAT(__Revenue_Invoiced, "#0.00")) &"
			                    </strong> </span>
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 1px; height: 75px; width: 185px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Target -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Target&":</strong> 
			                    <span style=' color:" &
			                        IF(__Revenue_PercentTarget > 0, "#4C7596", IF(__Revenue_PercentTarget < 0, "#dc3545", "black")) & ";'> R$ " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Revenue_Target) >= 1E9, FORMAT(__Revenue_Target, "#,,,.00B"), 
			                            ABS(__Revenue_Target) >= 1E6, FORMAT(__Revenue_Target, "#,,.00M"), 
			                            ABS(__Revenue_Target) >= 1E3, FORMAT(__Revenue_Target, "#,.00K"), 
			                            FORMAT(__Revenue_Target, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Revenue_PercentTarget >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Revenue_PercentTarget, "0.00") & "% " & IF(__Revenue_PercentTarget > 0, "☑", IF(__Revenue_PercentTarget < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Budget&":</strong> 
			                    <span style=' color:" &
			                        IF(__Revenue_PercentBudget > 0, "#4C7596", IF(__Revenue_PercentBudget < 0, "#dc3545", "black")) & ";'> R$ " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Revenue_Budget) >= 1E9, FORMAT(__Revenue_Budget, "#,,,.00B"), 
			                            ABS(__Revenue_Budget) >= 1E6, FORMAT(__Revenue_Budget, "#,,.00M"), 
			                            ABS(__Revenue_Budget) >= 1E3, FORMAT(__Revenue_Budget, "#,.00K"), 
			                            FORMAT(__Revenue_Budget, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Revenue_PercentBudget >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Revenue_PercentBudget, "0.00%") & " " & IF(__Revenue_PercentBudget > 0, "☑", IF(__Revenue_PercentBudget < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Forecast&":</strong> 
			                    <span style=' color:" &
			                        IF(__Revenue_PercentForecast > 0, "#4C7596", IF(__Revenue_PercentForecast < 0, "#dc3545", "black")) & ";'> R$ " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Revenue_Forecast) >= 1E9, FORMAT(__Revenue_Forecast, "#,,,.00B"), 
			                            ABS(__Revenue_Forecast) >= 1E6, FORMAT(__Revenue_Forecast, "#,,.00M"), 
			                            ABS(__Revenue_Forecast) >= 1E3, FORMAT(__Revenue_Forecast, "#,.00K"), 
			                            FORMAT(__Revenue_Forecast, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Revenue_PercentForecast >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Revenue_PercentForecast, "0.00%") & " " & IF(__Revenue_PercentForecast > 0, "☑", IF(__Revenue_PercentForecast < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Last Year -->
			                <span style='font-size: 10px; margin-bottom: 0px;'>
			                    <strong>"&_AnoAnterior&":</strong> 
			                    <span style=' color:" &
			                        IF(__Revenue_PercentLY > 0, "#4C7596", IF(__Revenue_PercentLY < 0, "#dc3545", "black")) & ";'> R$ " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Revenue_LY) >= 1E9, FORMAT(__Revenue_LY, "#,,,.00B"), 
			                            ABS(__Revenue_LY) >= 1E6, FORMAT(__Revenue_LY, "#,,.00M"), 
			                            ABS(__Revenue_LY) >= 1E3, FORMAT(__Revenue_LY, "#,.00K"), 
			                            FORMAT(__Revenue_LY, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Revenue_PercentLY >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Revenue_PercentLY, "0.00%") & " " & IF(__Revenue_PercentLY > 0, "☑", IF(__Revenue_PercentLY < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			            </div>
			        </div>
			    </div>
			
			    <!-- Linha 2 -->
			    <div style='display: flex; margin-bottom: 7px'>
			        
			        <!-- Peso -->
			        <div style='height: 93px; width: 185px; border-radius: 10px;'>
			            <!-- Título do Card -->
			            <div style=' height: 20px; margin-left: 1px; color: white; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Peso total(t)",
			                        2,"Gesamtgewicht(t)",
			                        3,"Total weight(t)"
			                )
			            &"<span style = 'font-size: 12px; margin-left: 3px;'> <strong>"&SWITCH(TRUE(), 
			                        ABS(__Peso_Invoiced) >= 1E9, FORMAT(__Peso_Invoiced, "#,,,.00B"), 
			                        ABS(__Peso_Invoiced) >= 1E6, FORMAT(__Peso_Invoiced, "#,,.00M"), 
			                        ABS(__Peso_Invoiced) >= 1E3, FORMAT(__Peso_Invoiced, "#,.00K"), 
			                        FORMAT(__Peso_Invoiced, "#0.00")) &"
			                    </strong> </span>
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 1px; height: 75px; width: 185px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Target -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Target&":</strong> 
			                    <span style=' color:" &
			                        IF(__Peso_PercentTarget > 0, "#4C7596", IF(__Peso_PercentTarget < 0, "#dc3545", "black")) & ";'> " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Peso_Target) >= 1E9, FORMAT(__Peso_Target, "#,,,.00B"), 
			                            ABS(__Peso_Target) >= 1E6, FORMAT(__Peso_Target, "#,,.00M"), 
			                            ABS(__Peso_Target) >= 1E3, FORMAT(__Peso_Target, "#,.00K"), 
			                            FORMAT(__Peso_Target, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Peso_PercentTarget >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Peso_PercentTarget, "0.00%") & " " & IF(__Peso_PercentTarget > 0, "☑", IF(__Peso_PercentTarget < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Budget&":</strong> 
			                    <span style=' color:" &
			                        IF(__Peso_PercentBudget > 0, "#4C7596", IF(__Peso_PercentBudget < 0, "#dc3545", "black")) & ";'>" 
			                        & SWITCH(TRUE(), 
			                            ABS(__Peso_Budget) >= 1E9, FORMAT(__Peso_Budget, "#,,,.00B"), 
			                            ABS(__Peso_Budget) >= 1E6, FORMAT(__Peso_Budget, "#,,.00M"), 
			                            ABS(__Peso_Budget) >= 1E3, FORMAT(__Peso_Budget, "#,.00K"), 
			                            FORMAT(__Peso_Budget, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Peso_PercentBudget >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Peso_PercentBudget, "0.00%") & " " & IF(__Peso_PercentBudget > 0, "☑", IF(__Peso_PercentBudget < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Forecast&":</strong> 
			                    <span style=' color:" &
			                        IF(__Peso_PercentForecast > 0, "#4C7596", IF(__Peso_PercentForecast < 0, "#dc3545", "black")) & ";'> " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Peso_Forecast) >= 1E9, FORMAT(__Peso_Forecast, "#,,,.00B"), 
			                            ABS(__Peso_Forecast) >= 1E6, FORMAT(__Peso_Forecast, "#,,.00M"), 
			                            ABS(__Peso_Forecast) >= 1E3, FORMAT(__Peso_Forecast, "#,.00K"), 
			                            FORMAT(__Peso_Forecast, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Peso_PercentForecast >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Peso_PercentForecast, "0.00%") & " " & IF(__Peso_PercentForecast > 0, "☑", IF(__Peso_PercentForecast < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Last Year -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_AnoAnterior&":</strong> 
			                    <span style=' color:" &
			                        IF(__Peso_PercentLY > 0, "#4C7596", IF(__Peso_PercentLY < 0, "#dc3545", "black")) & ";'> " 
			                        & SWITCH(TRUE(), 
			                            ABS(__Peso_LY) >= 1E9, FORMAT(__Peso_LY, "#,,,.00B"), 
			                            ABS(__Peso_LY) >= 1E6, FORMAT(__Peso_LY, "#,,.00M"), 
			                            ABS(__Peso_LY) >= 1E3, FORMAT(__Peso_LY, "#,.00K"), 
			                            FORMAT(__Peso_LY, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__Peso_PercentLY >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__Peso_PercentLY, "0.00%") & " " & IF(__Peso_PercentLY > 0, "☑", IF(__Peso_PercentLY < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			            </div>
			        </div>
			    </div>
			
			    <!-- Linha 3 -->
			    <div style='display: flex'>
			
			        <div style='height: 45px; width: 185px; border-radius: 10px;'>
			            <!-- Título do Card -->
			            <div style=' height: 20px; margin-left: 1px; color: white; font-weight: bold; text-align: left;  display: flex; align-items: center; border-radius: 10px 10px 0 0; font-size: 10px;margin-bottom: 4px'>
			                    "& 
			                SWITCH(_selecaoIdioma,
			                        1,"Preço Médio(R$/kg)",
			                        3,"Avarage Price(R$/kg)",
			                        2,"Durchschnittspreis(R$/kg)"
			                )
			            &"<span style = 'font-size: 12px; margin-left: 3px;'> <strong>R$"&SWITCH(TRUE(), 
			                        ABS(__AveragePrice_Invoiced) >= 1E9, FORMAT(__AveragePrice_Invoiced, "#,,,.00B"), 
			                        ABS(__AveragePrice_Invoiced) >= 1E6, FORMAT(__AveragePrice_Invoiced, "#,,.00M"), 
			                        ABS(__AveragePrice_Invoiced) >= 1E3, FORMAT(__AveragePrice_Invoiced, "#,.00K"), 
			                        FORMAT(__AveragePrice_Invoiced, "#0.00")) &"
			                    </strong> </span>
			            </div>
			            <!-- Conteúdo do Card -->
			            <div style='padding-left: 1px; height: 65px; width: 185px; display: flex; flex-direction: column; justify-content: center;'>
			                <!-- Target -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Target&":</strong> 
			                    <span style=' color:" &
			                        IF(__AveragePrice_PercentTarget > 0, "#4C7596", IF(__AveragePrice_PercentTarget < 0, "#dc3545", "black")) & ";'> " 
			                        & SWITCH(TRUE(), 
			                            ABS(__AveragePrice_Target) >= 1E9, FORMAT(__AveragePrice_Target, "#,,,.00B"), 
			                            ABS(__AveragePrice_Target) >= 1E6, FORMAT(__AveragePrice_Target, "#,,.00M"), 
			                            ABS(__AveragePrice_Target) >= 1E3, FORMAT(__AveragePrice_Target, "#,.00K"), 
			                            FORMAT(__AveragePrice_Target, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__AveragePrice_PercentTarget >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__AveragePrice_PercentTarget, "0.00%") & " " & IF(__AveragePrice_PercentTarget > 0, "☑", IF(__AveragePrice_PercentTarget < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Budget -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Budget&":</strong> 
			                    <span style=' color:" &
			                        IF(__AveragePrice_PercentBudget > 0, "#4C7596", IF(__AveragePrice_PercentBudget < 0, "#dc3545", "black")) & ";'>" 
			                        & SWITCH(TRUE(), 
			                            ABS(__AveragePrice_Budget) >= 1E9, FORMAT(__AveragePrice_Budget, "#,,,.00B"), 
			                            ABS(__AveragePrice_Budget) >= 1E6, FORMAT(__AveragePrice_Budget, "#,,.00M"), 
			                            ABS(__AveragePrice_Budget) >= 1E3, FORMAT(__AveragePrice_Budget, "#,.00K"), 
			                            FORMAT(__AveragePrice_Budget, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__AveragePrice_PercentBudget >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__AveragePrice_PercentBudget, "0.00%") & " " & IF(__AveragePrice_PercentBudget > 0, "☑", IF(__AveragePrice_PercentBudget < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Forecast -->
			                <span style='font-size: 10px; margin-bottom: 2px;'>
			                    <strong>"&_Forecast&":</strong> 
			                    <span style=' color:" &
			                        IF(__AveragePrice_PercentForecast > 0, "#4C7596", IF(__AveragePrice_PercentForecast < 0, "#dc3545", "black")) & ";'> " 
			                        & SWITCH(TRUE(), 
			                            ABS(__AveragePrice_Forecast) >= 1E9, FORMAT(__AveragePrice_Forecast, "#,,,.00B"), 
			                            ABS(__AveragePrice_Forecast) >= 1E6, FORMAT(__AveragePrice_Forecast, "#,,.00M"), 
			                            ABS(__AveragePrice_Forecast) >= 1E3, FORMAT(__AveragePrice_Forecast, "#,.00K"), 
			                            FORMAT(__AveragePrice_Forecast, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__AveragePrice_PercentForecast >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__AveragePrice_PercentForecast, "0.00%") & " " & IF(__AveragePrice_PercentForecast > 0, "☑", IF(__AveragePrice_PercentForecast < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			                <!-- Last Year -->
			                <span style='font-size: 10px; margin-bottom: 0px;'>
			                    <strong>"&_AnoAnterior&":</strong> 
			                    <span style=' color:" &
			                        IF(__AveragePrice_PercentLY > 0, "#4C7596", IF(__AveragePrice_PercentLY < 0, "#dc3545", "black")) & ";'> R$ " 
			                        & SWITCH(TRUE(), 
			                            ABS(__AveragePrice_LY) >= 1E9, FORMAT(__AveragePrice_LY, "#,,,.00B"), 
			                            ABS(__AveragePrice_LY) >= 1E6, FORMAT(__AveragePrice_LY, "#,,.00M"), 
			                            ABS(__AveragePrice_LY) >= 1E3, FORMAT(__AveragePrice_LY, "#,.00K"), 
			                            FORMAT(__AveragePrice_LY, "#0.00")) 
			                        &"<span style='margin-left: 4px; background-color:" &
			                        IF(__AveragePrice_PercentLY >= 0, "white","#F3EDE6") & ";'>
			                        " &
			                        FORMAT(__AveragePrice_PercentLY, "0.00%") & " " & IF(__AveragePrice_PercentLY > 0, "☑", IF(__AveragePrice_PercentLY < 0, "⚠", "")) &"
			                        </span>
			                    </span>
			                </span>
			            </div>
			        </div>
			
			    </div>
			
			   
			
			</div>
			
			
			"
			
			
			```
		isHidden
		displayFolder: HTML
		lineageTag: 9f9e4735-97fb-48b2-adc5-c7b27a83def4

	measure 'HTML CSAT' = ```
			
			
			// Insatisfação
			VAR _indiceInsat = [Indice Insatisfação]
			VAR _indiceInsatLY = [Index LY]
			VAR _perc_insat_vsLy = [% insat vs LY]+0
			VAR _seta = IF(_perc_insat_vsLy > 0, "&#9650; ", IF(_perc_insat_vsLy < 0, "&#9660; ", ""))
			
			// Reclamação
			VAR _qtdTotalReclamacoesImprocedentes = 
			CALCULATE(
			    COUNTROWS(fReclamacao),
			    dArtigo[identificacao] = "REL",
			    KEEPFILTERS(dDecisao_reclamacao[id_decisao] = 1)
			    )
			
			VAR _qtd_recl_proce_LY = 
			CALCULATE(
			    COUNTROWS(fReclamacao),
			    dArtigo[identificacao] = "REL",
			    KEEPFILTERS(dDecisao_reclamacao[id_decisao] = 1),
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			
			VAR _qtd_recl_imp_LY = 
			CALCULATE(
			    COUNTROWS(fReclamacao),
			    dArtigo[identificacao] = "REL",
			    KEEPFILTERS(dDecisao_reclamacao[id_decisao] <> 1),
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			
			VAR _qtd_recl_total_LY = _qtd_recl_imp_LY + _qtd_recl_proce_LY
			
			VAR _qtdReclTecnica =
			CALCULATE(
			    COUNTROWS(fReclamacao),
			   fReclamacao[tipo_reclamacao]="Tecnica",
			   dArtigo[identificacao] = "REL",
			    KEEPFILTERS(dDecisao_reclamacao[id_decisao] <> 1)
			   )
			
			VAR _qtdReclLogistica = 
			CALCULATE(
			    COUNTROWS(fReclamacao),
			   fReclamacao[tipo_reclamacao]="Logistica",
			    KEEPFILTERS(dDecisao_reclamacao[id_decisao] <> 1)
			   )
			VAR _qtdReclComercial = 
			CALCULATE(
			    COUNTROWS(fReclamacao),
			   fReclamacao[tipo_reclamacao]="Comercial",
			    KEEPFILTERS(dDecisao_reclamacao[id_decisao] <> 1)
			   )
			VAR _qtdReclProcedentes= _qtdReclTecnica + _qtdReclLogistica + _qtdReclComercial
			VAR _qtdReclTotal = _qtdReclProcedentes + _qtdTotalReclamacoesImprocedentes
			
			VAR _perc_qtd_total_proce_LY = DIVIDE(_qtdReclTotal-_qtd_recl_total_LY,_qtd_recl_total_LY)+0
			VAR _perc_qtd_recl_proce_LY = DIVIDE(_qtdReclProcedentes-_qtd_recl_proce_LY,_qtd_recl_proce_LY)+0
			VAR _perc_qtd_imp_proce_LY = DIVIDE(_qtdTotalReclamacoesImprocedentes-_qtd_recl_imp_LY,_qtd_recl_imp_LY)+0
			
			VAR _seta2 = IF(_perc_qtd_recl_proce_LY > 0, "&#9650; ", IF(_perc_qtd_recl_proce_LY < 0, "&#9660; ", ""))
			VAR _seta3 = IF(_perc_qtd_total_proce_LY > 0, "&#9650; ", IF(_perc_qtd_total_proce_LY < 0, "&#9660; ", ""))
			VAR _seta4 = IF(_perc_qtd_imp_proce_LY > 0, "&#9650; ", IF(_perc_qtd_imp_proce_LY < 0, "&#9660; ", ""))
			
			
			// Devoluções
			VAR _qtd_dev_total = [Devoluções (qtd)]
			VAR _qtd_dev_total_LY = CALCULATE( [Devoluções (qtd)], SAMEPERIODLASTYEAR(dCalendario[data]) )
			
			VAR _qtdDevTecnica = [Devoluções(qtd) Técnica]
			VAR _qtdDevTecnica_LY = CALCULATE([Devoluções(qtd) Técnica], SAMEPERIODLASTYEAR(dCalendario[data]))
			
			VAR _qtdDevLogistica = [Devoluções(qtd) Logística]
			VAR _qtdDevLogistica_LY = CALCULATE([Devoluções(qtd) Logística], SAMEPERIODLASTYEAR(dCalendario[data]))
			
			VAR _qtdDevComercial = [Devoluções(qtd) Comercial]
			VAR _qtdDevComercial_LY = CALCULATE([Devoluções(qtd) Comercial], SAMEPERIODLASTYEAR(dCalendario[data]))
			
			
			VAR _perc_qtd_dev_total_LY = DIVIDE(_qtd_dev_total - _qtd_dev_total_LY,_qtd_dev_total_LY)+0
			VAR _perc_qtdDevTecnica_LY = DIVIDE(_qtdDevTecnica-_qtdDevTecnica_LY,_qtdDevTecnica_LY)+0
			VAR _perc_qtdDevLogistica_LY = DIVIDE(_qtdDevLogistica-_qtdDevLogistica_LY,_qtdDevLogistica_LY)+0
			VAR _perc_qtdDevComercial_LY = DIVIDE(_qtdDevComercial-_qtdDevComercial_LY,_qtdDevComercial_LY)+0
			
			VAR _seta5 = IF(_perc_qtd_dev_total_LY > 0, "&#9650; ", IF(_perc_qtd_dev_total_LY < 0, "&#9660; ", ""))
			VAR _seta6 = IF(_perc_qtdDevTecnica_LY > 0, "&#9650; ", IF(_perc_qtdDevTecnica_LY < 0, "&#9660; ", ""))
			VAR _seta7 = IF(_perc_qtdDevLogistica_LY > 0, "&#9650; ", IF(_perc_qtdDevLogistica_LY < 0, "&#9660; ", ""))
			VAR _seta8 = IF(_perc_qtdDevComercial_LY > 0, "&#9650; ", IF(_perc_qtdDevComercial_LY < 0, "&#9660; ", ""))
			
			// Traduções
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _reclamacao = 
			SWITCH(_selecaoIdioma,
			        1,"Reclamações",
			        2,"Reklamationen",
			        3,"Complaints"
			)
			VAR _quantidade = 
			SWITCH(_selecaoIdioma,
			        1,"(quantidade)",
			        2,"(Anzahl)",
			        3,"(quantity)"
			)
			VAR _tecnica = 
			SWITCH(_selecaoIdioma,
			        1,"Técnica",
			        2,"Technisch",
			        3,"Technical"
			)
			VAR _comercial = 
			SWITCH(_selecaoIdioma,
			        1,"Comercial",
			        2,"Kommerziell",
			        3,"Commercial"
			)
			VAR _Logistica = 
			SWITCH(_selecaoIdioma,
			        1,"Logística",
			        2,"Logistik",
			        3,"Logistics"
			)
			VAR _clientes = 
			SWITCH(_selecaoIdioma,
			        1,"Quantidade de insatisfações",
			        2,"Anzahl der Unzufriedenheiten",
			        3,"Quantity of dissatisfactions"
			)
			
			VAR _procedentes = 
			SWITCH(_selecaoIdioma,
			        1,"Procedente",
			        2,"Berechtigt",
			        3,"Justified"
			)
			
			VAR _improcedente = 
			SWITCH(_selecaoIdioma,
			        1,"Improcedente",
			        2,"Unberechtigt",
			        3,"Unjustified"
			)
			/*
			VAR _procedente_tipo = 
			SWITCH(_selecaoIdioma,
			        1,"Procedentes por tipo",
			        2,"Berechtigt nach Typ",
			        3,"Justified by type"
			)
			*/
			VAR Devolucoes = 
			SWITCH(_selecaoIdioma,
			        1,"Devoluções",
			        2,"Rückgaben",
			        3,"Returns"
			)
			
			VAR _HTML = 
			"
			<html>
			<body>"&
			"<div>"&
			    "<div class='back_card1'>"&
			        "<div class='header'><strong>"&_clientes&" </strong></div>"&
			        "<div class= 'valor'>" &_indiceInsat &" <span style='color: #CCCCCC; font-size:10px;margin-top:2px'>"&_seta&" "&ROUND(ABS(_perc_insat_vsLy*100),2)&"% LY </span>"&"</div>"&
			    "</div>"&
			    "<div class='back_card2'>"&
			         "<div class='header'><strong>"&_reclamacao&"</strong></div>"&"<div class='header2'><strong>"&_quantidade&"</strong></div>"&
			        "<div class= 'valor'>" &_qtdReclTotal &"<span style='color: #CCCCCC; font-size:10px;margin-top:0px'>  "&_seta3&" "&ROUND(ABS(_perc_qtd_total_proce_LY*100),1)&"% LY </span>"&"</div>"&
			        "<div class='texto2'><strong>"&_procedentes&": </strong>"& _qtdReclProcedentes&"<span style='color: #CCCCCC; font-size:10px;margin-top:0px'>  "&_seta2&" "&ROUND(ABS(_perc_qtd_recl_proce_LY*100),1)&"% LY </span>"&"</div>"&
			        "<div class='texto2'><strong>"&_improcedente&": </strong>"& _qtdTotalReclamacoesImprocedentes&"<span style='color: #CCCCCC; font-size:10px;margin-top:0px'>  "&_seta4&" "&ROUND(ABS(_perc_qtd_imp_proce_LY*100),1)&"% LY </span>"&"</div>"&
			    "</div>"&
			
			    "<div class='back_card3'>"&
			        "<div class='header'><b>"&Devolucoes&"</b></div>"
			        &"<div class='header2'><strong>"&_quantidade&"</strong></div>"
			        &"<div class= 'valor'>" &_qtd_dev_total &" <span style='color: #CCCCCC; font-size:10px;margin-top:2px'>"&_seta5&" "&ROUND(ABS(_perc_qtd_dev_total_LY*100),2)&"% LY </span>"&
			        "<div style='margin-top: 0px;'>"&
			            "<div class='texto2'><strong>"&_tecnica&": </strong>"& _qtdDevTecnica&"<span style='color: #CCCCCC; font-size:10px;margin-top:0px'>  "&_seta6 &" "& ROUND(ABS(_perc_qtdDevTecnica_LY*100),2)&"% LY </span></div>"&
			            "<div class='texto2'><strong>"&_comercial&": </strong>"& _qtdDevComercial&"<span style='color: #CCCCCC; font-size:10px;margin-top:0px'>  "&_seta7 &" "& ROUND(ABS(_perc_qtdDevComercial_LY*100),2)&"% LY </span></div>"&
			            "<div class='texto2'><strong>"&_Logistica&": </strong>"& _qtdDevLogistica&"<span style='color: #CCCCCC; font-size:10px;margin-top:0px'>  "&_seta8 &" "&ROUND(ABS(_perc_qtdDevLogistica_LY*100),2)&"% LY </span></div>"&
			        "</div>"&
			
			    "</div>"&
			"</div>"&"
			</body>
			<style>
			    .back_card1{
			        border-radius: 5px;
			        background-color: #FFFFFF;
			        padding: 3px;
			        height: 72px
			        }
			    .back_card2{
			        border-radius: 5px;
			        background-color: #FFFFFF;
			        padding: 3px;
			        height: 100px;
			        margin-top: 3px;
			    }
			    .back_card3{
			        border-radius: 5px;
			        background-color: #FFFFFF;
			        padding: 3px;
			        height: 114px;
			        margin-top: 3px;
			    }
			    .header{
			        font-size:13px;
			        font: Segoe UI;
			        color: #003A69;
			        }
			
			    .header2{
			        font-size:12px;
			        font: Segoe UI;
			        color: #003A69;
			        }
			
			    .valor{
			        font-size:15px;
			        font: Segoe UI;
			        color: #003A69;
			        }
			
			        .texto{
			        font-size:11px;
			        font: Segoe UI;
			        color: #003A69;
			        padding-top: 7px;
			        }
			
			        .texto2{
			            font-size:10px;
			            font: Segoe UI;
			            color: #003A69;
			        }
			
			    .destaque{
			        .font-size: 8px;
			        .color: #CCCCCC;
			        }
			</style>
			</html>
			"
			
			RETURN
			_HTML
			```
		isHidden
		displayFolder: HTML
		lineageTag: 13c21f85-e659-4c02-98f0-cf87d57e7614

	measure 'HTML CSAT_2' = ```
			
			--VAR _seta = IF(_variacao > 0, "&#9650; ", IF(_variacao < 0, "&#9660; ", ""))\\
			VAR _Total_Qualidade = CALCULATE(COUNTROWS(fIQF),fIQF[criterio] = "Qualidade")
			VAR _Total_Entrega = CALCULATE(COUNTROWS(fIQF),fIQF[criterio] = "Entrega")
			VAR _Total_Geral = CALCULATE(COUNTROWS(fIQF),fIQF[criterio] = "Geral")
			VAR _Demerito_Qualidade = CALCULATE(SUM(fIQF[nota]),fIQF[criterio] = "Qualidade")
			VAR _Demerito_Entrega = CALCULATE(SUM(fIQF[nota]),fIQF[criterio] = "Entrega")
			VAR _Demerito_Geral = CALCULATE(SUM(fIQF[nota]),fIQF[criterio] = "Geral")
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _demerito = 
			SWITCH(_selecaoIdioma,
			        1,"Deméritos por critério",
			        2,"Abzüge nach Kriterium",
			        3,"Demerits by criterion"
			)
			VAR _qualidade = 
			SWITCH(_selecaoIdioma,
			        1,"Qualidade",
			        2,"Qualität",
			        3,"Quality"
			)
			VAR _entrega = 
			SWITCH(_selecaoIdioma,
			        1,"Entrega",
			        2,"Lieferung",
			        3,"Delivery"
			)
			VAR _geral = 
			SWITCH(_selecaoIdioma,
			        1,"Geral",
			        2,"Allgemein",
			        3,"General"
			)
			
			VAR _HTML = 
			"
			<html>
			<body>"&
			    "<div class='back_card1'>"&
			        "<div class='header'><strong>"&_demerito&"</strong></div>"&
			        "<div style='margin-top: 5px;'>"&
			            "<div class='texto'><strong>"&_entrega&": </strong>"& _Demerito_Entrega &"/"&_Total_Entrega&" ("& FORMAT(ROUND(DIVIDE(_Demerito_Entrega,_Total_Entrega)*100,2),"0.0")&"%)</div>"&
			            "<div class='texto'><strong>"&_qualidade&": </strong>"& _Demerito_Qualidade &"/"&_Total_Qualidade&" ("& FORMAT(ROUND(DIVIDE(_Demerito_Qualidade,_Total_Qualidade)*100,2),"0.0")&"%)</div>"&
			            "<div class='texto'><strong>"&_geral&": </strong>"& _Demerito_Geral &"/"&_Total_Geral&" ("&FORMAT(ROUND(DIVIDE(_Demerito_Geral,_Total_Geral)*100,2),"0.0")&"%)</div>"&
			        "</div>"&
			    "</div>"&"
			</body>
			<style>
			    .back_card1{
			        border-radius: 5px;
			        background-color: #FFFFFF;
			        padding: 5px;
			        height: 95px;
			        }
			    
			
			    .header{
			        font-size:14px;
			        font: Segoe UI;
			        color: #003A69;
			        }
			
			    .sub_header{
			        font-size:12px;
			        font: Segoe UI;
			        color: #003A69;
			        }
			
			    .valor{
			        font-size:16px;
			        font: Segoe UI;
			        color: #003A69;
			        }
			 
			    .destaque{
			        .font-size: 8px;
			        .color: #CCCCCC;
			        }
			    
			    .texto{
			        font-size:11px;
			        font: Segoe UI;
			        color: #003A69;
			        padding-top: 2px;
			        }
			</style>
			</html>
			"
			
			RETURN
			_HTML
			```
		isHidden
		displayFolder: HTML
		lineageTag: 24011976-33bb-4c29-8bcc-038264c3de97

	measure 'HTML EBTIDA' = ```
			
			// Configurações gerais
			VAR BaAlt = 30 --Altura da barra
			VAR CorTexto = "#003A69"
			VAR CorPositivo = "#8B9D9B"
			VAR CorNegativo = "#B22222"
			VAR Prop_Barra = 1.3  -- Multiplicador que define a posição da linha da meta / tamanho da barra (se é comum superar a meta de forma expressiva, colocar um valor maior)
			VAR _selecaoFormato = SELECTEDVALUE(pFormato[sFormato Pedido])
			
			// Cálculos|Medidas
			VAR _Faturamento = [Faturamento Líquido (EBITDA)]
			
			--Gross Profit R$/ton
			VAR _GMValor = [Gross Profit Comercial (EBITDA)]
			VAR _GMMeta = CALCULATE(SUM(fMetas_artigo[vlr_target])-SUM(fMetas_artigo[cst_mp_target]))
			VAR _GM_Prop_vsMeta_Valor = DIVIDE(_GMValor,_GMMeta)
			
			--Gross Profit %
			VAR _GMPerc =  [Gross Profit (%)]
			VAR _GMMetaPerc = [GrossProfit_target (%)]
			VAR _GMPerc_Prop_vsMeta_Valor = DIVIDE(_GMPerc,_GMMetaPerc)
			
			--EBITDA R$
			VAR _EBITDAValor = [EBITDA COMERCIAL] 
			VAR _EBITDAMeta = [Meta EBITDA (EBITDA)]
			VAR _EBITDA_Prop_vsMeta_Valor = DIVIDE(_EBITDAValor,_EBITDAMeta)
			
			--EBITDA %
			VAR _EBITDAPerc = DIVIDE(_EBITDAValor,_Faturamento)
			VAR _EBITDAMetaPerc =  DIVIDE(_EBITDAMeta,_Faturamento)
			VAR _EBITDAPerc_Prop_vsMeta_Valor = DIVIDE(_EBITDAPerc,_EBITDAMetaPerc)
			
			
			//Cálculos auxiliares para formatação das barras
			
			--Proporção Barra
			VAR PropGMValor = _GMMeta * Prop_Barra
			VAR PropGMPerc =_GMMetaPerc * Prop_Barra
			VAR PropEBITDAValor = _EBITDAMeta * Prop_Barra
			VAR PropEBITDAPerc =_EBITDAMetaPerc * Prop_Barra
			
			-- Cor da Barra
			VAR CorGM = IF(_GMValor >= _GMMeta, CorPositivo, CorNegativo)
			VAR CorGMPerc = IF(_GMPerc >= _GMMetaPerc, CorPositivo, CorNegativo)
			VAR CorEBITDA = IF(_EBITDAValor >= _EBITDAMeta, CorPositivo, CorNegativo)
			VAR CorEBITDAPerc = IF(_EBITDAPerc >= _EBITDAMetaPerc, CorPositivo, CorNegativo)
			
			--Cor texto
			VAR CorTextGM = IF(_GMValor >= _GMMeta, "black", "white")
			VAR CorTextGMPerc = IF(_GMPerc >= _GMMetaPerc, "black", "white")
			VAR CorTextEBITDA = IF(_EBITDAValor >= _EBITDAMeta, "black", "white")
			VAR CorTextEBITDAPerc = IF(_EBITDAPerc >= _EBITDAMetaPerc, "black", "white")
			
			
			//Valores Formatados para o rótulo
			VAR _GMPerc_F = FORMAT(_GMPerc,"#0.00%")
			VAR _EBITDAPerc_F = FORMAT(_EBITDAPerc,"#0.00%")
			
			var _GMValor_F = 
			FORMAT(_GMValor,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0",
			        1,SWITCH(
			                TRUE(),
			                ABS( _GMValor) >= 1E9, "#,,,.00B",
			                ABS( _GMValor) >= 1E6, "#,,.00M",
			                ABS( _GMValor) >= 1E3, "#,.00K",
			                "#,,,0"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			var _EBITDAValor_F = 
			FORMAT(_EBITDAValor,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0",
			        1,SWITCH(
			                TRUE(),
			                ABS( _EBITDAValor) >= 1E9, "#,,,.00B",
			                ABS( _EBITDAValor) >= 1E6, "#,,.00M",
			                ABS( _EBITDAValor) >= 1E3, "#,.00K",
			                "#,,,0"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _comercial = 
			SWITCH(_selecaoIdioma,
			        1,"EBITDA Comercial",
			        2,"Kommerziell EBITDA",
			        3,"Commercial EBITDA"
			)
			VAR _Target = 
			SWITCH(_selecaoIdioma,
			        1,"Meta",
			        2,"Ziel",
			        3,"Target"
			)
			VAR _gp = 
			SWITCH(_selecaoIdioma,
			        1,"Lucro Bruto",
			        2,"Bruttogewinn",
			        3,"Gross Profit"
			)
			VAR _semMeta = 
			SWITCH(_selecaoIdioma,
			        1,"Sem meta definida",
			        2,"Kein ziel definiert",
			        3,"No target defined"
			)
			RETURN
			"
			<html>
			<body>
			    <!-- Gross Profit (R$) -->
			    <div class = 'corpo'>
			        <span class='header'>"&_gp&" (R$)</span>
			        <span class='sub_header'>"&_Target&": <span style='color:"&CorGM&"'><b> "& FORMAT(_GM_Prop_vsMeta_Valor,"0.0%")&" </b></span></span>
			        <!-- Estrutura da barra -->
			        <div>
			            <span class= 'BarraFundo'></span>
			            <span style='width: "& round(DIVIDE(_GMValor,PropGMValor)*100,0) &"%; background-color: "& CorGM &"; position:absolute; height:"&BaAlt&"px'></span>
			            <span style='width: 1px; background-color: black; height:"&BaAlt&"px; position:absolute;left:"&round(DIVIDE(_GMMeta,PropGMValor)*100,0)&"%'></span>
			            <span style='height:"&BaAlt&"px; position:relative; color:"&CorTextGM&"; font-size: 14px; padding-left:5px; vertical-align:sub'>R$ "&_GMValor_F&"</span>
			        </div>
			    </div>
			
			    <div class='separador'></div>
			
			    <!-- Gross Profit (%) -->
			    <div class = 'corpo'>
			        <span class='header'>"&_gp&" KPI"&" (%)</span>
			        <span class='sub_header'>"&_Target&": <span style='color:"&CorGMPerc&"'><b> "& FORMAT(_GMPerc_Prop_vsMeta_Valor,"0.0%")&" </b></span></span>
			        <!-- Estrutura da barra -->
			        <div>
			            <span class= 'BarraFundo'></span>
			            <span style='width: "& round(DIVIDE(_GMPerc,PropGMPerc)*100,0) &"%; background-color: "& CorGMPerc &"; position:absolute; height:"&BaAlt&"px'></span>
			            <span style='width: 1px; background-color: black; height:"&BaAlt&"px; position:absolute;left:"&round(DIVIDE(_GMMetaPerc,PropGMPerc)*100,0)&"%'></span>
			            <span style='height:"&BaAlt&"px; position:relative; color:"&CorTextGMPerc&"; font-size: 14px; padding-left:5px; vertical-align:sub'>"&_GMPerc_F&"</span>
			        </div>
			    </div>
			   
			    <div class='separador'></div>
			    
			    <!-- Comercial (R$) -->
			    <div class = 'corpo'>
			        <span class='header'>"&_comercial&" (R$)</span>
			        "//<span class='sub_header'>"&_Target&": <span style='color:"&CorEBITDA&"'><b> "& FORMAT(_EBITDA_Prop_vsMeta_Valor,"0.0%")&" </b></span></span>
			        
			        &"<span class='sub_header'>"&_Target&": <span style='color:"&CorEBITDA&"'><b> "& _semMeta&" </b></span></span>
			        <!-- Estrutura da barra -->
			        <div>
			            <span class= 'BarraFundo'></span>
			            <span style='width: "& round(DIVIDE(_EBITDAValor,PropEBITDAValor)*100,0) &"%; background-color: "& CorEBITDA &"; position:absolute; height:"&BaAlt&"px'></span>
			            <span style='width: 1px; background-color: black; height:"&BaAlt&"px; position:absolute;left:"&round(DIVIDE(_EBITDAMeta,PropEBITDAValor)*00,0)&"%'></span>
			            <span style='height:"&BaAlt&"px; position:relative; color:"&CorTextEBITDA&"; font-size: 14px; padding-left:5px; vertical-align:sub'>R$ "&_EBITDAValor_F&"</span>
			        </div>
			    </div>
			    
			    <div class='separador'></div>
			    
			    <!-- Comercial (%) -->
			    <div class = 'corpo'>
			        <span class='header'>"&_comercial&" (%)</span>
			        "//<span class='sub_header'>"&_Target&": <span style='color:"&CorEBITDAPerc&"'><b> "& FORMAT(_EBITDAPerc_Prop_vsMeta_Valor,"0.0%")&" </b></span></span>
			        
			        &"<span class='sub_header'>"&_Target&": <span style='color:"&CorEBITDAPerc&"'><b> "& _semMeta&" </b></span></span>
			        <!-- Estrutura da barra -->
			        <div>
			            <span class= 'BarraFundo'></span>
			            <span style='width: "& round(DIVIDE(_EBITDAPerc,PropEBITDAPerc)*100,0) &"%; background-color: "& CorEBITDAPerc &"; position:absolute; height:"&BaAlt&"px'></span>
			            <span style='width: 1px; background-color: black; height:"&BaAlt&"px; position:absolute;left:"&round(DIVIDE(_EBITDAMetaPerc,PropEBITDAPerc)*00,0)&"%'></span>
			            <span style='height:"&BaAlt&"px; position:relative; color:"&CorTextEBITDAPerc&"; font-size: 14px; padding-left:5px; vertical-align:sub'>"&_EBITDAPerc_F&"</span>
			        </div>
			    </div>
			</body>
			<style>
			    .corpo {
			        margin-top:-2px;
			        display: flex;
			        flex-direction: column;
			        width:100%;
			    }
			    .header {
			        color: "&CorTexto&";
			        font-size: 14px;
			        font-weight: bold;
			        font-family: Segoe Ui;
			    }
			    .sub_header{
			        font-size: 12px;
			        font-family: Segoe Ui;
			        color: "&CorTexto&";
			        margin-top: -4px;
			        font-weight: 500;
			    }
			    .BarraFundo{
			        width: 100%; 
			        background-color: #D3D3D3;
			        height: "&BaAlt&"px; 
			        position: absolute;
			    }
			    .separador{
			        height:10px
			    }
			
			</style>
			</html>
			"
			```
		isHidden
		displayFolder: HTML
		lineageTag: a5487a75-0268-4f27-a24d-59a9a99c6d52

	measure 'HTML Tooltip' = ```
			
			//Parâmetros para filtos nas medidas
			VAR _metrica = SELECTEDVALUE(pMetricas[Valor])
			Var _selecaoFormato = SELECTEDVALUE(pFormato[sFormato Pedido])
			VAR _Ordem = SELECTEDVALUE(Helper_Scorecard[Ordem])
			var _idioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _periodo_calculo =
			 LOOKUPVALUE(
			            Helper_Scorecard[mes_ano_abreviado],
			            Helper_Scorecard[Ordem],
			            _Ordem
			        )
			VAR _periodo = 
			SWITCH(
			    _idioma,
			    1,_periodo_calculo,
			    2,LOOKUPVALUE(
			            Helper_Scorecard[mes_ano_DE],
			            Helper_Scorecard[Ordem],
			            _Ordem
			        ),    
			    3,LOOKUPVALUE(
			            Helper_Scorecard[mes_ano_EN],
			            Helper_Scorecard[Ordem],
			            _Ordem
			        )
			)
			VAR _periodo_LY_calculo = 
			LOOKUPVALUE(
			        Helper_Scorecard[mes_ano_abreviado],
			        Helper_Scorecard[Ordem],
			        _Ordem-12
			    )
			VAR _periodo_LY =
			IF(_periodo="YTD","YTD",
			    IFERROR(
			        SWITCH(
			                _idioma,
			                1,_periodo_LY_calculo,
			                2,LOOKUPVALUE(
			                        Helper_Scorecard[mes_ano_DE],
			                        Helper_Scorecard[Ordem],
			                        _Ordem-12
			                    ),    
			                3,LOOKUPVALUE(
			                        Helper_Scorecard[mes_ano_EN],
			                        Helper_Scorecard[Ordem],
			                        _Ordem-12
			                    )
			            )
			        ,"-"
			    )
			)
			VAR _MAXData_YTD = CALCULATE(MAX(dCalendario[data]),dCalendario[ano_mes_numerico]=MAX(dCalendario[ano_mes_numerico]))
			VAR _MaxData_Normal = CALCULATE(MAX(dCalendario[data]),dCalendario[mes_ano_abreviado]= _periodo_calculo)
			VAR _MaxData = MIN(IF(_periodo="YTD",_MAXData_YTD,_MaxData_Normal),TODAY())
			VAR Ano = YEAR(_MaxData)
			VAR Ano_Anterior = Ano-1
			VAR _MinData = DATE(Ano,1,1)
			VAR _MinDataLY = DATE(Ano_Anterior,1,1)
			VAR _listaDatasAnoAtual = DATESBETWEEN(dCalendario[data],_MinData,_MaxData)
			VAR _listaDatasAnoAnterior = DATESBETWEEN(dCalendario[data],_MinDataLY,EDATE(_MaxData,-12))
			
			
			//Cálculos
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			
			--YOY
			VAR _YOY_CY = [Scorecard_Invoiced]
			VAR _YOY_LY_mes = CALCULATE(
			    SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			            _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			            _selectedMetric IN {4, 18, 32}, [Indice Insatisfação]+0,
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			            _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			            _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			            _selectedMetric IN {12, 26, 40}, [Faturamento],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio]
			        ),REMOVEFILTERS(dCalendario)
			    ,dCalendario[mes_ano_abreviado]=_periodo_LY_calculo
			    )
			VAR _YOY_LY_YTD = CALCULATE([Scorecard_Invoiced],dCalendario[ano]=Ano_Anterior,dCalendario[data]<=EDATE(_MaxData,-12))
			VAR _YOY_LY = IF(_periodo="YTD",_YOY_LY_YTD,_YOY_LY_mes)
			
			VAR _VariacaoYOY = DIVIDE(_YOY_CY,_YOY_LY)-1
			
			--YTD
			VAR _YTD_CY = 
			    SWITCH(
			        TRUE(),
			        _selectedMetric IN {0, 14, 28}, CALCULATE([Local Market Sales (t)],_listaDatasAnoAtual),
			        _selectedMetric IN {1, 15, 29}, CALCULATE([Cold Rolled (market Sales: Local + Export) (t)],_listaDatasAnoAtual),
			        _selectedMetric IN {2, 16, 30}, CALCULATE([Export Market Sales (t)],_listaDatasAnoAtual),
			        _selectedMetric IN {3, 17, 31}, CALCULATE([Service Sales (KBRL)],_listaDatasAnoAtual),
			        _selectedMetric IN {4, 18, 32}, CALCULATE([Indice Insatisfação]+0,_listaDatasAnoAtual),
			        _selectedMetric IN {5, 19, 33}, CALCULATE([Gross Profit Total (R$/t)],_listaDatasAnoAtual),
			        _selectedMetric IN {6, 20, 34}, CALCULATE([Gross Profit (%)],_listaDatasAnoAtual),
			        _selectedMetric IN {7, 21, 35}, CALCULATE([Gross Profit - Cold Rolled (R$/t)],_listaDatasAnoAtual),
			        _selectedMetric IN {8, 22, 36}, CALCULATE([Customer Projects],_listaDatasAnoAtual),
			        _selectedMetric IN {9, 23, 37}, CALCULATE([Coated Sales Volumes (t)],_listaDatasAnoAtual),
			        _selectedMetric IN {10, 24, 38}, CALCULATE([H&T Sales Volumes (t)],_listaDatasAnoAtual),
			        _selectedMetric IN {11, 25, 39}, CALCULATE([Total Market Sales (t)],_listaDatasAnoAtual),
			        _selectedMetric IN {12, 26, 40}, CALCULATE([Faturamento],_listaDatasAnoAtual),
			        _selectedMetric IN {13, 27, 41}, CALCULATE([Preco Medio],_listaDatasAnoAtual)
			    )
			VAR _YTD_LY = 
			    SWITCH(
			        TRUE(),
			        _selectedMetric IN {0, 14, 28}, CALCULATE([Local Market Sales (t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {1, 15, 29}, CALCULATE([Cold Rolled (market Sales: Local + Export) (t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {2, 16, 30}, CALCULATE([Export Market Sales (t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {3, 17, 31}, CALCULATE([Service Sales (KBRL)],_listaDatasAnoAnterior),
			        _selectedMetric IN {4, 18, 32}, CALCULATE([Indice Insatisfação]+0,_listaDatasAnoAnterior),
			        _selectedMetric IN {5, 19, 33}, CALCULATE([Gross Profit Total (R$/t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {6, 20, 34}, CALCULATE([Gross Profit (%)],_listaDatasAnoAnterior),
			        _selectedMetric IN {7, 21, 35}, CALCULATE([Gross Profit - Cold Rolled (R$/t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {8, 22, 36}, CALCULATE([Customer Projects],_listaDatasAnoAnterior),
			        _selectedMetric IN {9, 23, 37}, CALCULATE([Coated Sales Volumes (t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {10, 24, 38},CALCULATE( [H&T Sales Volumes (t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {11, 25, 39}, CALCULATE([Total Market Sales (t)],_listaDatasAnoAnterior),
			        _selectedMetric IN {12, 26, 40}, CALCULATE([Faturamento],_listaDatasAnoAnterior),
			        _selectedMetric IN {13, 27, 41},CALCULATE( [Preco Medio],_listaDatasAnoAnterior)
			    )
			
			
			VAR _VariacaoYTD = DIVIDE(_YTD_CY,_YTD_LY)-1
			
			
			//Valores Formatados para o visual
			VAR _periodoAnterior = if(_periodo_LY="YTD","YTD("&Ano_Anterior&")",_periodo_LY)
			VAR _VariacaoYOY_Formatado = FORMAT(_VariacaoYOY,"#.00%")
			VAR _VariacaoYTD_Formatado = FORMAT(_VariacaoYTD,"#.00%")
			
			var _YOY_CY_formatado = 
			FORMAT(_YOY_CY,
			    SWITCH(
			        TRUE(),
			        _selectedMetric in {6,20,34},"#0.0%",
			        _selectedMetric in {4,18,32},"#,,,0",
			        _selectedMetric in {13,27,41},"#,,,0.000",
			        _selecaoFormato = 0, "#,,,,0",
			        _selecaoFormato = 1,
			            SWITCH(
			                TRUE(),
			                ABS( _YOY_CY) >= 1E9, "#,,,.00B",
			                ABS( _YOY_CY) >= 1E6, "#,,.00M",
			                ABS( _YOY_CY) >= 1E3, "#,.00K",
			                "#,,,0.00"
			            ),
			        _selecaoFormato = 2, "#0,K",
			        _selecaoFormato = 3, "#0,,M",
			        _selecaoFormato = 4, "#0,,,B"
			    )
			)
			
			var _YOY_LY_formatado = 
			FORMAT(_YOY_LY,
			    SWITCH(
			        TRUE(),
			        _selectedMetric in {6,20,34},"#0.0%",
			        _selectedMetric in {4,18,32},"#,,,0",
			        _selectedMetric in {13,27,41},"#,,,0.000",
			        _selecaoFormato = 0, "#,,,,0",
			        _selecaoFormato = 1,
			            SWITCH(
			                TRUE(),
			                ABS( _YOY_LY) >= 1E9, "#,,,.00B",
			                ABS( _YOY_LY) >= 1E6, "#,,.00M",
			                ABS( _YOY_LY) >= 1E3, "#,.00K",
			                "#,,,0.00"
			            ),
			        _selecaoFormato = 2, "#0,K",
			        _selecaoFormato = 3, "#0,,M",
			        _selecaoFormato = 4, "#0,,,B"
			    )
			)
			
			
			var _YTD_CY_formatado = 
			FORMAT(_YTD_CY,
			    SWITCH(
			        TRUE(),
			        _selectedMetric in {6,20,34},"#0.0%",
			        _selectedMetric in {4,18,32},"#,,,0",
			        _selectedMetric in {13,27,41},"#,,,0.000",
			        _selecaoFormato = 0, "#,,,,0",
			        _selecaoFormato = 1,
			            SWITCH(
			                TRUE(),
			                ABS( _YTD_CY) >= 1E9, "#,,,.00B",
			                ABS( _YTD_CY) >= 1E6, "#,,.00M",
			                ABS( _YTD_CY) >= 1E3, "#,.00K",
			                "#,,,0.00"
			            ),
			        _selecaoFormato = 2, "#0,K",
			        _selecaoFormato = 3, "#0,,M",
			        _selecaoFormato = 4, "#0,,,B"
			    )
			)
			
			
			var _YTD_LY_formatado = 
			FORMAT(_YTD_LY,
			    SWITCH(
			        TRUE(),
			        _selectedMetric in {6,20,34},"#0.0%",
			        _selectedMetric in {4,18,32},"#,,,0",
			        _selectedMetric in {13,27,41},"#,,,0.000",
			        _selecaoFormato = 0, "#,,,,0",
			        _selecaoFormato = 1,
			            SWITCH(
			                TRUE(),
			                ABS( _YTD_LY) >= 1E9, "#,,,.00B",
			                ABS( _YTD_LY) >= 1E6, "#,,.00M",
			                ABS( _YTD_LY) >= 1E3, "#,.00K",
			                "#,,,0.00"
			            ),
			        _selecaoFormato = 2, "#0,K",
			        _selecaoFormato = 3, "#0,,M",
			        _selecaoFormato = 4, "#0,,,B"
			    )
			)
			
			
			VAR _corPositivo = "#4C7596"
			VAR _corNegativo = "#B4404A"
			VAR _corYOY = IF(_VariacaoYOY<0,_corNegativo,_corPositivo)
			VAR _corYTD = IF(_VariacaoYTD<0,_corNegativo,_corPositivo)
			
			VAR _SetaYOY = IF(_VariacaoYOY<0,"⬇","⬆")
			VAR _SetaYTD = IF(_VariacaoYTD<0,"⬇","⬆")
			
			VAR _HTML = 
			"
			<html>
			    <body>
			        <div style='background-color:white; border-radius: 5px;'>
			            <div style='text-align:left;font-size:12px;background-color:#003A69;padding:15px; color: white; border-radius: 5px 5px 0px 0px'>"&LEFT(_metrica,45)&" - "&_periodo&"</div>
			            <div style='display: flex; flex-direction:row;padding:5px'>
			                <span style='text-align: center; width:50%'>
			                    <b>YOY</b><span style='color:"&_corYOY&";'> ("&_SetaYOY&" "&_VariacaoYOY_Formatado &")</span>
			                    <br></br>
			                    <b>"&_periodo&":</b> "&_YOY_CY_formatado &"
			                    <br></br>
			                    <b>"&_periodoAnterior&":</b>
			                    "&_YOY_LY_formatado &
			                "</span>
			                <span  style='text-align: center; width:50%''>
			                    <b>YTD</b><span style='color:"&_corYTD&";'> ("&_SetaYTD&" "&_VariacaoYTD_Formatado &")</span>
			                    <br></br>
			                    <b>CY:</b> "&IF(_periodo="YTD",_YOY_CY_formatado,_YTD_CY_formatado) &"
			                    <br></br>
			                    <b>LY:</b> "&_YTD_LY_formatado &
			                "</span>
			            </div>
			        </div>
			    </body>
			</html>
			"
			
			RETURN _HTML
			```
		isHidden
		displayFolder: HTML
		lineageTag: fd5f38e2-dc5d-493d-a2d9-0d7bb1087380

	measure 'Dummy segmento' = 0
		isHidden
		displayFolder: Dummy
		lineageTag: 2fa491b0-89c6-4a4f-99c8-ffb167c95ae0

		formatStringDefinition = SELECTEDVALUE(dArtigo[segmento])

	measure 'Dummy aplicação' = 0
		isHidden
		displayFolder: Dummy
		lineageTag: fb080b29-7a44-4b34-a581-2c0d23d505a6

		formatStringDefinition =
				Var _medida = SELECTEDVALUE(dArtigo[aplicacao])
				RETURN
				LEFT(_medida,25)

	measure 'Dummy Familia' = 0
		isHidden
		displayFolder: Dummy
		lineageTag: 965ba153-2c0c-4f87-9114-f8b4e14f8b5d

		formatStringDefinition = ```
				var familia = SELECTEDVALUE(dArtigo[familia_indg])
				var ajuste = IF(AND(len(familia)=1,CONTAINSSTRING(familia,"L"))," L.",familia) 
				RETURN
				LEFT(ajuste,25)
				```

	measure 'Dummy Cliente' = 0
		isHidden
		displayFolder: Dummy
		lineageTag: 2f88f64c-79f6-415b-89db-afa3cc5da031

		formatStringDefinition =
				var _cliente = SELECTEDVALUE(dClientes[razao_social])
				
				RETURN LEFT(_cliente,25)

	measure 'Dummy Qualidade' = 0
		isHidden
		displayFolder: Dummy
		lineageTag: 0e12754f-186e-485f-962d-efb557ddc6be

		formatStringDefinition = ```
				Var qualidade = SELECTEDVALUE(dArtigo[qualidade_bw])
				var ajuste = IF(AND(len(qualidade)=1,CONTAINSSTRING(qualidade,"L"))," L.",qualidade) 
				RETURN
				LEFT(ajuste,25)
				```

	measure 'Dummy Dinamico Segmento' = 0
		isHidden
		displayFolder: Dummy
		lineageTag: 7b908b85-59ca-4e4d-8167-bfcba9f57279

		formatStringDefinition =
				VAR _selecao = SELECTEDVALUE(pSegmentos[pSegmentos Pedido])
				RETURN
				SWITCH(
				    _selecao,
				    0,SELECTEDVALUE('dClientes'[mercado]),
				    1,SELECTEDVALUE('dGerencia'[gerente]),
				    2,SELECTEDVALUE('dArtigo'[segmento]),
				    3,SELECTEDVALUE('dArtigo'[aplicacao]),
				    4,SELECTEDVALUE('dArtigo'[familia_indg]),
				    5,SELECTEDVALUE('dArtigo'[qualidade_bw]),
				    6,SELECTEDVALUE('dClientes'[nome_abreviado]),
				    7,CONVERT(SELECTEDVALUE('dArtigo'[id_artigo_original]),STRING),
				    8,SELECTEDVALUE('dClientes'[mercado]),
				    9,SELECTEDVALUE('dGerencia'[gerente]),
				    10,SELECTEDVALUE('dArtigo'[segmento]),
				    11,SELECTEDVALUE('dArtigo'[aplicacao]),
				    12,SELECTEDVALUE('dArtigo'[familia_indg]),
				    13,SELECTEDVALUE('dArtigo'[qualidade_bw]),
				    14,SELECTEDVALUE('dClientes'[nome_abreviado]),
				    15,CONVERT(SELECTEDVALUE('dArtigo'[id_artigo_original]),STRING),
				    16,SELECTEDVALUE('dClientes'[mercado]),
				    17,SELECTEDVALUE('dGerencia'[gerente]),
				    18,SELECTEDVALUE('dArtigo'[segmento]),
				    19,SELECTEDVALUE('dArtigo'[aplicacao]),
				    20,SELECTEDVALUE('dArtigo'[familia_indg]),
				    21,SELECTEDVALUE('dArtigo'[qualidade_bw]),
				    22,SELECTEDVALUE('dClientes'[nome_abreviado]),
				    23,CONVERT(SELECTEDVALUE('dArtigo'[id_artigo_original]),STRING)
				)

	measure 'Formatacao Dinamica' = ```
			
			VAR _valor = SELECTEDMEASURE()
			Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
			var _formatoDinamico = 
			SWITCH(
			    TRUE(),
			    ABS( _valor) >= 1E9, "#,,,.00B",
			    ABS( _valor) >= 1E6, "#,,.00M",
			    ABS( _valor) >= 1E3, "#,.00K",
			    "#0.00"
			)
			
			RETURN
			
			SWITCH(
			    _selecao,
			    0, "#0.00",
			    1,_formatoDinamico,
			    2, "#,.00K",
			    3, "#,,.00M",
			    4, "#,,,.00B"
			)
			```
		isHidden
		displayFolder: Formatação
		lineageTag: 4a7281cb-7829-4bd7-8d5d-9474d0069583

	measure 'Titulo Scorecard graf_barra' = ```
			
			var _parametro = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			var _segmento = LOOKUPVALUE(pSegmentos[pSegmentos],pSegmentos[pSegmentos Pedido],SELECTEDVALUE(pSegmentos[pSegmentos Pedido]))
			VAR _selecaoMetrica = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _parametroselecionado = LOOKUPVALUE(pMetricas[Valor],pMetricas[Parâmetro Pedido],_parametro)
			VAR _conector = 
			SWITCH(
			    _selecaoIdioma,
			    1, " por ",
			    2," nach ",
			    3," by "
			)
			RETURN
			
			_parametroselecionado &_conector & _segmento
			```
		isHidden
		displayFolder: Formatação
		lineageTag: eba5cde2-46b5-4403-818a-0f44521f96eb

	measure 'Titulo Scorecard graf_coluna' =
			LOOKUPVALUE(pMetricas[Valor],pMetricas[Parâmetro Pedido],SELECTEDVALUE(pMetricas[Parâmetro Pedido]))
			/*
			 VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			RETURN
			SWITCH(
			    _selecaoIdioma,
			    1, LOOKUPVALUE(pMetricas[Valor],pMetricas[Parâmetro Pedido],SELECTEDVALUE(pMetricas[Parâmetro Pedido])),
			    2,LOOKUPVALUE(pMetricas[Valor],pMetricas[Parâmetro Pedido],SELECTEDVALUE(pMetricas[Parâmetro Pedido])),
			    3,LOOKUPVALUE(pMetricas[Valor],pMetricas[Parâmetro Pedido],SELECTEDVALUE(pMetricas[Parâmetro Pedido]))
			)
			*/
		isHidden
		displayFolder: Formatação
		lineageTag: 9d6dbbc1-aa99-4a0f-adfb-b7c44b6fe025

	measure cor_gauge_reclamacao = if([Reclamações por ton]>[MetaReclamação],"#DE7256","#003A69")
		isHidden
		displayFolder: Formatação
		lineageTag: 073809d2-4886-460f-8a52-2cdb93aa7cd4

	measure cor_bar_reclamacao = if([Reclamacoes 1000t grafico]>[Meta Reclamacao grafico],"#B4404A","#6E8582")
		isHidden
		displayFolder: Formatação
		lineageTag: f3e0e066-0379-4847-bcc8-b072d0d9fc7b

	measure 'Titulo Gráfico Segmento CSAT' =
			
			LOOKUPVALUE(
			    pSegmentos[pSegmentos],
			    pSegmentos[pSegmentos Pedido],
			    SELECTEDVALUE(pSegmentos[pSegmentos Pedido])
			    )
		isHidden
		displayFolder: Formatação
		lineageTag: d4326f65-5f14-4b09-b2df-6a96f0aeb904

	measure cor_scorecard =
			
			VAR _selectedReference = SELECTEDVALUE(Helper_referencia[Ordem])
			RETURN
			    IF(
			        _selectedReference=2,
			        IF([Scorecard_Target Para Cor]<0,"#B4404A","#A9B7A1")
			    )
		isHidden
		displayFolder: Formatação
		lineageTag: 08cf42db-cad5-44b4-a806-f5d0f27f34dd

	measure Descricao_Formato_selecionado = ```
			
			VAR _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			RETURN
			SWITCH(
			    _selecaoIdioma,
			    2,
			    SWITCH(
			        _selecao,
			        0, "Ausgewählten Werte: 'Keine Formatierung'.",
			        1, "Ausgewählten Werte: 'Dynamische Formatierung'.",
			        2, "Ausgewählten Werte: 'Tausend'.",
			        3, "Ausgewählten Werte: 'Million'.",
			        4, "Ausgewählten Werte: 'Milliarde'."
			    ),
			    3,
			    SWITCH(
			        _selecao,
			        0, "View of selected values: 'No Formatting'.",
			        1, "View of selected values: 'Dynamic Formatting'.",
			        2, "View of selected values: 'Thousand'.",
			        3, "View of selected values: 'Million'.",
			        4, "View of selected values: 'Billion'."
			    ),
			    SWITCH(
			        _selecao,
			        0, "Visualização dos valores selecionados: 'Sem Formatação'.",
			        1, "Visualização dos valores selecionados: 'Formatação dinâmica'.",
			        2, "Visualização dos valores selecionados: 'Milhar'.",
			        3, "Visualização dos valores selecionados: 'Milhão'.",
			        4, "Visualização dos valores selecionados: 'Bilhão'."
			    )
			)
			
			```
		isHidden
		displayFolder: Formatação
		lineageTag: dae808c1-145c-49c9-a2f9-5fbcd2bf60b6

	measure cor_texto_scorecard =
			
			VAR _selectedReference = SELECTEDVALUE(Helper_referencia[Ordem])
			RETURN
			    IF(
			        _selectedReference=2,
			        IF([Scorecard_Target Para Cor]<0,"#FFFFFF","#000000")
			    )
		isHidden
		displayFolder: Formatação
		lineageTag: e4d31035-2a3c-4978-a791-8b360d220a7c

	measure subtítulo_csat = ```
			
			VAR _selecao = SELECTEDVALUE(pSegmentos[pSegmentos pedido])
			VAR _coluna = LOOKUPVALUE(pSegmentos[pSegmentos],pSegmentos[pSegmentos Pedido],SELECTEDVALUE(pSegmentos[pSegmentos Pedido]))
			
			RETURN
			SWITCH(
			    SELECTEDVALUE(pIdioma[Ordem]),
			    1,
			        SWITCH(
			            TRUE(),
			            ISFILTERED(dClientes[nome_abreviado])," Insatisfações por cliente",
			            "Reclamações por "&_coluna
			        ),
			    2,
			        SWITCH(
			            TRUE(),
			            ISFILTERED(dClientes[nome_abreviado]),"Unzufriedenheiten nach kunden",
			            "Reklamationen nach "&_coluna
			        ),
			    3,
			        SWITCH(
			            TRUE(),
			            ISFILTERED(dClientes[nome_abreviado]),"Dissatisfactions by customer",
			            "Complaints by "&_coluna
			        )
			)
			
			```
		isHidden
		displayFolder: Formatação
		lineageTag: 49c72f71-fd89-4e66-9e93-324bbec39aa2

	measure 'Titulo gráfico temp Ebitda' = SELECTEDVALUE(pVisaoEBITDA[Target])
		isHidden
		displayFolder: Formatação
		lineageTag: c5dd3905-9b9b-44f3-84ca-7020056b2afa

	measure LocalMarketSales_Target =
			CALCULATE(
			    [Target Peso],
			    dClientes[mercado] = "Interno",
			    dArtigo[identificacao] = "REL"
			)
		displayFolder: Target
		lineageTag: 5e32ced4-c2b6-4ee7-93aa-a086bebe737a

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Target Peso' = SUM(fMetas_artigo[peso_target])
		displayFolder: Target
		lineageTag: 4c0ce770-68d1-410e-bbd1-9e7d8920d097

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure ExportMarketSales_Target =
			CALCULATE(
			    [Target Peso],
			    dClientes[mercado] = "Externo",
			    dArtigo[identificacao] = "REL"
			)
		displayFolder: Target
		lineageTag: a8db18bc-7d6f-47fe-a8b4-d6f08d816f88

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure TotalMarketSales_Target = [LocalMarketSales_Target] + [ExportMarketSales_Target]
		displayFolder: Target
		lineageTag: ffdc5db6-d163-4f1d-a12a-6b466e929624

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Gross Profit Total (R$/t)_Target' =
			
			CALCULATE(
			    DIVIDE(
			        SUM(fMetas_artigo[vlr_target]) - SUM(fMetas_artigo[cst_mp_target])
			        ,SUM(fMetas_artigo[peso_target])
			    )
			    ,REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL")
			)
		displayFolder: Target
		lineageTag: 739e0b3f-52ff-47a3-9116-43d6bb3a4464

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Cold Rolled_target' =
			CALCULATE(
			    [Target Peso],
			    dArtigo[rota] = "Com Laminação",
			    dArtigo[identificacao] = "REL"
			)
		displayFolder: Target
		lineageTag: 77cb4932-511a-45a8-b290-7be8f39f8bd9

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coated Sales Volume_target' =
			
			CALCULATE(
			    [Target Peso],
			    dArtigo[revestimento] <> "",
			    dArtigo[revestimento] <> "*",
			    dArtigo[identificacao] = "REL"
			)
		displayFolder: Target
		lineageTag: 690b47da-0429-47aa-a5ea-414d03d9ffaf

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'H&T Sales Volume_target' =
			
			CALCULATE(
			    [Target Peso],
			    dArtigo[temperado] <> "",
			    dArtigo[temperado] <> "*",
			    dArtigo[identificacao] = "REL"
			)
		displayFolder: Target
		lineageTag: 20ad9150-96a6-4a28-95c1-201cfdbb3b29

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TargetDinamico_scorecard = ```
			
			VAR _selecao_Meta  = VALUES(pMeta[sMeta Pedido])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			RETURN
			
			IF(0 in _selecao_Meta,
			    SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Target],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Target],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Target],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) target],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_Target],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_target (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_target],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Target],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Target],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Target],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Target],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Target]
			        )
			)
			
			```
		displayFolder: Target
		lineageTag: edbedef6-bee6-4993-a965-8702fab2e4ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Faturamento_target = SUM(fMetas_artigo[vlr_target])
		displayFolder: Target
		lineageTag: 5765da69-b7c6-488b-8e49-7234cb94ff95

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preco Medio_target' = DIVIDE(DIVIDE([Faturamento_target],[Target Peso]),1000)
		displayFolder: Target
		lineageTag: d5484815-433c-4634-b57a-8cc6f0c3de77

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.000"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.000",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Gross Profit Comercial (EBITDA)_target' = ```
			
			VAR _result = 
			DIVIDE(
			    SUM(fMetas_artigo[vlr_target]) - SUM(fMetas_artigo[cst_mp_target])
			    ,SUM(fMetas_artigo[peso_target])
			)
			RETURN 
			IF(0 IN VALUES(pMeta[sMeta Pedido]), _result)
			
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Target
		lineageTag: 9e1ab191-c13f-444f-bd7a-996f99c677db

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Gross Margin Comercial (EBITDA)_target' = ```
			
			vAR _RESULT = 
			AVERAGEX(
			    fMetas_artigo,
			    DIVIDE(fMetas_artigo[vlr_target] - fMetas_artigo[cst_mp_target],fMetas_artigo[peso_target])
			)
			RETURN BLANK()
			--IF(0 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Target
		lineageTag: 7bc94375-4c0f-4be3-9df5-309c5862f3c5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'EBITDA Comercial_target' = ```
			
			VAR _result = 
			AVERAGEX(
			    fMetas_artigo,
			    DIVIDE(fMetas_artigo[vlr_target] - fMetas_artigo[cst_mp_target],fMetas_artigo[peso_target])
			)
			
			RETURN BLANK()
			--IF(0 IN VALUES(pMeta[sMeta Pedido]), _result)
			
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Target
		lineageTag: 70c0bf2a-a625-427d-88b9-e405f58f75c4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Coated Sales Volume_Budget' =
			
			CALCULATE(
			    [Budget Peso],
			    dArtigo[revestimento] <> "",
			    dArtigo[revestimento] <> "*"
			)
		displayFolder: Budget
		lineageTag: 2f3c8fdf-457c-4e55-8025-e1156e496d1b

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Budget Peso' = SUM(fMetas_artigo[peso_Budget])
		displayFolder: Budget
		lineageTag: fa049aa7-8221-4b8c-85bf-97c6b5affb7e

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cold Rolled_Budget' =
			CALCULATE(
			    [Budget Peso],
			    dArtigo[rota] = "Com Laminação"
			)
		displayFolder: Budget
		lineageTag: 95eb3aa4-1914-4a35-9235-441d72e460c4

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExportMarketSales_Budget =
			CALCULATE(
			    [Budget Peso],
			    dClientes[mercado] = "Externo"
			)
		displayFolder: Budget
		lineageTag: dc281e01-163f-4699-8322-1397730658da

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'H&T Sales Volume_Budget' =
			
			CALCULATE(
			    [Budget Peso],
			    dArtigo[temperado] <> "*",
			    dArtigo[temperado] <> ""
			)
		displayFolder: Budget
		lineageTag: c78c4d04-e886-4d29-bc9f-7f429f9a9ac9

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LocalMarketSales_Budget =
			
			CALCULATE(
			    [Budget Peso],
			    dClientes[mercado] = "Interno"
			)
		displayFolder: Budget
		lineageTag: 264a6782-9dec-42fe-9737-7bd5db536d0d

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalMarketSales_Budget = [LocalMarketSales_Budget] + [ExportMarketSales_Budget]
		displayFolder: Budget
		lineageTag: cdfa61e5-3ab6-45ec-a99f-922401741126

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure BudgetDinamico_scorecard = ```
			
			VAR _selecao_Meta  = VALUES(pMeta[sMeta Pedido])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			RETURN
			
			IF(1 in _selecao_Meta,
			    SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Budget],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Budget],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Budget],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) budget],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_budget],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_budget (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_budget],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Budget],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Budget],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Budget],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Budget],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Budget]
			        )
			)
			
			```
		displayFolder: Budget
		lineageTag: 38c19fb7-cc98-4f2c-b238-7839f13ace20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Faturamento_budget = SUM(fMetas_artigo[vlr_budget])
		displayFolder: Budget
		lineageTag: eec3d30e-43c8-4e47-b781-191bf67e06bf

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preco Medio_budget' = DIVIDE(DIVIDE([Faturamento_budget],[budget Peso]),1000)
		displayFolder: Budget
		lineageTag: d8053516-e2eb-40b7-bfca-c4c6b5db4a2d

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Gross Profit Comercial (EBITDA)_budget' = ```
			
			VAR _result = 
			DIVIDE(
			    SUM(fMetas_artigo[vlr_budget]) - SUM(fMetas_artigo[cst_mp_budget])
			    ,SUM(fMetas_artigo[peso_budget])
			)
			
			RETURN
			IF(1 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Budget
		lineageTag: 0678201a-e161-4be3-876a-ea89d9955a34

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'EBITDA Comercial_budget' = ```
			
			VAR _result = 
			AVERAGEX(
			    fMetas_artigo,
			    DIVIDE(fMetas_artigo[vlr_budget] - fMetas_artigo[cst_mp_budget],fMetas_artigo[peso_budget])
			)
			RETURN BLANK()
			--IF(1 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Budget
		lineageTag: 080ea242-c162-4436-87b8-85f9d475e21d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Gross Margin Comercial (EBITDA)_budget' = ```
			
			VAR _result = 
			AVERAGEX(
			    fMetas_artigo,
			    DIVIDE(fMetas_artigo[vlr_budget] - fMetas_artigo[cst_mp_budget],fMetas_artigo[peso_budget])
			)
			RETURN BLANK()
			--IF(1 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Budget
		lineageTag: 47f7481e-261a-4eb9-a3a2-02260525c5ed

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Forecast Peso' = SUM(fMetas_artigo[peso_Forecast])
		displayFolder: Forecast
		lineageTag: ab545d67-9ddd-416c-ad83-7bfd91979e36

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coated Sales Volume_Forecast' =
			
			CALCULATE(
			    [Forecast Peso],
			    dArtigo[revestimento] <> "",
			    dArtigo[revestimento] <> "*"
			)
		displayFolder: Forecast
		lineageTag: 13888a8d-d5d9-4c5c-92ce-6e52bdffde71

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cold Rolled_Forecast' =
			CALCULATE(
			    [Forecast Peso],
			    dArtigo[rota] = "Com Laminação"
			)
		displayFolder: Forecast
		lineageTag: c2eed6e9-905d-4549-99a8-6ebf77102575

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExportMarketSales_Forecast =
			CALCULATE(
			    [Forecast Peso],
			    dClientes[mercado] = "Externo"
			)
		displayFolder: Forecast
		lineageTag: 0598976e-247d-48da-bb5a-8e73052f1843

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'H&T Sales Volume_Forecast' =
			
			CALCULATE(
			    [Forecast Peso],
			    dArtigo[temperado] <> "*",
			    dArtigo[temperado] <> ""
			)
		displayFolder: Forecast
		lineageTag: dd7ef96b-1db8-475a-b023-c6a1e31240c1

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LocalMarketSales_Forecast =
			CALCULATE(
			    [Forecast Peso],
			    dClientes[mercado] = "Interno"
			)
		displayFolder: Forecast
		lineageTag: f1660642-689f-42ad-9f3c-750cccbcc2cf

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalMarketSales_Forecast = [LocalMarketSales_Forecast] + [ExportMarketSales_Forecast]
		displayFolder: Forecast
		lineageTag: a178b3b0-62e6-4ad4-933e-337a07bb4d6e

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ForecastDinamico_scorecard = ```
			
			VAR _selecao_Meta  = VALUES(pMeta[sMeta Pedido])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			RETURN
			
			IF(2 in _selecao_Meta,
			    SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_forecast],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_forecast],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_forecast],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) forecast],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_forecast],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_forecast (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_forecast],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_forecast],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_forecast],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_forecast],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_forecast],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_forecast]
			        )
			)
			
			```
		displayFolder: Forecast
		lineageTag: 70a6e14b-e3b2-4ca3-98ba-d439ef9f559e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Faturamento_forecast = SUM(fMetas_artigo[vlr_forecast])
		displayFolder: Forecast
		lineageTag: c6415b57-3e01-48d7-b457-a01dde189af5

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preco Medio_forecast' = DIVIDE(DIVIDE([Faturamento_forecast],[forecast Peso]),1000)
		displayFolder: Forecast
		lineageTag: 30c70f7f-fa50-42b9-ba78-324b7138aaba

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit Comercial (EBITDA)_forecast' = ```
			
			VAR _result = 
			DIVIDE(
			    SUM(fMetas_artigo[vlr_forecast]) - SUM(fMetas_artigo[cst_mp_forecast])
			    ,SUM(fMetas_artigo[peso_forecast])
			)
			RETURN IF(2 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Forecast
		lineageTag: fcc96266-8eb8-4e86-8f5e-b71b3d6f7088

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Gross Margin Comercial (EBITDA)_forecast' = ```
			
			VAR _result = 
			AVERAGEX(
			    fMetas_artigo,
			    DIVIDE(fMetas_artigo[vlr_forecast] - fMetas_artigo[cst_mp_forecast],fMetas_artigo[peso_forecast])
			)
			RETURN  BLANK()
			--IF(2 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		displayFolder: Forecast
		lineageTag: 24dc137c-873b-4f56-95ec-1d244d58623a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EBITDA Comercial_forecast' = ```
			
			VAR _result= 
			AVERAGEX(
			    fMetas_artigo,
			    DIVIDE(fMetas_artigo[vlr_forecast] - fMetas_artigo[cst_mp_forecast],fMetas_artigo[peso_forecast])
			)
			RETURN BLANK()
			--IF(2 IN VALUES(pMeta[sMeta Pedido]), _result)
			--SUM(febtida_artigo_coml[gm_total])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Forecast
		lineageTag: 1036d480-dfca-4098-ab92-069af6858229

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Rank_segmento_overview =
			
			VAR _selecao = SELECTEDVALUE(pVisao[pVisao Pedido])
			RETURN
			IF(SELECTEDVALUE(pMelhorPior[ID])=1,
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[segmento]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                ASC BLANKS LAST
			            )
			        ),
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[segmento]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                DESC BLANKS LAST
			            )
			        )
			)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: b8d216d5-6400-434c-9e41-6bcaded43d0e

	measure Rank_Familia_overview =
			
			VAR _selecao = SELECTEDVALUE(pVisao[pVisao Pedido])
			RETURN
			IF(SELECTEDVALUE(pMelhorPior[ID])=1,
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[familia_indg]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                ASC BLANKS LAST
			            )
			        ),
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[familia_indg]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                DESC BLANKS LAST
			            )
			        )
			)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: edcb319c-abaa-4b1a-a493-1d2c829eeec0

	measure Rank_aplicacao_overview = ```
			
			VAR _selecao = SELECTEDVALUE(pVisao[pVisao Pedido])
			
			RETURN
			IF(SELECTEDVALUE(pMelhorPior[ID])=1,
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[aplicacao]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                ASC BLANKS LAST
			            )
			        ),
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[aplicacao]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                DESC BLANKS LAST
			            )
			        )
			)
			
			```
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: 18c86910-e40a-4b2d-ae1c-8f70677d84cd

	measure Rank_qualidade_overview =
			
			VAR _selecao = SELECTEDVALUE(pVisao[pVisao Pedido])
			RETURN
			IF(SELECTEDVALUE(pMelhorPior[ID])=1,
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[qualidade_bw]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                ASC BLANKS LAST
			            )
			        ),
			        RANK(
			            DENSE,
			            ALLSELECTED(dArtigo[qualidade_bw]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                DESC BLANKS LAST
			            )
			        )
			)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: 9ae189c3-daf4-4583-b9f8-75b19aac6160

	measure Rank_cliente_overview =
			
			VAR _selecao = SELECTEDVALUE(pVisao[pVisao Pedido])
			
			RETURN
			IF(SELECTEDVALUE(pMelhorPior[ID])=1,
			        RANK(
			            DENSE,
			            ALLSELECTED(dClientes[nome_abreviado]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                ASC BLANKS LAST
			            )
			        ),
			        RANK(
			            DENSE,
			            ALLSELECTED(dClientes[nome_abreviado]),
			            ORDERBY(
			                SWITCH(
			                _selecao,
			                0,[PesoFaturado],
			                1,[Faturamento],
			                2,[Preco Medio],
			                3,[Gross Profit Total (R$/t)],
			                4,[Gross Profit (%)]
			                ),
			                DESC BLANKS LAST
			            )
			        )
			)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: 75acb191-6d6c-4d26-9791-f01f76da3d46

	measure _Top_aplicacao =
			
			VAR _top = [Valor sTop]
			VAR _rank = [Rank_aplicacao_overview]
			
			RETURN
			IF(_rank <= _top, 1, 0)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: fc130e8a-43eb-4294-9b04-73af5c5d9e32

	measure _Top_segmento =
			
			VAR _top = [Valor sTop]
			VAR _rank = [Rank_segmento_overview]
			
			RETURN
			IF(_rank <= _top, 1, 0)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: 91bab7f5-9fdf-4368-bd25-f2a60d023b83

	measure _Top_familia =
			
			VAR _top = [Valor sTop]
			VAR _rank = [Rank_familia_overview]
			
			RETURN
			IF(_rank <= _top, 1, 0)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: a7648652-b20b-4328-8ff5-80d0c3e8ba25

	measure _Top_qualidade =
			
			VAR _top = [Valor sTop]
			VAR _rank = [Rank_qualidade_overview]
			
			RETURN
			IF(_rank <= _top, 1, 0)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: 71f868cb-a962-48e3-b2a8-33cf60afd96e

	measure _Top_cliente =
			
			VAR _top = [Valor sTop]
			VAR _rank = [Rank_cliente_overview]
			
			RETURN
			IF(_rank <= _top, 1, 0)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: a649534f-8051-4a8d-914c-0eb21cef38c2

	measure Rank_metricas_scorecard =
			
			VAR _selecao_metrica = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			RETURN
			SWITCH(
			    TRUE(),
			    _selecao_metrica IN {0, 14, 28}, [Local Market Sales (t)],
			    _selecao_metrica IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			    _selecao_metrica IN {2, 16, 30}, [Export Market Sales (t)],
			    _selecao_metrica IN {3, 17, 31}, [Service Sales (KBRL)],
			    _selecao_metrica IN {4, 18, 32}, [Indice Insatisfação],
			    _selecao_metrica IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			    _selecao_metrica IN {6, 20, 34}, [Gross Profit (%)],
			    _selecao_metrica IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			    _selecao_metrica IN {8, 22, 36}, [Customer Projects],
			    _selecao_metrica IN {9, 23, 37}, [Coated Sales Volumes (t)],
			    _selecao_metrica IN {10, 24, 38}, [H&T Sales Volumes (t)],
			    _selecao_metrica IN {11, 25, 39}, [Total Market Sales (t)],
			    _selecao_metrica IN {12, 26, 40}, [Faturamento],
			    _selecao_metrica IN {13, 27, 41}, [Preco Medio]
			)
		formatString: 0
		isHidden
		displayFolder: Rank_TopN
		lineageTag: 3abfee88-fda1-4e4f-8f2b-69419eebbbc0

	measure 'Faturamento YTD' =
			
			TOTALYTD(
			    [Real_Ton],
			    dCalendario[data]
			)
		isHidden
		displayFolder: Temporal
		lineageTag: b9755546-47cd-4c6b-9b79-280d09195c05

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Faturamento_target YTD' =
			
			TOTALYTD(
			    [Real_Ton Target],
			    dCalendario[data]
			)
		isHidden
		displayFolder: Temporal
		lineageTag: f2f71c89-4d72-43e0-8718-1d1fc31c5322

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Faturamento_budget YTD' =
			
			TOTALYTD(
			    [Real_Ton Budget],
			    dCalendario[data]
			)
		isHidden
		displayFolder: Temporal
		lineageTag: 0acd2b53-d81a-4914-afbc-57feec4e0e38

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Faturamento_forecast YTD' =
			
			TOTALYTD(
			    [Real_Ton Forecast],
			    dCalendario[data]
			)
		isHidden
		displayFolder: Temporal
		lineageTag: 51216c6f-7cda-4307-9f4d-038e33f4cd6b

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Index LY' = CALCULATE([Indice Insatisfação],SAMEPERIODLASTYEAR(dCalendario[data]))
		formatString: 0
		isHidden
		displayFolder: Temporal
		lineageTag: 668af886-29c1-4c4b-b762-d8587cab90ac

	measure 'Gross Profit Comercial (EBITDA)' =
			[Faturamento Líquido (EBITDA)] - [Custo materia Prima (EBITDA)]
			// AVERAGEX(
			//    febtida_artigo_coml,
			//    febtida_artigo_coml[preco_por_ton] - febtida_artigo_coml[custo_mp_c_s]
			// )
			
			// SUMX(
			//     febtida_artigo_coml,
			//     [receita_liquida] - febtida_artigo_coml[custo_mp_s_s]
			// )
			
			--SUM(febtida_artigo_coml[gm_total])
		displayFolder: EBITDA
		lineageTag: 42d9e559-1d41-4090-bde7-7273aec4df27

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Faturamento Líquido (EBITDA)' = SUM(febtida_artigo_coml[receita_liquida])
		displayFolder: EBITDA
		lineageTag: cac05209-e6db-49f9-acac-501acbaff236

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Custo materia Prima (EBITDA)' = SUM(febtida_artigo_coml[custo_mp_full])
		displayFolder: EBITDA
		lineageTag: 9b01b877-e3d6-45e9-b5e4-93d1d2eaad99

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gastos Gerais de Fabricacao GGF (EBITDA)' = SUM(febtida_artigo_coml[vlr_GGF_total])
		displayFolder: EBITDA
		lineageTag: 54294807-2cec-4403-8fd4-1e562a16d370

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Despesas Operacionais (EBITDA)' =
			
			SUMX(
			    febtida_artigo_coml,
			    febtida_artigo_coml[desp_adm]
			    + febtida_artigo_coml[desp_comissao]
			    + febtida_artigo_coml[desp_vendas]
			)
		displayFolder: EBITDA
		lineageTag: 58f5f385-7e88-4d38-83f3-ffd214f383da

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EBITDA COMERCIAL' = [EBIT Comercial] --+ [Despesas não monetárias]
		displayFolder: EBITDA
		lineageTag: 90f9eaf1-6847-4a45-811a-5b3c4624d352

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure Valor_categoria_waterfall =
			
			SWITCH(
			    SELECTEDVALUE(Helper_EBITDA[Ordem]),
			    1,[Faturamento Líquido (EBITDA)],
			    3,[Gross Profit Comercial (EBITDA)],
			    5,[Gross Margin Comercial (EBITDA)],
			    7,[EBIT Comercial],
			    9,[EBITDA COMERCIAL]
			)
		isHidden
		displayFolder: EBITDA
		lineageTag: 2fff1e61-0351-4627-b8a0-493217287199

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				
				```

	measure Base_categoria_waterfall = ```
			
			VAR _parte1 = [Faturamento Líquido (EBITDA)] - [Custo materia Prima (EBITDA)]
			VAR _parte2 = _parte1 - [Gastos Gerais de Fabricacao GGF (EBITDA)]
			VAR _parte3 = _parte2 - [Despesas Operacionais (EBITDA)]
			VAR _parte4 = [EBITDA COMERCIAL] - [Despesas não monetárias]
			RETURN
			SWITCH(
			    SELECTEDVALUE(Helper_EBITDA[Ordem]),
			    2,_parte1,
			    4,_parte2, 
			    6,_parte3,
			    8,_parte4
			)
			```
		isHidden
		displayFolder: EBITDA
		lineageTag: d46ef271-fd00-478c-b565-0fee0a685293

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Valor_Deducao_categoria_waterfall =
			
			SWITCH(
			    SELECTEDVALUE(Helper_EBITDA[Ordem]),
			    2,[Custo materia Prima (EBITDA)],
			    4,[Gastos Gerais de Fabricacao GGF (EBITDA)],
			    6,[Despesas Operacionais (EBITDA)]
			)
		isHidden
		displayFolder: EBITDA
		lineageTag: 7ea6b688-dc83-482a-a61c-a90ade70f559

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				
				```

	measure Detalhe_Waterfall =
			
			VAR _faturamento = [Faturamento Líquido (EBITDA)]
			RETURN
			SWITCH(SELECTEDVALUE(Helper_EBITDA[Ordem]),
			    2,"(" & ROUND(DIVIDE([Custo materia Prima (EBITDA)],_faturamento)*100,1) & "%)",
			    3,"(" & ROUND(DIVIDE([Gross Profit Comercial (EBITDA)],_faturamento)*100,1) & "%)",
			    4,"(" & ROUND(DIVIDE([Gastos Gerais de Fabricacao GGF (EBITDA)],_faturamento)*100,1) & "%)",
			    5,"(" & ROUND(DIVIDE([Gross Margin Comercial (EBITDA)],_faturamento)*100,1) & "%)",
			    6,"(" & ROUND(DIVIDE([Despesas Operacionais (EBITDA)],_faturamento)*100,1) & "%)",
			    7,"(" & ROUND(DIVIDE([EBIT Comercial],_faturamento)*100,1) & "%)",
			    8,"(" & ROUND(DIVIDE([Despesas não monetárias],_faturamento)*100,1) & "%)",
			    9,"(" & ROUND(DIVIDE([EBITDA COMERCIAL],_faturamento)*100,1) & "%)"
			)
		isHidden
		displayFolder: EBITDA
		lineageTag: 546e3d29-383d-4f2c-a878-c0f1dfea43f4

	measure 'perc Ating (EBITDA)' =
			
			Var _target = [Gross Profit Total (R$/t)_Target]
			VAR _gross = [Gross Profit Total (R$/t)]
			Var _verif = COALESCE(_target,_gross)
			RETURN
			DIVIDE(_gross - _verif, _verif)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: EBITDA
		lineageTag: f3186b54-152a-46cc-a408-391e5bc3694c
		dataCategory: Uncategorized

	measure 'Peso Faturado (EBITDA)' = DIVIDE(SUM(febtida_artigo_coml[Peso_faturado]),1000)
		displayFolder: EBITDA
		lineageTag: c28a5b31-6e55-46c5-9cf9-5dc47f2da9a6

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta EBITDA (EBITDA)' = DIVIDE(80,100) * [EBITDA COMERCIAL]
		displayFolder: EBITDA
		lineageTag: 5b86e88a-2517-4cdc-a497-f25ac9d95493

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				
				```

	measure FiltroAtingimento = ```
			
			VAR _padrao = SELECTEDVALUE(pBaseCorteTargetEbtida[Indice]) 
			VAR _top = DIVIDE([Valor sTop],100)
			VAR _selecao = SELECTEDVALUE(pVisaoTargetEbtida[Indice])
			RETURN
			IF(_padrao= 0,
			    SWITCH(
			        _selecao,
			            0, 1,
			            1, IF([perc Ating (EBITDA)]>=0,1,0),
			            2, IF([perc Ating (EBITDA)]<0,1,0)
			    ),
			    SWITCH(
			        _selecao,
			            0, IF(ABS([perc Ating (EBITDA)])>=_top,1,0),
			            1, IF([perc Ating (EBITDA)]>=_top,1,0),
			            2, IF([perc Ating (EBITDA)]*(-1)>=_top,1,0)
			    )
			)
			```
		formatString: 0
		isHidden
		displayFolder: EBITDA
		lineageTag: d480825f-1617-46ed-99a4-c071172814b1

	measure 'Despesas não monetárias' = 0
		displayFolder: EBITDA
		lineageTag: 864a978f-74e4-4f84-90d4-257aca78a5b7

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Margin Comercial (EBITDA)' = [Gross Profit Comercial (EBITDA)] - [Gastos Gerais de Fabricacao GGF (EBITDA)]
		displayFolder: EBITDA
		lineageTag: f057dc36-db70-43a8-bffc-dc55ad30fbb3

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EBIT Comercial' = [Gross Margin Comercial (EBITDA)] - [Despesas Operacionais (EBITDA)] - [Frete (EBITDA)]
		displayFolder: EBITDA
		lineageTag: 4a022af0-17e2-45e6-ad55-3571403797eb

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure aumentar_categoria_waterfall =
			
			SWITCH(
			    SELECTEDVALUE(Helper_EBITDA[Ordem]),
			    8,[Despesas não monetárias]
			)
		isHidden
		displayFolder: EBITDA
		lineageTag: eb88d289-7c9e-490c-92b4-d97f1039c97f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reclamações por ton' =
			
			VAR _qtd = [Reclamações Validas]
			VAR _tons = DIVIDE(CALCULATE([PesoFaturado],dArtigo[identificacao] = "REL" ),1000)
			RETURN
			DIVIDE(_qtd,_tons)
		displayFolder: Reclamação e CSAT
		lineageTag: 285d9fce-0301-4709-89b3-8200ff01833d

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure MetaReclamação = ```
			
			VAR _Ano = YEAR(MAX(dCalendario[data]))
			
			RETURN 
			MAXX(fMetas_Reclamacao,fMetas_Reclamacao[Meta])
			--LOOKUPVALUE(fMetas_Reclamacao[Meta],fMetas_Reclamacao[Ano],_Ano)
			```
		displayFolder: Reclamação e CSAT
		lineageTag: 513dd006-5e67-4161-8571-c97a57da0aa0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reclamações Validas' =
			
			CALCULATE(
			    [Reclamações],
			    dDecisao_reclamacao[id_decisao] <> 1
			)
		displayFolder: Reclamação e CSAT
		lineageTag: e727929c-5dd0-4bf4-be3f-4b7585db8841

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,B",
				    ABS( _valor) >= 1E6, "#,,M",
				    ABS( _valor) >= 1E3, "#,K",
				    "#,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0",
				    1,_formatoDinamico,
				    2, "#,K",
				    3, "#,,M",
				    4, "#,,,B"
				)
				```

	measure Reclamações = ```
			
			 CALCULATE(
			    COUNTROWS(VALUES(fReclamacao[id_reclamacao])),
			    fReclamacao[tipo_reclamacao] in VALUES(ptiposegmentacao[Parâmetro Campos]),
			    dArtigo[identificacao] = "REL"
			)
			/*
			Antes de passar no dax optimizer
			
			VAR _tab = 
			CALCULATETABLE(
			    fReclamacao, 
			    fReclamacao[tipo_reclamacao] in VALUES(ptiposegmentacao[Parâmetro Campos]),
			    dArtigo[identificacao] = "REL"
			    )
			VAR _Calculo = 
			CALCULATE(
			   DISTINCTCOUNT(fReclamacao[id_reclamacao]),
			   -- COUNTROWS(fReclamacao),
			   _tab
			)
			
			RETURN
			_Calculo 
			*/
			
			
			```
		formatString: 0
		displayFolder: Reclamação e CSAT
		lineageTag: f3d73f7a-1f92-466a-9837-3cf23b1d947a

	measure '% insat vs LY' =
			
			VAR _indexLY = [Index LY]
			RETURN
			DIVIDE([Indice Insatisfação]-_indexLY,_indexLY)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Reclamação e CSAT
		lineageTag: e61722ef-8725-41bb-9c3a-ce9948e4e875

	measure 'Qtd. Clientes Insatisfeitos' =
			
			VAR _calculo =
			SWITCH(
			    TRUE(),
			    ISINSCOPE(dClientes[nome_abreviado]),[Indice Insatisfação],
			    [Reclamações]
			)
			RETURN
			If(_calculo,_calculo)
			// COUNTROWS(
			//     FILTER(
			//         ADDCOLUMNS(
			//             VALUES(dClientes[id_cliente]),
			//             "@insat", [Indice Insatisfação]
			//         ),[@insat]>0
			//     )
			// )
		displayFolder: Reclamação e CSAT
		lineageTag: 640db423-9ecd-42c0-a2d9-144fc5d63ca7

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Qtd. Clientes' = DISTINCTCOUNT(dClientes[id_cliente])
		displayFolder: Reclamação e CSAT
		lineageTag: 550dc47a-9aa9-4b7f-83a2-f1aa3eeceba2

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Quantidade Clientes Novos' = ```
			
			VAR _tabDatas = 
			ADDCOLUMNS(
			    VALUES(dCalendario[data]),
			    "@qtd_novos",
			    VAR _data = dCalendario[data]
			    RETURN
			    COUNTROWS(CALCULATETABLE(dClientes,dClientes[PrimeiraCompra] = _data))
			)
			RETURN
			SUMX(_tabDatas,[@qtd_novos])
			```
		formatString: 0
		displayFolder: Reclamação e CSAT
		lineageTag: a49622f6-6ae3-4337-9d3c-184d7af7fb2a

	measure 'Quantidade Clientes Perdidos' = ```
			
			VAR _tabDatas = 
			ADDCOLUMNS(
			    VALUES(dCalendario[data]),
			    "@qtd_perdidos",
			    VAR _data = dCalendario[data]
			    RETURN
			    COUNTROWS(CALCULATETABLE(dClientes,dClientes[UltimaCompra] = _data,dClientes[Ordem]=4))
			)
			RETURN
			SUMX(_tabDatas,[@qtd_perdidos])
			```
		formatString: 0
		displayFolder: Reclamação e CSAT
		lineageTag: 4389ea3f-8f34-416c-b0db-781fa7ecfb6a

	measure Dias_ultima_Compra =
			
			VAR _UltimaCompra = CALCULATE(MAX(fFaturamento[data_pedido]),ALL(dCalendario[data]))
			VAR _today = TODAY()
			RETURN
			DATEDIFF(_UltimaCompra,_today,DAY)
		displayFolder: Reclamação e CSAT
		lineageTag: a413843d-3359-4a64-9895-41ccbbc37761

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Max_Medidor = MAX([Meta Reclamacao grafico],[Reclamacoes 1000t grafico])*1.5
		isHidden
		displayFolder: Reclamação e CSAT
		lineageTag: df51f67f-f9ed-49d7-99f6-5c3a17a54ec0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'INsatisfações tabela' =
			
			VAR _selecao = SELECTEDVALUE(pSegmentos[pSegmentos Pedido])
			VAR _nota = [Indice Insatisfação]
			RETURN
			IF(_selecao in {0,1,6,8,9,14,16,17,22},_nota,BLANK())
		formatString: 0
		isHidden
		displayFolder: Reclamação e CSAT
		lineageTag: 6bbd821d-813c-479e-a52f-04e64a3cb3b9

	measure 'Scorecard_Target Para Cor' = ```
			
			VAR _selectedPeriod = SELECTEDVALUE(Helper_Scorecard[mes_ano_abreviado])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			VAR _datasYTD = DATESYTD(dCalendario[data])
			RETURN
			If(_selectedPeriod ="YTD",
			    VAR _Target = 
			    CALCULATE(
			        SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Target],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Target],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Target],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) target],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_Target],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_target (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_target],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Target],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Target],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Target],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Target],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Target]
			        ),_datasYTD
			    )
			    VAR _invoiced = 
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),_datasYTD
			    )
			    VAR _variacao = DIVIDE(_invoiced,_Target)-1
			
			    RETURN if(ISBLANK(_invoiced),BLANK(),_variacao)
			    ,
			    VAR _Target = 
			    CALCULATE(
			        SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Target],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Target],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Target],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) target],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_Target],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_target (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_target],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Target],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Target],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Target],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Target],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Target]
			        ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			    VAR _invoiced = 
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			    VAR _variacao = DIVIDE(_invoiced,_Target)-1
			
			    RETURN if(ISBLANK(_invoiced),BLANK(),_variacao)
			)
			```
		isHidden
		displayFolder: Scorecard
		lineageTag: abd4bd66-66b8-4240-b471-cea2727367a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Budget = ```
			
			VAR _datasYTD = DATESYTD(dCalendario[data])
			VAR _selectedPeriod = SELECTEDVALUE(Helper_Scorecard[mes_ano_abreviado])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			VAR _selectedReference = SELECTEDVALUE(Helper_referencia[Ordem])
			Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
			
			RETURN
			If(_selectedPeriod ="YTD",
			    VAR _budget = 
			    CALCULATE(
			        SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Budget],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Budget],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Budget],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) budget],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_budget],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_budget (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_budget],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Budget],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Budget],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Budget],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Budget],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Budget]
			        ),
			        _datasYTD
			    )
			    VAR _invoiced = 
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),
			        _datasYTD
			    )
			    VAR _variacao = DIVIDE(_invoiced,_budget)-1
			    VAR _emoji = IF(_variacao<0,"☹︎","☺")
			    VAR _valor = _budget
			    VAR _formatoDinamico = 
			        FORMAT(_valor,
			            SWITCH(
			            _selecao,
			            0, "#,,,0",
			            1,SWITCH(
			                    TRUE(),
			                    ABS( _valor) >= 1E9, "#0,,,B",
			                    ABS( _valor) >= 1E6, "#0,,M",
			                    ABS( _valor) >= 1E3, "#0,K",
			                    "#,,,0"
			                ),
			            2, "#0,K",
			            3, "#0,,M",
			            4, "#0,,,B"
			        ))
			    VAR _Texto =
			        SWITCH(TRUE(),
			            _selectedMetric in {6,20,34},FORMAT(_valor,"#0.0%"),
			            _selectedMetric in {4,18,32},FORMAT(_valor,"#,,,0"),
			            _selectedMetric in {13,27,41},FORMAT(_valor,"#,,,0.000"),
			            _formatoDinamico
			        )&UNICHAR(10)&"("&FORMAT(_variacao,"0.0%")&_emoji&")"
			    
			    RETURN if(ISBLANK(_invoiced),BLANK(),_Texto)
			    ,
			    VAR _budget = 
			    CALCULATE(
			        SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Budget],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Budget],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Budget],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) budget],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_budget],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_budget (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_budget],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Budget],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Budget],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Budget],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Budget],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Budget]
			        ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			    VAR _invoiced = 
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			    VAR _valor = _budget
			    VAR _variacao = DIVIDE(_invoiced,_budget)-1
			    vAR _formatoDinamico = 
			        FORMAT(_valor,
			            SWITCH(
			            _selecao,
			            0, "#,,,0",
			            1,SWITCH(
			                    TRUE(),
			                    ABS( _valor) >= 1E9, "#0,,,B",
			                    ABS( _valor) >= 1E6, "#0,,M",
			                    ABS( _valor) >= 1E3, "#0,K",
			                    "#,,,0"
			                ),
			            2, "#0,K",
			            3, "#0,,M",
			            4, "#0,,,B"
			        ))
			
			    VAR _emoji = IF(_variacao<0,"☹︎","☺")
			    VAR _Texto =
			        SWITCH(TRUE(),
			            _selectedMetric in {6,20,34},FORMAT(_valor,"#0.0%"),
			            _selectedMetric in {4,18,32},FORMAT(_valor,"#,,,0"),
			            _selectedMetric in {13,27,41},FORMAT(_valor,"#,,,0.000"),
			            _formatoDinamico
			        ) &UNICHAR(10)&"("&FORMAT(_variacao,"0.0%")&_emoji&")"
			    RETURN if(ISBLANK(_invoiced),BLANK(),_Texto)
			)
			```
		isHidden
		displayFolder: Scorecard
		lineageTag: 181a6456-5a82-45b9-8923-cf9efe315ccc

	measure Scorecard_Target = ```
			
			VAR _datasYTD = DATESYTD(dCalendario[data])
			VAR _selectedPeriod = SELECTEDVALUE(Helper_Scorecard[mes_ano_abreviado])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			VAR _selectedReference = SELECTEDVALUE(Helper_referencia[Ordem])
			Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
			RETURN
			If(_selectedPeriod ="YTD",
			    VAR _Target = 
			    CALCULATE(
			        SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Target],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Target],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Target],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) target],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_Target],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_target (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_target],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Target],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Target],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Target],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Target],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Target]
			        ),_datasYTD
			    )
			    VAR _invoiced = 
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),_datasYTD
			    )
			    VAR _variacao = DIVIDE(_invoiced,_Target)-1
			    VAR _emoji = IF(_variacao<0,"☹︎","☺")
			    VAR _valor = _target
			    VAR _formatoDinamico = 
			        FORMAT(_valor,
			            SWITCH(
			            _selecao,
			            0, "#,,,0",
			            1,SWITCH(
			                    TRUE(),
			                    ABS( _valor) >= 1E9, "#0,,,B",
			                    ABS( _valor) >= 1E6, "#0,,M",
			                    ABS( _valor) >= 1E3, "#0,K",
			                    "#,,,0"
			                ),
			            2, "#0,K",
			            3, "#0,,M",
			            4, "#0,,,B"
			        ))
			    VAR _Texto =
			        SWITCH(TRUE(),
			            _selectedMetric in {6,20,34},FORMAT(_valor,"#0.0%"),
			            _selectedMetric in {4,18,32},FORMAT(_valor,"#,,,0"),
			            _selectedMetric in {13,27,41},FORMAT(_valor,"#,,,0.000"),
			            _formatoDinamico
			        )&UNICHAR(10)&"("&FORMAT(_variacao,"0.0%")&_emoji&")"
			    RETURN IF(ISBLANK(_invoiced),BLANK(),_Texto)
			    ,
			    VAR _Target = 
			    CALCULATE(
			        SWITCH(
			            TRUE(),
			            _selectedMetric IN {0, 14, 28}, [LocalMarketSales_Target],
			            _selectedMetric IN {1, 15, 29}, [Cold Rolled_Target],
			            _selectedMetric IN {2, 16, 30}, [ExportMarketSales_Target],
			            _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL) target],
			            _selectedMetric IN {4, 18, 32}, IF([Indice Insatisfação], 0),
			            _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)_Target],
			            _selectedMetric IN {6, 20, 34}, [GrossProfit_target (%)],
			            _selectedMetric IN {7, 21, 35}, [Gross Profit cold rolled (R$/t)_target],
			            _selectedMetric IN {8, 22, 36}, [Customer Projects],
			            _selectedMetric IN {9, 23, 37}, [Coated Sales Volume_Target],
			            _selectedMetric IN {10, 24, 38}, [H&T Sales Volume_Target],
			            _selectedMetric IN {11, 25, 39}, [TotalMarketSales_Target],
			            _selectedMetric IN {12, 26, 40}, [Faturamento_Target],
			            _selectedMetric IN {13, 27, 41}, [Preco Medio_Target]
			        ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			    VAR _invoiced = 
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			    VAR _variacao = DIVIDE(_invoiced,_Target)-1
			    VAR _emoji = IF(_variacao<0,"☹︎","☺")
			    VAR _valor = _Target
			    VAR _formatoDinamico = 
			        FORMAT(_valor,
			            SWITCH(
			            _selecao,
			            0, "#,,,0",
			            1,SWITCH(
			                    TRUE(),
			                    ABS( _valor) >= 1E9, "#0,,,B",
			                    ABS( _valor) >= 1E6, "#0,,M",
			                    ABS( _valor) >= 1E3, "#0,K",
			                    "#,,,0"
			                ),
			            2, "#0,K",
			            3, "#0,,M",
			            4, "#0,,,B"
			        ))
			    VAR _Texto =
			        SWITCH(TRUE(),
			            _selectedMetric in {6,20,34},FORMAT(_valor,"#0.0%"),
			            _selectedMetric in {4,18,32},FORMAT(_valor,"#,,,0"),
			            _selectedMetric in {13,27,41},FORMAT(_valor,"#,,,0.000"),
			            _formatoDinamico
			        )&UNICHAR(10)&"("&FORMAT(_variacao,"0.0%")&_emoji&")"
			    RETURN IF(ISBLANK(_invoiced),BLANK(),_Texto)
			)
			```
		isHidden
		displayFolder: Scorecard
		lineageTag: ffa6e64c-b428-4ea6-8660-bb31feae070f

	measure Scorecard_Invoiced = ```
			
			VAR _selectedPeriod = SELECTEDVALUE(Helper_Scorecard[mes_ano_abreviado])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			VAR _selectedReference = SELECTEDVALUE(Helper_referencia[Ordem])
			
			RETURN
			If(_selectedPeriod ="YTD",
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação]+0,
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),
			        DATESYTD(dCalendario[data])
			    ),
			    
			    CALCULATE(
			        SWITCH(
			                TRUE(),
			                _selectedMetric IN {0, 14, 28}, [Local Market Sales (t)],
			                _selectedMetric IN {1, 15, 29}, [Cold Rolled (market Sales: Local + Export) (t)],
			                _selectedMetric IN {2, 16, 30}, [Export Market Sales (t)],
			                _selectedMetric IN {3, 17, 31}, [Service Sales (KBRL)],
			                _selectedMetric IN {4, 18, 32}, [Indice Insatisfação],
			                _selectedMetric IN {5, 19, 33}, [Gross Profit Total (R$/t)],
			                _selectedMetric IN {6, 20, 34}, [Gross Profit (%)],
			                _selectedMetric IN {7, 21, 35}, [Gross Profit - Cold Rolled (R$/t)],
			                _selectedMetric IN {8, 22, 36}, [Customer Projects],
			                _selectedMetric IN {9, 23, 37}, [Coated Sales Volumes (t)],
			                _selectedMetric IN {10, 24, 38}, [H&T Sales Volumes (t)],
			                _selectedMetric IN {11, 25, 39}, [Total Market Sales (t)],
			                _selectedMetric IN {12, 26, 40}, [Faturamento],
			                _selectedMetric IN {13, 27, 41}, [Preco Medio]
			            ),
			        KEEPFILTERS(dCalendario[mes_ano_abreviado] = _selectedPeriod)
			    )
			) 
			```
		isHidden
		displayFolder: Scorecard
		lineageTag: 8b030cee-1063-4a64-a640-f1002e683fbc

		formatStringDefinition = [Formatacao Dinamica]

	measure Scorecard_table = ```
			
			VAR _selectedReference = SELECTEDVALUE(Helper_referencia[Ordem])
			VAR _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
			VAR _selectedMetric = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			RETURN
			    SWITCH(
			        _selectedReference,
			        0,[Scorecard_Budget],
			        1,[Scorecard_Target],
			        2,
			            VAR _valor = [Scorecard_Invoiced]
			            var _formatoDinamico = 
			                SWITCH(
			                    TRUE(),
			                    ABS( _valor) >= 1E9, "#0,,,B",
			                    ABS( _valor) >= 1E6, "#0,,M",
			                    ABS( _valor) >= 1E3, "#0,K",
			                    "#,,,0"
			                )
			
			                RETURN
			                IF(_valor,
			                    FORMAT(_valor,
			                        SWITCH(
			                            TRUE(),
			                            _selectedMetric in {6,20,34},"#0.0%",
			                            _selectedMetric in {4,18,32},"#,,,0",
			                            _selectedMetric in {13,27,41},"#,,,0.000",
			                            _selecao = 0, "#,,,,0",
			                            _selecao = 1,_formatoDinamico,
			                            _selecao = 2, "#0,K",
			                            _selecao = 3, "#0,,M",
			                            _selecao = 4, "#0,,,B"
			                        )
			                    )
			                )
			        )
			```
		isHidden
		displayFolder: Scorecard
		lineageTag: 19483320-653e-426c-b7d3-caa9a8380908

	measure 'Tooltip Waterfall' = ```
			
			//Parâmetros para filtos nas medidas
			VAR _selecao = SELECTEDVALUE(Helper_EBITDA[Ordem])
			VAR _selecaoFormato = SELECTEDVALUE(pFormato[sFormato Pedido])
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _metrica = 
			SWITCH(_selecaoIdioma,
			        1,SWITCH(
			            _selecao,
			            1,"Faturamento",
			            2,"Custo MP",
			            3,"Lucro Bruto",
			            4,"GGF",
			            5,"Margem Bruta",
			            6,"Despesas Op.",
			            9,"EBITDA C."
			        ),
			        3,SWITCH(
			            _selecao,
			            1,"Revenue",
			            2,"Raw Material Cost",
			            3,"Gross Profit",
			            4,"Industrial Cost",
			            5,"Gross Margin",
			            6,"Op. Expenses",
			            9,"EBITDA C."
			        ),
			        2,SWITCH(
			            _selecao,
			            1,"Nettoumsatz",
			            2,"Materialkosten",
			            3,"Bruttogewinn",
			            4,"Herstellkosten",
			            5,"Bruttomarge",
			            6,"Betriebskosten",
			            9,"EBITDA K."
			        )
			)
			
			VAR _ValorMetrica = 
			SWITCH(
			    _selecao,
			    1,[Faturamento Líquido (EBITDA)],
			    2,[Custo materia Prima (EBITDA)],
			    3,[Gross Profit Comercial (EBITDA)],
			    4,[Gastos Gerais de Fabricacao GGF (EBITDA)],
			    5,[Gross Margin Comercial (EBITDA)],
			    6,[Despesas Operacionais (EBITDA)],
			    7,[EBIT Comercial],
			    8,[Despesas não monetárias],
			    9,[EBITDA COMERCIAL]
			) 
			
			var _ValorMetrica_formatado = 
			FORMAT(_ValorMetrica,
			    SWITCH(
			        _selecaoFormato,
			        0, "#,,,0",
			        1,SWITCH(
			                TRUE(),
			                ABS( _ValorMetrica) >= 1E9, "#,,,.00B",
			                ABS( _ValorMetrica) >= 1E6, "#,,.00M",
			                ABS( _ValorMetrica) >= 1E3, "#,.00K",
			                "#0.00"
			            ),
			        2, "#,.00K",
			        3, "#,,.00M",
			        4, "#,,,.00B"
			    )
			)
			VAR _corPositivo = "#4C7596"
			
			
			VAR _HTML = 
			"
			<html>
			    <body>
			        <div style='background-color:white; border-radius: 5px;'>
			            <div style='text-align:left;font-size:10px;background-color:#003A69;padding:5px; color: white; border-radius: 5px 5px 0px 0px'>"&_metrica&"</div>
			            <div style='display: flex; flex-direction:row;padding:5px'>
			                <span style='text-align: center; width:50%'>
			                    <b></b><span style='color:"&_corPositivo&"; text-align: center; margin: 0px 0px 0px 30px '> "&_ValorMetrica_formatado& "" &[Detalhe_Waterfall] &"</span>
			                </span>
			            </div>
			        </div>
			    </body>
			</html>
			"
			
			RETURN _metrica&UNICHAR(10)&_ValorMetrica_formatado& " " &[Detalhe_Waterfall]
			```
		isHidden
		displayFolder: HTML
		lineageTag: 983b099c-f262-4312-932f-85e155aa0cb0

	measure Noblank_p_visao =
			
			VAR _selecao = SELECTEDVALUE(pVisao[pVisao Pedido])
			RETURN
			SWITCH(
			    _selecao,
			    0,IF(ISBLANK([PesoFaturado]),0,1),
			    1,IF(ISBLANK([Faturamento]),0,1),
			    2,IF(ISBLANK([Preco Medio]),0,1),
			    3,IF(ISBLANK([Gross Profit Total (R$/t)]),0,1),
			    4,IF(ISBLANK([Gross Profit (%)]),0,1)
			)
		formatString: 0
		isHidden
		displayFolder: Formatação
		lineageTag: f3b74259-6bea-4b3f-96f2-5958d2d37b09

	measure Noblank_p_metricas = ```
			
			VAR _selecao = SELECTEDVALUE(pMetricas[Parâmetro Pedido])
			RETURN
			SWITCH(
			    TRUE(),
			    _selecao IN {0, 14, 28}, IF(ISBLANK([Local Market Sales (t)]), 0, 1),
			    _selecao IN {1, 15, 29}, IF(ISBLANK([Cold Rolled (market Sales: Local + Export) (t)]), 0, 1),
			    _selecao IN {2, 16, 30}, IF(ISBLANK([Export Market Sales (t)]), 0, 1),
			    _selecao IN {3, 17, 31}, IF(ISBLANK([Service Sales (KBRL)]), 0, 1),
			    _selecao IN {4, 18, 32}, IF(ISBLANK([Quantidade de deméritos]), 0, 1),
			    _selecao IN {5, 19, 33}, IF(ISBLANK([Gross Profit Total (R$/t)]), 0, 1),
			    _selecao IN {6, 20, 34}, IF(ISBLANK([Gross Profit (%)]), 0, 1),
			    _selecao IN {7, 21, 35}, IF(ISBLANK([Gross Profit - Cold Rolled (R$/t)]), 0, 1),
			    _selecao IN {8, 22, 36}, IF(ISBLANK([Customer Projects]), 0, 1),
			    _selecao IN {9, 23, 37}, IF(ISBLANK([Coated Sales Volumes (t)]), 0, 1),
			    _selecao IN {10, 24, 38}, IF(ISBLANK([H&T Sales Volumes (t)]), 0, 1),
			    _selecao IN {11, 25, 39}, IF(ISBLANK([Total Market Sales (t)]), 0, 1),
			    _selecao IN {12, 26, 40}, IF(ISBLANK([Faturamento]), 0, 1),
			    _selecao IN {13, 27, 41}, IF(ISBLANK([Preco Medio]), 0, 1)
			)
			
			```
		formatString: 0
		isHidden
		displayFolder: Formatação
		lineageTag: 90e88e3b-ca85-4e90-8dfb-02eae86cbf01

	measure 'Faturamento por tonelada' = ```
			
			CALCULATE(
			    DIVIDE([Faturamento],[PesoFaturado])
			    ,REMOVEFILTERS(dArtigo[identificacao])
			    ,KEEPFILTERS(dArtigo[identificacao] = "REL")
			    ) 
			```
		displayFolder: Geral
		lineageTag: e9bf0dde-88c7-4f62-b1b2-2b747a09a95e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Devoluções (qtd)' =
			
			CALCULATE(
			    COUNTROWS(DISTINCT(fDevolucao)),
			    dMotivoDevolucao[descr_motivdev] in VALUES(ptiposegmentacao[Parâmetro Campos])
			)
		formatString: 0
		displayFolder: Geral
		lineageTag: c99af537-09fe-4260-9cb5-735edad8d79d

	measure 'Devoluções(qtd) Técnica' =
			
			CALCULATE(
			    [Devoluções (qtd)],
			    dMotivoDevolucao[id_motivodev] = 2
			)
		formatString: 0
		displayFolder: Geral
		lineageTag: 7dac1ebf-f0aa-460b-85d9-026f7b88b859

	measure 'Devoluções(qtd) Comercial' =
			
			CALCULATE(
			    [Devoluções (qtd)],
			    dMotivoDevolucao[id_motivodev] = 1
			)
		formatString: 0
		displayFolder: Geral
		lineageTag: 0bc7cdc7-b9cf-4283-8a2a-d073af4e9010

	measure 'Devoluções(qtd) Logística' =
			
			CALCULATE(
			    [Devoluções (qtd)],
			    dMotivoDevolucao[id_motivodev] = 3
			)
		formatString: 0
		displayFolder: Geral
		lineageTag: d432c25c-cd6e-4265-b77e-164e3e2a7db7

	measure subtítulo_csat_cliente_perdido = ```
			
			VAR _selecao = SELECTEDVALUE(pSegmentos[pSegmentos pedido])
			
			RETURN
			SWITCH(
			    SELECTEDVALUE(pIdioma[Ordem]),
			    1,"Perdido: cliente cujo a última compra foi a mais de 60 dias",
			    2,"Verloren: Kunde, dessen letzter Kauf vor mehr als 60 Tagen war",
			    3,"Lost: customer whose last purchase was more than 60 days ago"
			)
			
			```
		isHidden
		displayFolder: Formatação
		lineageTag: cc6ae55a-19fa-44f9-b821-8adaab226628

	measure data_selecionada = ```
			
			VAR _min = MIN(dCalendario[data])
			VAR _max = MAX(dCalendario[data])
			RETURN
			SWITCH(
			    SELECTEDVALUE(pIdioma[Ordem]),
			    1,"Período selecionado: "&_min&" até "&_max,
			    2,"Ausgewählter Zeitraum: "&_min&" bis "&_max,
			    3,"Selected period: "&_min&" to "&_max
			)
			
			```
		isHidden
		displayFolder: Atualização
		lineageTag: 0ff267b1-a3b6-40ba-bd64-d4d8769f0ffe

	measure 'Gross Profit Total (R$/t)_forecast' =
			
			CALCULATE(
			    DIVIDE(
			        SUM(fMetas_artigo[vlr_forecast]) - SUM(fMetas_artigo[cst_mp_forecast])
			        ,SUM(fMetas_artigo[peso_forecast])
			    ),REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL")
			)
		displayFolder: Forecast
		lineageTag: 69c03bc0-fb98-4a8f-874c-7af5282e27c3

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'Gross Profit Total (R$/t)_budget' =
			
			CALCULATE(
			    DIVIDE(
			        SUM(fMetas_artigo[vlr_budget]) - SUM(fMetas_artigo[cst_mp_budget])
			        ,SUM(fMetas_artigo[peso_budget])
			    )
			    ,REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL")
			)
		displayFolder: Budget
		lineageTag: 857594d3-5e3d-43e9-bf6b-63a19573d902

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

	measure 'GrossProfit_target (%)' =
			
			CALCULATE(
			    DIVIDE(
			        [Gross Profit Total (R$/t)_Target],
			        DIVIDE(SUM(fMetas_artigo[vlr_target]),SUM(fMetas_artigo[peso_target]))
			    ),REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL")
			 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Target
		lineageTag: aeba10d4-ee17-4e02-90cd-ac481b7979f6

	measure 'GrossProfit_budget (%)' =
			
			CALCULATE(
			    DIVIDE(
			        [Gross Profit Total (R$/t)_budget],
			        DIVIDE(SUM(fMetas_artigo[vlr_budget]),SUM(fMetas_artigo[peso_budget]))
			    )
			    ,REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL")
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Budget
		lineageTag: 271dcd5e-537c-411b-ab85-1d7d6736c9dc

	measure 'GrossProfit_forecast (%)' =
			
			CALCULATE(
			    DIVIDE(
			        [Gross Profit Total (R$/t)_forecast],
			        DIVIDE(SUM(fMetas_artigo[vlr_forecast]),SUM(fMetas_artigo[peso_forecast]))
			    )
			    ,REMOVEFILTERS(dArtigo[identificacao]),KEEPFILTERS(dArtigo[identificacao]="REL")
			 )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: fb2203bd-e8d3-46e7-a841-de51560a2756

	measure 'Service Sales (KBRL) budget' =
			
			CALCULATE(
			    DIVIDE(SUM(fMetas_artigo[vlr_budget]),1000),
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] IN {"M.Obra","MO Decap"})
			    )
		displayFolder: Budget
		lineageTag: 3a1935fb-8a3d-468b-8b5a-414bc34405ad

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Sales (KBRL) target' =
			
			CALCULATE(
			    DIVIDE(SUM(fMetas_artigo[vlr_target]),1000),
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] IN {"M.Obra","MO Decap"})
			    )
		displayFolder: Target
		lineageTag: 82b88373-cb3f-4d8d-a2ba-6b102b35f271

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Sales (KBRL) forecast' =
			
			CALCULATE(
			    DIVIDE(SUM(fMetas_artigo[vlr_forecast]),1000),
			    REMOVEFILTERS(dArtigo[identificacao]),
			    KEEPFILTERS(dArtigo[identificacao] IN {"M.Obra","MO Decap"})
			    )
		displayFolder: Forecast
		lineageTag: ec0a3188-8b13-4e5f-8455-5dca29d74803

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit cold rolled (R$/t)_budget' =
			
			CALCULATE(
			    [Gross Profit Total (R$/t)_budget],
			    dArtigo[rota] = "Com Laminação"
			)
		displayFolder: Budget
		lineageTag: c9a3d4eb-9fbc-4a31-95d4-a7c586d65057

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit cold rolled (R$/t)_target' =
			
			CALCULATE(
			    [Gross Profit Total (R$/t)_target],
			    dArtigo[rota] = "Com Laminação"
			)
		displayFolder: Target
		lineageTag: a201ec0a-425b-4294-b2b2-4aa1df22e0c7

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit cold rolled (R$/t)_forecast' =
			
			CALCULATE(
			    [Gross Profit Total (R$/t)_forecast],
			    dArtigo[rota] = "Com Laminação"
			)
		displayFolder: Forecast
		lineageTag: 4e8a65ae-4f61-41fe-8e30-5968c4f484c4

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0.00",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit (%)' = DIVIDE([Gross Profit Total (R$/t)], [Faturamento por tonelada])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPIs
		lineageTag: 329c7701-31ab-4b43-9a4d-65983761b91d

	measure 'Frete (EBITDA)' = SUM(febtida_artigo_coml[desp_frete])
		displayFolder: EBITDA
		lineageTag: 0fd2769b-bfaa-4b5d-abff-2f5bf8b49a4d

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit Comercial (EBITDA) por tonelada' = DIVIDE([Gross Profit Comercial (EBITDA)],[Peso Faturado (EBITDA)])
		displayFolder: EBITDA
		lineageTag: 8918a198-c17c-4388-9a49-6b2bcff05e2b

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "R$ #,,,.00B",
				    ABS( _valor) >= 1E6, "R$ #,,.00M",
				    ABS( _valor) >= 1E3, "R$ #,.00K",
				    "R$ #,,,0"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "R$ #,,,0",
				    1,_formatoDinamico,
				    2, "R$ #,.00K",
				    3, "R$ #,,.00M",
				    4, "R$ #,,,.00B"
				)
				
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Real_Ton = IF( SELECTEDVALUE(pRealTon[pRealTon Pedido]) = 0,[PesoFaturado] , [Faturamento] )
		displayFolder: Geral
		lineageTag: b97ba1a0-cbce-4609-bf9b-7a2b743e004e

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Real_Ton Budget' = IF( SELECTEDVALUE(pRealTon[pRealTon Pedido]) = 0,[Budget Peso] , [Faturamento_budget] )
		displayFolder: Budget
		lineageTag: 87227eee-5184-49e3-ae4c-a398465e3c50

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Real_Ton Forecast' = IF( SELECTEDVALUE(pRealTon[pRealTon Pedido]) = 0,[Forecast Peso] , [Faturamento_forecast] )
		displayFolder: Forecast
		lineageTag: d6e09653-5cc1-4d35-ad50-32632f6e88ad

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Real_Ton Target' = IF( SELECTEDVALUE(pRealTon[pRealTon Pedido]) = 0,[Target Peso] , [Faturamento_target] )
		displayFolder: Target
		lineageTag: 21309ca0-e361-472a-808e-495016b96779

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				VAR _moeda= IF(SELECTEDVALUE(pRealTon[pRealTon Pedido])=1,"R$ ")
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				_moeda&
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

	measure 'Faturamento Líquido (R$/t) (EBITDA)' = SUM(febtida_artigo_coml[preco_por_ton])
		displayFolder: EBITDA
		lineageTag: f1262d17-3b73-4c96-bc74-d6b28daf0f9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Valor Negociado Sem Imposto (R$/t)' = SUM(febtida_artigo_coml[vlr_negociado_sem_imposto])
		displayFolder: EBITDA
		lineageTag: 926627af-6dce-436c-bc98-1b598504c13f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Custo Total Sem Imposto (R$/t)' = SUM(febtida_artigo_coml[custo_vnd_total_sem_imposto])
		displayFolder: EBITDA
		lineageTag: afa1316e-5b9c-4d19-bb1a-e521418dd237

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Custo marginal Sem Imposto (R$/t)' = SUM(febtida_artigo_coml[custo_vnd_marginal_sem_imposto])
		displayFolder: EBITDA
		lineageTag: eb86a110-6e88-49fe-9f09-6f6443472cdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Faturamento - Custo marginal' =
			
			VAR _calculo = [Faturamento Líquido (R$/t) (EBITDA)] - [Custo marginal Sem Imposto (R$/t)]
			RETURN
			IF(_calculo<0,_calculo)
		displayFolder: EBITDA
		lineageTag: 80b5f0c7-0dd0-43f0-b07a-0a745f59b68a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Especificacao EBITDA' = IF(AND(ISINSCOPE(dArtigo[id_artigo_original]),[Faturamento Líquido (R$/t) (EBITDA)]),SELECTEDVALUE(dArtigo[especificacao]))
		displayFolder: EBITDA
		lineageTag: 079e41c0-ecb9-4fab-8c9f-499e05c14d9e

	measure 'espessura EBITDA' = IF(AND(ISINSCOPE(dArtigo[id_artigo_original]),[Faturamento Líquido (R$/t) (EBITDA)]),SELECTEDVALUE(dArtigo[espessura_mm]))
		formatString: 0.000
		displayFolder: EBITDA
		lineageTag: 2d3fbb72-7f15-4614-9320-0a4e2fbaf9b6

	measure 'largura EBITDA' = IF(AND(ISINSCOPE(dArtigo[id_artigo_original]),[Faturamento Líquido (R$/t) (EBITDA)]),SELECTEDVALUE(dArtigo[largura_mm]))
		formatString: 0.000
		displayFolder: EBITDA
		lineageTag: 9d9ba2a2-8b33-4283-9b96-997ea4f64889

	measure 'comprimento EBITDA' = IF(AND(ISINSCOPE(dArtigo[id_artigo_original]),[Faturamento Líquido (R$/t) (EBITDA)]),SELECTEDVALUE(dArtigo[comprimento_mm]))
		formatString: 0.000
		displayFolder: EBITDA
		lineageTag: 87cc1284-4355-4f56-8d67-276be4aa4e13

	measure 'Cor Valor Negociado' = IF([Valor Negociado Sem Imposto (R$/t)]<[Faturamento Líquido (R$/t) (EBITDA)],"#FF5353")
		displayFolder: EBITDA
		lineageTag: 6192d39a-faa2-4ded-a694-d02ede7af4b4

	measure 'Cor Custo Marginal S/I' = IF([Faturamento Líquido (R$/t) (EBITDA)]<[Custo marginal Sem Imposto (R$/t)],"#FF5353")
		displayFolder: EBITDA
		lineageTag: 30284a99-20e0-4e87-8661-4f61a9cbd7dd

	measure 'HTML CSAT_3' = ```
			
			// Configurações gerais
			VAR BaAlt = 30 --Altura da barra
			VAR CorTexto = "#003A69"
			VAR CorPositivo = "#8B9D9B"
			VAR CorNegativo = "#B22222"
			VAR Prop_Barra = 1.3  -- Multiplicador que define a posição da linha da meta / tamanho da barra (se é comum superar a meta de forma expressiva, colocar um valor maior)
			VAR _selecaoFormato = SELECTEDVALUE(pFormato[sFormato Pedido])
			VAR _ano = MAX(dCalendario[ano])
			
			// Cálculos|Medidas
			VAR _Faturamento = [Faturamento Líquido (EBITDA)]
			
			--Gross Profit R$/ton
			VAR _ComTempera = CALCULATE([Reclamações por ton],dArtigo[temperado]<>"*")
			VAR _Meta =  MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _ano, fMetas_Reclamacao[TipoMeta] = "RR/1000t_fat_temp" ),fMetas_Reclamacao[Meta])
			VAR __Prop_vsMeta_Valor = DIVIDE(_ComTempera,_Meta)
			
			--Gross Profit %
			VAR _SemTempera =  CALCULATE([Reclamações por ton],dArtigo[temperado]="*")
			VAR _MetaPerc = MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _ano, fMetas_Reclamacao[TipoMeta] = "RR/1000t_fat_nao_temp" ),fMetas_Reclamacao[Meta])
			VAR _SemTempera_Prop_vsMeta_Valor = DIVIDE(_SemTempera,_MetaPerc)
			
			//Cálculos auxiliares para formatação das barras
			
			--Proporção Barra
			VAR PropGMValor = IF(_ComTempera>_Meta, _ComTempera*1.1,_Meta * Prop_Barra) 
			VAR PropGMPerc = IF(_SemTempera>_MetaPerc, _SemTempera*1.1,_MetaPerc * Prop_Barra) --_MetaPerc * Prop_Barra
			
			-- Cor da Barra
			VAR CorGM = IF(_ComTempera <= _Meta, CorPositivo, CorNegativo)
			VAR CorGMPerc = IF(_SemTempera <= _MetaPerc, CorPositivo, CorNegativo)
			
			--Cor texto
			VAR CorTextGM = IF(_ComTempera <= _Meta, "black", "white")
			VAR CorTextGMPerc = IF(_SemTempera <= _MetaPerc, "black", "white")
			
			//Valores Formatados para o rótulo
			VAR _SemTempera_F = FORMAT(_SemTempera,"#0.00")
			
			var _ComTempera_F = FORMAT(_ComTempera,"#0.00")
			// FORMAT(_ComTempera,
			//     SWITCH(
			//         _selecaoFormato,
			//         0, "#,,,0",
			//         1,SWITCH(
			//                 TRUE(),
			//                 ABS( _ComTempera) >= 1E9, "#,,,.00B",
			//                 ABS( _ComTempera) >= 1E6, "#,,.00M",
			//                 ABS( _ComTempera) >= 1E3, "#,.00K",
			//                 "#,,,0"
			//             ),
			//         2, "#,.00K",
			//         3, "#,,.00M",
			//         4, "#,,,.00B"
			//     )
			// )
			
			
			VAR _selecaoIdioma = SELECTEDVALUE(pIdioma[Ordem])
			VAR _comercial = 
			SWITCH(_selecaoIdioma,
			        1,"EBITDA Comercial",
			        2,"Kommerziell EBITDA",
			        3,"Commercial EBITDA"
			)
			VAR _Target = 
			SWITCH(_selecaoIdioma,
			        1,"Meta",
			        2,"Ziel",
			        3,"Target"
			)
			VAR _title = 
			SWITCH(_selecaoIdioma,
			        1,"Reclamações por 1000 ton faturada",
			        2,"Beschwerden pro 1000 fakturierte Tonnen",
			        3,"Complaints per 1000 tons billed"
			)
			VAR _ct = 
			SWITCH(_selecaoIdioma,
			        1,"Com Têmpera",
			        2,"Band vergütet",
			        3,"With Tempering"
			)
			VAR _st = 
			SWITCH(_selecaoIdioma,
			        1,"Sem Têmpera",
			        2,"Band unvergütet",
			        3,"Without Tempering"
			)
			
			VAR _TextoAcima = 
			    SWITCH(_selecaoIdioma,
			    1," acima da meta",
			    2," über dem Ziel",
			    3," above target"
			    )
			
			VAR _TextoAbaixo = 
			    SWITCH(_selecaoIdioma,
			    1," abaixo da meta",
			    2," Im Ziel",
			    3, " Within  target"
			    )
			VAR _VariaPerc = DIVIDE(_ComTempera - _Meta, _Meta)
			VAR _Varia2Perc = DIVIDE(_SemTempera - _MetaPerc, _MetaPerc)
			VAR _PERC1 = round(DIVIDE(_Meta,PropGMValor)*100,0)
			VAR _PERC2 = round(DIVIDE(_MetaPerc,PropGMPerc)*100,0)
			RETURN
			"
			<html>
			<body>
			    <span class='title'>"&_title&"</span>
			    <div class='separador3'></div>
			
			    <!-- Com Têmpera -->
			    <div class='corpo'>
			        <span class='header'>"&_ct&"</span>
			        <div class='separador3'></div>
			        <span class='sub_header'>"&FORMAT(ABS(_VariaPerc),"#0.00%")&IF(_Meta<_ComTempera,_TextoAcima,_TextoAbaixo)&" 
			            <span style='color:"&CorGM&"; position:absolute; left:"&_PERC1&"%'; transform: translateX(-50%); top:-20px; font-size:12px;'>
			                <b>"&IF(_PERC1<=55,"",_Meta)&"</b>
			            </span>
			        </span>
			        <!-- Estrutura da barra -->
			        <div style='position:relative'>
			            <span class='BarraFundo'></span>
			            <span style='width: "& round(DIVIDE(_ComTempera,PropGMValor)*100,0) &"%; background-color: "& CorGM &"; position:absolute; height:"&BaAlt&"px'></span>
			            <span style='width: 1px; background-color: black; height:"&BaAlt&"px; position:absolute;left:"&_PERC1&"%'></span>
			            <span style='height:"&BaAlt&"px; position:relative; color:"&CorTextGM&"; font-size: 14px; padding-left:5px; vertical-align:sub'>"&_ComTempera_F&"</span>
			        </div>
			        <div class='separador2'></div>
			        <span class='sub_header'>"&" 
			            <span style='color:"&CorGM&"; position:absolute; left:"&_PERC1&"%'; transform: translateX(-50%); top:-20px; font-size:12px;'>
			                <b>"&IF(_PERC1>=55,"",_Meta)&"</b>
			            </span>
			        </span>
			    </div>
			
			
			
			    <div class='separador'></div>
			
			    <!-- Sem Têmpera -->
			    <div class = 'corpo'>
			        <span class='header'>"&_st&"</span>
			        <div class='separador3'></div>
			        <span class='sub_header2'>"&FORMAT(ABS(_Varia2Perc),"#0.00%")&IF(_MetaPerc<_SemTempera,_TextoAcima,_TextoAbaixo)&" 
			            <span style='color:"&CorGMPerc&"; position:absolute; left:"&_PERC2&"%'; transform: translateX(-50%); top:-20px; font-size:12px;'>
			                <b>"&IF(_PERC2<=55,"",_MetaPerc)&"</b>
			            </span>
			        </span>
			        <!-- Estrutura da barra -->
			        <div>
			            <span class= 'BarraFundo'></span>
			            <span style='width: "& round(DIVIDE(_SemTempera,PropGMPerc)*100,0) &"%; background-color: "& CorGMPerc &"; position:absolute; height:"&BaAlt&"px'></span>
			            <span style='width: 1px; background-color: black; height:"&BaAlt&"px; position:absolute;left:"&_PERC2&"%'></span>
			            <span style='height:"&BaAlt&"px; position:relative; color:"&CorTextGMPerc&"; font-size: 14px; padding-left:5px; vertical-align:sub'>"&_SemTempera_F&"</span>
			        </div>
			        <div class='separador2'></div>
			        <span class='sub_header'>"&" 
			            <span style='color:"&CorGMPerc&"; position:absolute; left:"&_PERC2&"%'; transform: translateX(-50%); top:-20px; font-size:12px;'>
			                <b>"&IF(_PERC2>=55,"",_MetaPerc)&"</b>
			            </span>
			        </span>
			    </div>
			   
			    </div>
			</body>
			<style>
			    .corpo {
			        margin-top:-2px;
			        display: flex;
			        flex-direction: column;
			        width:100%;
			    }
			    .title {
			        color: "&CorTexto&";
			        font-size: 14px;
			        font-weight: bold;
			        font-family: Segoe Ui;
			    }
			    .header {
			        color: "&CorTexto&";
			        font-size: 12px;
			        font-weight: bold;
			        font-family: Segoe Ui;
			    }
			    .sub_header{
			        font-size: 8px;
			        font-family: Segoe Ui;
			        color: "&CorGM&";
			        margin-top: -4px;
			        font-weight: 500;
			    }
			    .sub_header2{
			        font-size: 8px;
			        font-family: Segoe Ui;
			        color: "&CorGMPerc&";
			        margin-top: -4px;
			        font-weight: 500;
			    }
			    .BarraFundo{
			        width: 100%; 
			        background-color: #D3D3D3;
			        height: "&BaAlt&"px; 
			        position: absolute;
			    }
			    .separador{
			        height:8px
			    }
			    .separador2{
			        height:7px
			    }
			    .separador3{
			        height:5px
			    }
			</style>
			</html>
			"
			```
		displayFolder: HTML
		lineageTag: 20bb05f7-45f0-4030-ac56-878f2a76a82c

	measure 'Reclamacoes por ton com tempera' =
			
			CALCULATE(
			    [Reclamações por ton],
			    dArtigo[temperado] <> "*"
			)
		displayFolder: Reclamação e CSAT
		lineageTag: f69d1e12-5621-45b0-a51a-e402b8846832

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reclamacoes por ton sem tempera' =
			
			CALCULATE(
			    [Reclamações por ton],
			    dArtigo[temperado] = "*"
			)
		displayFolder: Reclamação e CSAT
		lineageTag: 5671de11-8d7e-43fb-a626-8e09fa9fce58

		formatStringDefinition = ```
				VAR _valor = SELECTEDMEASURE()
				Var _selecao = SELECTEDVALUE(pFormato[sFormato Pedido])
				var _formatoDinamico = 
				SWITCH(
				    TRUE(),
				    ABS( _valor) >= 1E9, "#,,,.00B",
				    ABS( _valor) >= 1E6, "#,,.00M",
				    ABS( _valor) >= 1E3, "#,.00K",
				    "#,,,0.00"
				)
				
				RETURN
				
				SWITCH(
				    _selecao,
				    0, "#,,,0.00",
				    1,_formatoDinamico,
				    2, "#,.00K",
				    3, "#,,.00M",
				    4, "#,,,.00B"
				)
				```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reclamacoes 1000t grafico' =
			
			VAR _selecao = SELECTEDVALUE(pReclamacao[id])
			
			RETURN
			SWITCH(
			    TRUE(),
			    _selecao IN {0,3,6}, [Reclamações por ton],
			    _selecao IN {1,4,7}, [Reclamacoes por ton com tempera],
			    _selecao IN {2,5,8}, [Reclamacoes por ton sem tempera]
			)
		displayFolder: Reclamação e CSAT
		lineageTag: 32a247c1-e572-4b77-affd-ce3c8681ee0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta Reclamacao grafico' =
			
			VAR _selecao = SELECTEDVALUE(pReclamacao[id])
			VAR _Ano = MAX(dCalendario[ano])
			
			RETURN
			SWITCH(
			    TRUE(),
			    _selecao IN {0,3,6}, MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _Ano, fMetas_Reclamacao[TipoMeta] = "RR/1000t_fat_geral" ),[Meta]) ,
			    _selecao IN {1,4,7}, MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _Ano, fMetas_Reclamacao[TipoMeta] = "RR/1000t_fat_temp" ),[Meta]),
			    _selecao IN {2,5,8}, MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _Ano, fMetas_Reclamacao[TipoMeta] = "RR/1000t_fat_nao_temp" ),[Meta])
			)
		displayFolder: Reclamação e CSAT
		lineageTag: dfe245b7-d045-47a0-9a8a-cd7254e609dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'tons reclamados por faturados' = ```
			
			VAR _selecao = SELECTEDVALUE(pReclamacao[id])
			
			RETURN
			SWITCH(
			    TRUE(),
			    _selecao IN {0,3,6}, 
			    DIVIDE(
			    CALCULATE(
			        SUM(fReclamacao[peso_reclamado]),
			        dDecisao_reclamacao[id_decisao] <> 1
			    ),[PesoFaturado]
			    ,0
			),
			    _selecao IN {1,4,7}, 
			    DIVIDE(
			        CALCULATE(
			            SUM(fReclamacao[peso_reclamado]),
			            dDecisao_reclamacao[id_decisao] <> 1,
			            dArtigo[temperado] <>"*"
			        ),CALCULATE([PesoFaturado],dArtigo[temperado] <>"*")
			        ,0
			    ),
			    _selecao IN {2,5,8}, 
			    DIVIDE(
			        CALCULATE(
			            SUM(fReclamacao[peso_reclamado]),
			            dDecisao_reclamacao[id_decisao] <> 1,
			            dArtigo[temperado] ="*"
			        ),CALCULATE([PesoFaturado],dArtigo[temperado] ="*")
			        ,0
			    )
			)
			```
		displayFolder: Reclamação e CSAT
		lineageTag: ad1246bf-931c-4a71-a49c-24475033bb21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta ton rec_fat' = ```
			
			VAR _selecao = SELECTEDVALUE(pReclamacao[id])
			var _Ano = Max(dCalendario[ano])
			
			RETURN
			SWITCH(
			    TRUE(),
			    _selecao IN {0,3,6}, MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _Ano, fMetas_Reclamacao[TipoMeta] = "PesoReclamado/PesoFaturado_geral" ),[Meta]) ,
			    _selecao IN {1,4,7}, MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _Ano, fMetas_Reclamacao[TipoMeta] = "PesoReclamado/PesoFaturado_temp" ),[Meta]),
			    _selecao IN {2,5,8}, MAXX(CALCULATETABLE(fMetas_Reclamacao,fMetas_Reclamacao[Ano] = _Ano, fMetas_Reclamacao[TipoMeta] = "PesoReclamado/PesoFaturado_nao_temp" ),[Meta])
			)
			
			```
		displayFolder: Reclamação e CSAT
		lineageTag: 07a817f7-820b-40f0-bece-c0b9cc3c7848

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Max_Medidor_tonRecFat = MAX([Meta ton rec_fat],[tons reclamados por faturados])*1.5
		displayFolder: Reclamação e CSAT
		lineageTag: 62dd2a91-8c0c-45a0-9b85-f188c46fc7d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: bf3c8107-1b44-4732-8a80-f227cce929c1
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

