table dGerencia
	lineageTag: a93bc0a4-670c-4ed3-9087-57c43bcc7af9

	column id_gerencia
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6a2bf7e6-9722-43b2-85f8-c5a7a51f851c
		summarizeBy: none
		sourceColumn: id_gerencia

		annotation SummarizationSetBy = Automatic

	column gerente
		dataType: string
		lineageTag: 6e610887-3e8f-4cc5-8a3b-9a6097e76854
		summarizeBy: none
		sourceColumn: gerente

		annotation SummarizationSetBy = Automatic

	column representante
		dataType: string
		lineageTag: d810a17d-c0ff-4c7d-8461-3641458144b2
		summarizeBy: none
		sourceColumn: representante

		annotation SummarizationSetBy = Automatic

	column gestor
		dataType: string
		lineageTag: a8634301-0c42-48e6-adaf-f38dac175918
		summarizeBy: none
		sourceColumn: gestor

		annotation SummarizationSetBy = Automatic

	partition dGerencia = m
		mode: import
		queryGroup: Dimensão
		source =
				let
				    Fonte = Sql.Database(server, Banco, [CreateNavigationProperties=false, Query="Select * from vw_dGerencia"]),
				    Primeiro_Maiusculo = Table.TransformColumns(Fonte,{{"gerente", Text.Proper, type text}, {"representante", Text.Proper, type text}, {"gestor", Text.Proper, type text}})
				in
				    Primeiro_Maiusculo

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

