table transacoes
	lineageTag: a2ea0539-01d0-4db8-80c6-e636bd9e661b

	measure Measure = 1
		formatString: 0
		lineageTag: 426ca903-554a-47b0-bba1-58442b981d16

	column ID
		dataType: double
		lineageTag: 083579d1-7f18-4161-9ab4-29779f8bbfb9
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: a57c9e4e-fca8-4557-af0c-bb8d2912323e
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Total
		dataType: double
		lineageTag: 6fbaa04a-9c03-46e6-a826-86e9e1f283fc
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		lineageTag: a6446b01-61d4-4047-bf46-0c4aa455db1a
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

